### ISSUE TITLE
[Feature Request] Smart Playlist Files

### ISSUE THREAD

**Issue by trymeouteh** [AdrienPoupa/VinylMusicPlayer#100]
Please create a smart playlist file type which can store data on a start playlist and be used in Vinyl. The playlist could use XML as a markup and be called a vpl file (Vinyl Playlist).

Many music players have built-in app playlist that are not files but are saved within the app but this is not a good option since these playlist cannot be backed up and cannot be transferred or synced across devices. Since Vinyl Music Player is a basic music player which requires the user to manage their music files it will not too hard for the users to manage playlist files. This is also handy when you have multiple android devices like a phone and tablet and the ability to easily copy a playlist file from device to device.

**Comment by GeoZac** [comment]
@trymeouteh  The player already has support for `*.m3u` files.Also there is a feature to save created playlists as files.These playlist will work on multiple devices as long as files are found on the location specified on `*m3u` files.

**Comment by trymeouteh** [comment]
I am requesting smart playlists not regular playlists. Most music players that use smart playlists will save the playlist within the app. iTunes for example has smart playlists but these playlists are saved into iTunes and are not files themselves. Windows Media Player is the only music player that supports smart playlists as a file (In WMP it is called auto playlists).

I would like to see Vinyl support smart playlists and be able to manage these playlists as files and I am suggesting to create a new file type and use XML as a markdown to make this happen. You could support the smart playlists Windows Media Player uses also.

**Comment by AdrienPoupa** [comment]
We'll stick with m3u files for now, unless you can submit a PR with your request.
