### ISSUE TITLE
[Bug] Crash when tapping on "Library Categories" setting

### ISSUE THREAD

**Issue by RobBrazier** [AdrienPoupa/VinylMusicPlayer#102]
I found that the app crashes when "Settings -> Library categories" is tapped. 

Expected:
--
View opened to rearrange/toggle library categories

Actual:
--
App crashed

Device info:
--
<table>
<tr><td>App version</td><td>0.19.1</td></tr>
<tr><td>App version code</td><td>159</td></tr>
<tr><td>Android build version</td><td>d646e332a7</td></tr>
<tr><td>Android release version</td><td>8.1.0</td></tr>
<tr><td>Android SDK version</td><td>27</td></tr>
<tr><td>Android build ID</td><td>lineage_oneplus3-userdebug 8.1.0 OPM7.181205.001 d646e332a7</td></tr>
<tr><td>Device brand</td><td>OnePlus</td></tr>
<tr><td>Device manufacturer</td><td>OnePlus</td></tr>
<tr><td>Device name</td><td>OnePlus3T</td></tr>
<tr><td>Device model</td><td>ONEPLUS A3003</td></tr>
<tr><td>Device product name</td><td>lineage_oneplus3</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Logs:
--
```
01-22 06:39:50.097 E/AndroidRuntime(5994): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.constraint.ConstraintLayout" on path: DexPathList[[zip file "/data/app/com.poupa.vinylmusicplayer-5vQ71tj0VBxMEh0FYu2ScQ==/base.apk", zip file "/data/app/com.poupa.vinylmusicplayer-5vQ71tj0VBxMEh0FYu2ScQ==/split_config.en.apk", zip file "/data/app/com.poupa.vinylmusicplayer-5vQ71tj0VBxMEh0FYu2ScQ==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.poupa.vinylmusicplayer-5vQ71tj0VBxMEh0FYu2ScQ==/lib/arm64, /system/lib64, /system/vendor/lib64]]
01-22 06:39:50.097 E/AndroidRuntime(5994): 	at com.poupa.vinylmusicplayer.preferences.LibraryPreferenceDialog.onCreateDialog(Unknown Source:12)
``` 

Hopefully those logs are enough. I can get some more if you want, however the rest are either chatty or "No original dex files found for dex location"

**Comment by AdrienPoupa** [comment]
Thanks for the report, it is now fixed!
