### ISSUE TITLE
[Feature request]  Crossfader

### ISSUE THREAD

**Issue by Nathoufresh** [AdrienPoupa/VinylMusicPlayer#105]
Add a crossfader between streams. Also add settings to enable and customize it ( set the duration of the fade) as in Rhythmbox [https://github.com/GNOME/rhythmbox](url)

**Comment by Cantuariensis** [comment]
Deezer had a very good implementation of it in the HTML5 web player:
![67e7b3de-3a90-4716-89e0-dffd8ff8e0bb](https://user-images.githubusercontent.com/62208363/76703749-26e71600-66d4-11ea-9681-64a75f31e603.jpg)
