### ISSUE TITLE
artist names with a hyphen not showing

### ISSUE THREAD

**Issue by wiscxrise** [AdrienPoupa/VinylMusicPlayer#106]
Artists with "-" in their name won't display in the artists tab. You can, however, find the artist by using the search function

-

Device info:
---
<table>
<tr><td>App version</td><td>0.19.2</td></tr>
<tr><td>App version code</td><td>160</td></tr>
<tr><td>Android build version</td><td>5180536</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PQ2A.190205.003</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>marlin</td></tr>
<tr><td>Device model</td><td>Pixel XL</td></tr>
<tr><td>Device product name</td><td>marlin</td></tr>
<tr><td>Device hardware name</td><td>marlin</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by AdrienPoupa** [comment]
Hi, I can't reproduce it as I see artists containing hyphens in my database. Could you send me a problematic file at adrien at poupa dot fr please? Thanks!
