### ISSUE TITLE
Missing font

### ISSUE THREAD

**Issue by ziqitsai** [AdrienPoupa/VinylMusicPlayer#107]
I am a Chinese user. After updating to the latest version, I found that all song names, artists and album names cannot be displayed.

-

Device info:
---
<table>
<tr><td>App version</td><td>0.20.1</td></tr>
<tr><td>App version code</td><td>162</td></tr>
<tr><td>Android build version</td><td>C01B243</td></tr>
<tr><td>Android release version</td><td>6.0</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>CAM-TL00C01B243</td></tr>
<tr><td>Device brand</td><td>HONOR</td></tr>
<tr><td>Device manufacturer</td><td>HUAWEI</td></tr>
<tr><td>Device name</td><td>HWCAM-H</td></tr>
<tr><td>Device model</td><td>CAM-TL00</td></tr>
<tr><td>Device product name</td><td>CAM-TL00</td></tr>
<tr><td>Device hardware name</td><td>hi6210sft</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by RodolfoCandido** [comment]
I have the same issue after the upgrade (using F-Droid), but is Roman alphabet (portuguese language). All fonts are missing the same way.

**Comment by AdrienPoupa** [comment]
Strange. Was it working before? Can you give me an example of a broken display?

**Comment by zJoul** [comment]
I have the exact same problem. I've upgraded this morning with F-Droid.
I have both latin and non-latin filenames

Some screenshots :
![screenshot_20190225-082555](https://user-images.githubusercontent.com/5512504/53327215-a77b7e80-38e7-11e9-84e7-2b81cf10b0ec.png)
![screenshot_20190225-082559](https://user-images.githubusercontent.com/5512504/53327217-a77b7e80-38e7-11e9-8f96-b2101b885174.png)
![screenshot_20190225-082604](https://user-images.githubusercontent.com/5512504/53327218-a77b7e80-38e7-11e9-86bc-019f87773e9f.png)
![screenshot_20190225-082613](https://user-images.githubusercontent.com/5512504/53327219-a77b7e80-38e7-11e9-9705-05e8d0a2c60b.png)

**Comment by AdrienPoupa** [comment]
That's troubling indeed. I tried on my 7.0 and 8.1 devices and can't reproduce your issue. I will try using a virtual 6.0 device. What are your specs @zJoul ?

I believe this is related to https://github.com/AdrienPoupa/VinylMusicPlayer/commit/ba0dfae7dd03771f3625b8393927986aad552e2a

**Comment by AdrienPoupa** [comment]
Reproduced in Android 6
![image](https://user-images.githubusercontent.com/15086425/53351331-17413780-38ef-11e9-8194-56a6cb9cebfc.png)

**Comment by zJoul** [comment]
I'm on Android 6.0 indeed

Device info:
---
<table>
<tr><td>App version</td><td>0.20.1</td></tr>
<tr><td>App version code</td><td>162</td></tr>
<tr><td>Android build version</td><td>3</td></tr>
<tr><td>Android release version</td><td>6.0</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MPI24.65-39-4</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>surnia_umts</td></tr>
<tr><td>Device model</td><td>MotoE2(4G-LTE)</td></tr>
<tr><td>Device product name</td><td>surnia_reteu</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by AdrienPoupa** [comment]
I found where the problem comes from but it's harder to fix than expected...
https://stackoverflow.com/questions/54874431/onmeasure-returning-widthmeasurespec-0-in-horizontalscrollview-in-android-6

**Comment by buteo2** [comment]
Unfortunately I've got the very same problem, running Android 4.4.4

**Comment by AdrienPoupa** [comment]
That should do it: https://github.com/AdrienPoupa/VinylMusicPlayer/commit/e8dc9379105c9091597a4eeb4c96cc00f8be3259

Publishing the release now
