### ISSUE TITLE
[Feature request] Android Auto support

### ISSUE THREAD

**Issue by dugite-code** [AdrienPoupa/VinylMusicPlayer#108]
Currently you cannot access vinyl in android auto, and would be a nice addition

https://developer.android.com/training/auto/audio/

**Comment by AdrienPoupa** [comment]
Good point. @arkon did a [great job](https://github.com/kabouzeid/Phonograph/pull/283) on Phonograph with some bugs still left to fix. I backported his changes here so we can work on those bugs.

**Comment by arkon** [comment]
Probably worth looking at what was commented over there too:

> “How to paginate MediaBrowserService” by Giora Shevach [link.medium.com/xOkh066WjT](https://link.medium.com/xOkh066WjT)

I feel like [this issue](https://github.com/kabouzeid/Phonograph/issues/206) because we're not using MediaSessions / queues properly.

**Comment by AdrienPoupa** [comment]
Both Shuttle and Musicolet do not display album covers in lists. Also, the issue has been reported in https://github.com/googlesamples/android-UniversalMusicPlayer/issues/235

So for now, maybe we should just drop support for that.

For the queue, since Shuttle got it working, I'll look at their code to see how they have done.

**Comment by paolovalerdi** [comment]
Shuttle is using MedisBrowserCompat to list the available media and MedisBrowserService, any of these are used in phonograph. If these were implemented not only Auto would be possible but also wear and cast. It's worth to see how it's implemented on TimberX: https://github.com/naman14/TimberX

**Comment by AdrienPoupa** [comment]
@paolovalerdi Thanks for the link. i'll try to have a look. In the meantime, you can look at [my PR](https://github.com/AdrienPoupa/VinylMusicPlayer/pull/113) and tell me if you have any ideas :)

@arkon same, in case you may know what's going on there.

**Comment by AdrienPoupa** [comment]
Seems like this is more challenging than expected. I opened a ticket on Google's bug tracker, we'll follow the progress of that in the PR.
