### ISSUE TITLE
Bug: No text in folder-view in v0.20.1

### ISSUE THREAD

**Issue by HardCode4All** [AdrienPoupa/VinylMusicPlayer#110]
Yesterday I installed the v0.20.1 and had to revert to 0.19.0, because the new version shows "blank" folder structures throughout:

![screenshot_2019-02-26-00-19-33](https://user-images.githubusercontent.com/38424724/53392318-54620400-3999-11e9-80fa-7017b2bbca9a.png)
![screenshot_2019-02-26-00-19-49](https://user-images.githubusercontent.com/38424724/53392319-54620400-3999-11e9-820c-d2519a96c4cf.png)

I tried switching dark/light themes and re-starting Vinyl but to no avail.

PS: this is Android 6.0.1 in a Samsung Galaxy S5 Mini.

**Comment by Keith94** [comment]
No such bug on Android 8.0 on Galaxy A8.

![screenshot_20190225-230459_vinyl music player](https://user-images.githubusercontent.com/5490615/53393717-f3fba400-3951-11e9-848a-027ff313868b.jpg)

**Comment by HardCode4All** [comment]
Is that a helpful comment?

**Comment by zJoul** [comment]
Maybe it's the same issue as #107

**Comment by HardCode4All** [comment]
That could actually be the case! I didn't see that issue. I will check the 0.20.2 and come back here with the result.

**Comment by AdrienPoupa** [comment]
Yes it should be the same.

**Comment by HardCode4All** [comment]
Any idea when this will be available at F-Droid?

**Comment by AdrienPoupa** [comment]
Whenever their bot finally builds the version

**Comment by HardCode4All** [comment]
Hmmm...

> Could not find com.github.kabouzeid:AndroidSlidingUpPanel:3.3.0-kmod3.
  Required by:
      project :app

Oh well. I guess I can live with the older version a bit longer ;)

**Comment by AdrienPoupa** [comment]
Nothing changed at this level, it shouldn't fail for this reason. F-Droid's builds really are unreliable

**Comment by GeoZac** [comment]
@AdrienPoupa The build issue was reported in the upstream project [here](https://github.com/kabouzeid/Phonograph/issues/655)and is expected to be patched in a future release.

**Comment by AdrienPoupa** [comment]
@GeoZac how does it make sense since the same version was used in builds that succeeded?

**Comment by GeoZac** [comment]
@AdrienPoupa Fdroid's build system may not have been able to access the dependency,the artifacts may have been moved

**Comment by AdrienPoupa** [comment]
OK, in this case I'm not sure how changing the version would do anything
