### ISSUE TITLE
App crashes on start

### ISSUE THREAD

**Issue by buteo2** [AdrienPoupa/VinylMusicPlayer#112]
Alright, so after you fixed the "missing font"-Bug I updated the app and now it crashes directly on start. "Unfortunately Vinyl Music Player has stopped." I'm trying to get the crash log...
Don't know if it's helpful, some additional device info. If you need something special let me now. 

App version | 0.20.1
Android release version | 4.4.4
Android SDK version | 19
Board | MSM8226
Build Nr. | 18.3.1.C.1.17
Device manufacturer | Sony
Device name | D2303
Device model | Xperia M2
CPU_ABI | [armeabi-v7a]
CPU_ABI2 | [armeabi]

Thanks so far.

**Comment by AdrienPoupa** [comment]
Hi, the latest version is 0.20.2. Otherwise, I'm not sure why it crashes but I didn't test it on 4.4.4

**Comment by AdrienPoupa** [comment]
I tested the application on a virtual device, everything is working as it should, so not sure why you'd have this error

**Comment by buteo2** [comment]
Hi, thank you for the effort. Excuse my inacurracy. I updated the last version from F-Droid, which seems to be 0.20.1 but I guess the 0.20.2 will be available soon, then. I will get back to you if I tested it.

**Comment by AdrienPoupa** [comment]
The latest version failed to build on Fdroid for some reason unfortunately. I'd advise to stay on 0.19.2 until the build succeeds
