### ISSUE TITLE
[BUG] ReplayGain disabled when playing next track

### ISSUE THREAD

**Issue by darkvadd7** [AdrienPoupa/VinylMusicPlayer#115]
When playing an album with ReplayGain (album) activated, it is automatically disabled when start playing next track. I have to go in the settings during playing to re-able it (it's not visible in the settings it is disabled, but I can hear it).

**Comment by AdrienPoupa** [comment]
Hi, would you have a file to share that triggers this behavior?

**Comment by darkvadd7** [comment]
No specific file, it works with every file that have ReplayGain tags.
Thanks.

**Comment by darkvadd7** [comment]
After more tries, it seems to work now.
Thanks.
