### ISSUE TITLE
Tags missing for .m4a (+ cannot change them)

### ISSUE THREAD

**Issue by braniii** [AdrienPoupa/VinylMusicPlayer#116]
Vinyl Player: 0.20.1 F-DROID
Android: LineageOS 16 with microG (Android Pie without GAPPS)
How to reproduce: Download any audio file with NewPipe as .m4a. Use any tag editor (e.g. vanilla music plugin) and reload librery in VinylMusicPlayer.

The player reads correctly the tag of .m4a files and shows it within the app. But once I tap on "edit tags" (hopefully correctly translated), all fields are empty. Trying to modify them fails as well.

**Comment by qxzcode** [comment]
I was having this issue too, but new .m4a files downloaded with NewPipe no longer have this problem, even for the same videos. NewPipe/YouTube must have changed something.
