### ISSUE TITLE
[BUG] Not all artists are shown

### ISSUE THREAD

**Issue by braniii** [AdrienPoupa/VinylMusicPlayer#117]
Vinyl Player: 0.20.1 F-DROID
Android: LineageOS 16 with microG (Android Pie without GAPPS)

I have several songs (.mp3 and .m4a) which are listed correctly (with name and artist) in the songs-tab but not in the artist tab. This happens always if all songs from an artist are missing the "album"-tag. Adding it to a single one, adds the artist with all other songs to the artist tab.

**Comment by AdrienPoupa** [comment]
Hi,
Can you see them with other apps relying on Android MediaStore?

**Comment by braniii** [comment]
Thanks for looking into this issue. On Phonograph, no. But both, vanilla music and the default lineage os music app, are able to display them correctly (I'm not sure which library they use).

If you can tell me some music apps relying on Android MediaStore, I'll try them as well.

**Comment by AdrienPoupa** [comment]
Ok, it seems to be related to Vinyl then. I'll have a look eventually
