### ISSUE TITLE
Highlight currently playing song in list

### ISSUE THREAD

**Issue by dbr** [AdrienPoupa/VinylMusicPlayer#127]
Small thing but it would be useful to have the currently playing song highlighted when browsing through the music library

For example, currently the second song in the list is playing:

<img src="https://user-images.githubusercontent.com/509/55209668-b2e9fe80-5233-11e9-93f3-83a4340adba9.jpg" height="350px">

It would be helpful if that second item was visually distinguished form the others in some way - Google Play Music replaces the track number with a "currently playing" icon. Spotify displays this by colouring the current song's title green:

<img src="https://user-images.githubusercontent.com/509/55209815-63580280-5234-11e9-88fe-3cc2e8ec3fc9.jpg" height="350px">

**Comment by soncaokim** [comment]
i'm looking into this - intend to make it visible on search/album/artist/playlist pages

**Comment by soncaokim** [comment]
See https://github.com/AdrienPoupa/VinylMusicPlayer/pull/136.

**Comment by soncaokim** [comment]
This is released with version 0.22.0

**Comment by dbr** [comment]
Thanks for this; been using it recently and it's a small but nice improvement!
