### ISSUE TITLE
library scanning not working on new files

### ISSUE THREAD

**Issue by rapha8l** [AdrienPoupa/VinylMusicPlayer#128]
Version 0.20.1
android 9

Hello,
First thanks for your player that works great and is open source.
As I'm not using it since long, I can't tell if it's a new problem : 
I have my music files on a sdcard, and if I add some new (mtp or abd-sync), rescanning library does not add them, though they are present on filesystem.
I have to unmount/remount sdcard and go back from scratch to get new songs added

Have a nice day

**Comment by pieqq** [comment]
Hey, just a quick question: did you check with another music app if the newly added files were available there?

**Comment by rapha8l** [comment]
Indeed, I forgot this, it was not available on another, though files were present
Now that I think it may not be related to Vynil player

**Comment by AdrienPoupa** [comment]
Yup, probably related to the mediastore
