### ISSUE TITLE
Increase Number of Equalisers

### ISSUE THREAD

**Issue by autofreak** [AdrienPoupa/VinylMusicPlayer#129]
Can you increase number of equalisers? I missed POP equaliser.

**Comment by AdrienPoupa** [comment]
Hi,

The equalizers are handled by your equalizer application and not vinyl.

**Comment by autofreak** [comment]
Really, but I can change to Pop equaliser using music player like Shuttle.
Such option is not available in Vinyl, this is my favourite equalizer
though.
