### ISSUE TITLE
Doesn't play well with KLWP.

### ISSUE THREAD

**Issue by aFoxWhoIsNice** [AdrienPoupa/VinylMusicPlayer#13]
I have setup a KLWP music player, and the controls never work as expected when I play from Vinyl. This is a problem on Phonograph as well. Other music players don't have this problem. Please fix this Adrien. I like this music player a lot, but I have to break away from it till you fix this.

**Comment by AdrienPoupa** [comment]
Hi,

You're talking about this one, right? https://play.google.com/store/apps/details?id=org.kustom.wallpaper&hl=en

**Comment by aFoxWhoIsNice** [comment]
Yeah man, that's the one. You can make music player for your homescreen, with controls and stuff. All, music players work with it except Vinyl, & Phonograph. So, I believe the roots of the problem is in the Phonograph source code.

**Comment by aFoxWhoIsNice** [comment]
KLWP should works the same way for everyone. The album art problem exists as well. Do try and recreate the file by getting the pro version. Then you'll understand what I mean.

**Comment by aFoxWhoIsNice** [comment]
Oh okay, so nothing for me to do right?

**Comment by AdrienPoupa** [comment]
Not for now indeed. But to reproduce it, do I need the Pro version?

**Comment by aFoxWhoIsNice** [comment]
Yeah :/ or you need to look up some tutorials on YouTube and learn how to create your own player in KLWP. That can be done for free.

**Comment by AdrienPoupa** [comment]
Ok, I'll look into that, thanks. But anyway it seems to be related to Glide according to that: https://bitbucket.org/frankmonza/kustomapi so maybe the migration to Glide v4 will change the behavior of Vinyl with KLWP. I'll keep you posted.

**Comment by aFoxWhoIsNice** [comment]
Sure thing. Thanks Adrien.

**Comment by GeoZac** [comment]
Phonograph has no conflicts with KLWP ![](https://i.imgur.com/MrkBZl8.jpg)
![](https://i.imgur.com/XT052am.jpg)
The only feature not working is mq() feature,which is being dealt by developers
