### ISSUE TITLE
New “Put song title text view into a horizontal scrollview” feature prevents from selecting/playing a song

### ISSUE THREAD

**Issue by pieqq** [AdrienPoupa/VinylMusicPlayer#131]
Vinyl v0.20.0 introduced a new feature: “Put song title text view into a horizontal scrollview”.

This has some advantages, but has a big drawback in the song list view:

![Screenshot_20190403-172157_Vinyl Music Player resized](https://user-images.githubusercontent.com/512471/55468167-5e7cbf80-5635-11e9-9a3c-61879490d57f.jpg)

the zones highlighted in red become unresponsive when tapping on it (to play the song, for instance, or to long-press the song in order to add it to a playlist).

The same issue happens in the song list:

![Screenshot_20190403-172642_Vinyl Music Player](https://user-images.githubusercontent.com/512471/55468467-fe3a4d80-5635-11e9-865c-85d8d722bd32.jpg)

I think the horizontal scrollview can be useful and not too intrusive, for instance to scroll the title of the current song in the song list (highlighted in green in the previous screenshot), since a long press on this part of the screen doesn't do anything, and since the song is already playing (play/pause are available somewhere else).

I would like to know other people's opinion and maybe come to a conclusion regarding this feature.

My personal take would be to remove it wherever it could block the actual "tap" action.

**Comment by AdrienPoupa** [comment]
Yes, this is an issue I have encountered and it is quite a blocker. I improve the mechanism which differentiates a tap and a slide. In the meantime, it's not ideal but you can tap on the artist name instead of the song name.

**Comment by soncaokim** [comment]
I agree with you on having the scrollview only on the green part, and not on the red part.

Probably make it auto-scrolling, so that it is more discoverable.

**Comment by AdrienPoupa** [comment]
@soncaokim I've been working on this bug this afternoon: https://github.com/AdrienPoupa/VinylMusicPlayer/commit/2304404868f20c4001946c617fad31924fbc7498

I've been able to greatly reduce the complexity of the feature by using a GestureDetector. Now, I'm able to handle a tap and a scroll differently.

I'm still missing a bit though: I need to trigger the click action to read the song here: https://github.com/AdrienPoupa/VinylMusicPlayer/blob/2304404868f20c4001946c617fad31924fbc7498/app/src/main/java/com/poupa/vinylmusicplayer/views/TouchInterceptHorizontalScrollView.java#L192

Any help would be appreciated :)

**Comment by AdrienPoupa** [comment]
I think I got it working! If you could confirm that it works with the latest commit that would be great.

**Comment by soncaokim** [comment]
Looks good with 7b0327c on vinyl/master

**Comment by AdrienPoupa** [comment]
Feel free to reopen if it persists
