### ISSUE TITLE
Album Art Not Saving

### ISSUE THREAD

**Issue by wablair** [AdrienPoupa/VinylMusicPlayer#135]
In the tag editor, after downloading from last.fm or selecting locally, the album art will change to the image but after saving and exiting the tag editor it returns to the default image.

-

Device info:
---
<table>
<tr><td>App version</td><td>0.20.2</td></tr>
<tr><td>App version code</td><td>163</td></tr>
<tr><td>Android build version</td><td>5310204</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PQ2A.190405.003</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>blueline</td></tr>
<tr><td>Device model</td><td>Pixel 3</td></tr>
<tr><td>Device product name</td><td>blueline</td></tr>
<tr><td>Device hardware name</td><td>blueline</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by AdrienPoupa** [comment]
Are you doing this on a SDCard?

**Comment by wablair** [comment]
No, have tried this with Pixel and Pixel 3 internal storage.

**Comment by wablair** [comment]
This is with flac files in case that matters.

**Comment by AdrienPoupa** [comment]
Ok, does it happen with other format as well?

**Comment by wablair** [comment]
It looks like it is working correctly with mp3 files.

**Comment by braniii** [comment]
This is the same issue as #116. Editing tags (including album artwork) works only for mp3.
