### ISSUE TITLE
Scanning media several times will crash the application

### ISSUE THREAD

**Issue by AdrienPoupa** [AdrienPoupa/VinylMusicPlayer#137]
**Describe the bug**
Application crashes when scanning media

**To Reproduce**
1. Tap to scan media repeatedly

**Comment by paolovalerdi** [comment]
Isn't it caused because the task is already running and two task can't be attached at the same time?

**Comment by AdrienPoupa** [comment]
Possibly, I haven't investigated yet. If so we should check for the background tasks before running a new one.
