### ISSUE TITLE
unable to play from folder view since 0.21.0

### ISSUE THREAD

**Issue by rwchhs** [AdrienPoupa/VinylMusicPlayer#139]
**Describe the bug**
Since I installed the latest update 0.21.0, I am unable to play media from the folder view. Touching a song has no effect, neither has selecting the song by long pressing and then using "add to playlist" or by using the song menu and selecting "play next". This is reproducible on all of my songs, all of which used to work before the update.
Notably, the library view is not affected (everything works as expected there, tried the same songs), only the folder view.
I have reinstalled the app as well to no effect.

**To Reproduce**
1. Go to folder view
2. Try to play any song by any means provided by the app

**Expected behavior**
The song would play.

**Smartphone (please complete the following information):**
 - Device:  LG V30 (H930)
 - Android Version: build 183202318d019, release 8.0.0, sdk 26
 - ROM: factory default
 - Vinyl Music Player Version: 0.21.0

**Comment by AdrienPoupa** [comment]
You're right, looks like this was introduced when fixing the tap bug on the library view... arg this horizontal scrollview feature is so much complex than I thought. I'll look into it soon and thanks for the report.

**Comment by AdrienPoupa** [comment]
Related to https://github.com/AdrienPoupa/VinylMusicPlayer/pull/121/files#diff-dc26bca3f9eaa3d012220d35efee533e as reverting those changes fixed the bug @soncaokim

**Comment by AdrienPoupa** [comment]
@soncaokim I reverted those changes for now, feel free to open a PR when you fixed it.

**Comment by soncaokim** [comment]
@adrienpoupa, just realized that my email response was not delivered.

Thanks for the quick reaction, I ll have a look.
