### ISSUE TITLE
Feature Request: Relative Path Playlists

### ISSUE THREAD

**Issue by trymeouteh** [AdrienPoupa/VinylMusicPlayer#141]
When you save a playlist into a m3u file the playlist songs paths are something like this...

`/storage/0000-0000/Music/Black Sabbath/13/03 Loner.flac`

It would be better if it looked like this in the m3u file

`/Black Sabbath/13/03 Loner.flac`

This way when you sync your playlists to other devices such as your computer the playlist will work in other music players. This will also make synced playlists between different Android devices using Vinyl work where device A music files are in internal storage and device B music files are on the external storage.

**Comment by k3b** [comment]
Is it possible to make the playlist-enties relative to the playlistfile?

Example

* /storage/0000-0000/Music/Black Sabbath/BlackSabbathBestOf.m3u would contain this file
* 13/03 Loner.flac

* /storage/0000-0000/Music/AllBestOf.m3u would contain this file
* Black Sabbath/13/03 Loner.flac

**Comment by trymeouteh** [comment]
> Is it possible to make the playlist-enties relative to the playlistfile?
> 
> Example
> 
> * /storage/0000-0000/Music/Black Sabbath/BlackSabbathBestOf.m3u would contain this file
> * 13/03 Loner.flac
> 
> Example
> 
> * /storage/0000-0000/Music/AllBestOf.m3u would contain this file
> * Black Sabbath/13/03 Loner.flac

That is an interesting concept and might the the way to go but I think it will have to look like this...

`/Black Sabbath/13/03 Loner.flac`

And the playlist file will be saved within your /storage/0000-0000/Music/ folder.

The problem for me is my Phone SD directory is _/storage/0000-0000/_ while my Tablet DS directory is _/storage/6430-6362/_. I do not know why this is but it causes some issues.

Also by using this method playlists can be transferred and synced to desktop computers and work with music players that support these relative m3u playlist files.

**Comment by trymeouteh** [comment]
I think the best way to do the relative paths is the following...

A Playlist folder will be created in the Music folder

` /storage/0000-0000/Music/Playlist/`

And inside will contain the m3u playlist files and the playlists will be structured like such...

```
../Black Sabbath/13/03 Loner.flac
```

**Comment by mirenbz** [comment]
Any chance to get some advance in this? Relative-path playlists are read/played just fine now, but it would be great if the app could automatically also update the source playlist file when adding new songs (with their corresponding relative paths).

Right now, 

- you need to export manually to actually have it stored in a file
- it uses absolute paths, so probably not going to work in different locations than the phone

Thanks!
