### ISSUE TITLE
Please add material design 2 icons in Vinyl Music Player

### ISSUE THREAD

**Issue by Gigla123** [AdrienPoupa/VinylMusicPlayer#143]
Please add material design icons 2 to the program and widgets.

**Comment by AdrienPoupa** [comment]
Hi, can you be more specific? Like listing which icon you'd like to replace by which

**Comment by Gigla123** [comment]
I would like to change all the icons, if possible, which are in the program (in the side menu and on the playback page and in widgets) for the icons that google currently uses in material design 2

**Comment by AdrienPoupa** [comment]
I understand. If you want me to have a closer look at it, list all the icons and their replacement please

**Comment by Gigla123** [comment]
List of icons in the side menu:
Library
Folders
Scan Media
Settings
About the program
List of icons on the playback screen:
Skip next
Skip previous
Play
Pause
Volume

**Comment by AdrienPoupa** [comment]
List of their replacement?

**Comment by Gigla123** [comment]
Yes, I would like to change them
