### ISSUE TITLE
Images flickering

### ISSUE THREAD

**Issue by paolovalerdi** [AdrienPoupa/VinylMusicPlayer#144]
**Describe the bug**
Images are flickering whenever some "data refreshing" operation is done. 

**To Reproduce**
1. Go to Settings > Images > Turn on Ignore Media Store Covers
2. There are many ways to reproduce this:
- Long press a song and then unselected 
- Go to a playlist and rearrange and item
- Leave the app in background and then come back also causes flickering

**Expected behavior**
Images should not flicker when Ignore Media Store is activated. (Just like it does with that option deactivated)

**Smartphone (please complete the following information):**
 - Device:  Essential Phone PH-1
 - Android Version: 9.0
 - ROM: Stock
 - Vinyl Music Player Version: 0.21.1

**Comment by paolovalerdi** [comment]
I suspect that as notifyDataSetChanged re-binds all the visible views in the recyclerview images are some sort of uncached  and that's why are loaded again, but I haven't dig into this.

About the flickering when the Activity is resumed I have no idea but the issue is slightly different as it doesn't not "re-bind" the views but just flicker (I mean you can tell images are not re-loaded because one can't see the placeholder again like other cases)

**Comment by AdrienPoupa** [comment]
Hi, I'll try to have a look. If you can come up with a fix I'd be delighted to merge it :)

**Comment by AdrienPoupa** [comment]
@paolovalerdi by the way I noticed that your player, Abbey does not have its sourcecode available? Since it is based on phonograph, that follows the GPL license, you have to provide it somewhere

**Comment by paolovalerdi** [comment]
@AdrienPoupa i'm working on this. I'm still refactoring things to kotlin and right now the codebase is a mess

**Comment by AdrienPoupa** [comment]
It doesn't really matter, as long as you release it you are required to provide the sourcecode as per the license conditions.

**Comment by paolovalerdi** [comment]
Btw Retro isn't the codebase at all all it's Phonograph

**Comment by AdrienPoupa** [comment]
Ok! Considering the visual similarities I thought it was :) but yeah, basically you're breaking the terms of the license for now

**Comment by paolovalerdi** [comment]
I've been playing around with DiffUtil and the flickering seems gone for most of the cases except the ones that triggers onMediaStoreChanged, this means that for example if you turn off Ignore Media store then the album list won't get refreshed until one of the following things happen:
- The adapter gets recreated (changing from grid to list)
- Scroll down and up so the views re-bind
I thinks it's not worth to make a PR until I get this to work someway

**Comment by AdrienPoupa** [comment]
Hey, have you made some progress here?

**Comment by paolovalerdi** [comment]
Not really, the items aren't updating.
For example if you rename a playlist or set a custom artist image the changes will be shown until the item it's rebind, so I might be using diff until wrong. I feel this has more to do with Glide itself and cache than the recycler view. 
Flickering only happens with non media store album covers and fetched artist images. Media store and custom artist images does not flicker

**Comment by AdrienPoupa** [comment]
Ok, maybe try to open an issue on their repo?

**Comment by paolovalerdi** [comment]
I'll try migrating to Glide 4.9 and search if there's some related issues in their repo.

BTW do ya have any idea on how can I test Auto implementation? I've trying to merge it into Abbey but I haven't been able to launch it at all.

**Comment by AdrienPoupa** [comment]
https://9to5google.com/2018/01/12/how-to-enable-android-auto-developer-settings-android-basics/ and you can enabled unauthorized apps

**Comment by paolovalerdi** [comment]
I've tried that but the app isn't listed
