### ISSUE TITLE
Suggestion: Add Headset control feature

### ISSUE THREAD

**Issue by ammarraisafti** [AdrienPoupa/VinylMusicPlayer#147]
# Component
Music player that looks good, free and open source. Music Player Vinyl has a material design that is easy on the eyes. Easy to use and customizable (some themes including dark ones). It supports folder browsing, sleep timer and tag editor. I have used it well, and I really enjoyed it. 

My proposal is based on how to control music through a headset.

<i>The following is the feature I want to propose:</i>
- Headset control 
- Single press
- Double press
- Triple press

![2gsjgna1uruv8X2R8t7XDv5HGXyHWCCu4rKmbB5pmEzjYShW4zR2DwKuB9pWXLFumoAtiEqy53eHfMPuduRSdv1hVFyjXKYEki3E5KGkoavMxuzSuL-picsay.png](https://cdn.steemitimages.com/DQmZV21XuW9VSUiiaftPjzCFVmwXYGFmpCXeYzgPKGUSMmN/2gsjgna1uruv8X2R8t7XDv5HGXyHWCCu4rKmbB5pmEzjYShW4zR2DwKuB9pWXLFumoAtiEqy53eHfMPuduRSdv1hVFyjXKYEki3E5KGkoavMxuzSuL-picsay.png)

# Proposal description
Add the Headset control feature in the application settings section, as well as access to activate it. And modifications to the Headset control feature to give users a choice of headset controls that can be adjusted. 

One click to pause / play. 
Double-click for the next song.
Triple it for the previous song.

![2gsjgna1uruv8X2R8t7XDv5HGXyHWCCu4rKmbB5pmEzjYShW4zR2DwKuB9pWXLFumoAtiEqy53eHfMPuduRSdv1hVFyjXKYEki3E5KGkoavMxuzSuL-picsay.png](https://cdn.steemitimages.com/DQmZV21XuW9VSUiiaftPjzCFVmwXYGFmpCXeYzgPKGUSMmN/2gsjgna1uruv8X2R8t7XDv5HGXyHWCCu4rKmbB5pmEzjYShW4zR2DwKuB9pWXLFumoAtiEqy53eHfMPuduRSdv1hVFyjXKYEki3E5KGkoavMxuzSuL-picsay.png)

# Mockups / Examples
The following is an example of an illustration image of the Headset control feature.
![Screenshot_2019-04-22-00-41-10-picsay.jpg](https://cdn.steemitimages.com/DQmZaVNSPHaH6C6762TdHK7oVrSLSfhbb2y6EDYWW6xEfaQ/Screenshot_2019-04-22-00-41-10-picsay.jpg)

The following is an example of an illustration image of the Single press  feature.
![Screenshot_2019-04-22-00-41-10-picsay.jpg](https://cdn.steemitimages.com/DQmZPbmz73BoqBUHQYivnKQ4DKG9Hg3STkPLs9HLiHDFAhd/Screenshot_2019-04-22-00-41-10-picsay.jpg)

The following is an example of an illustration image of the Double press  feature.
![Screenshot_2019-04-22-00-41-10-picsay.jpg](https://cdn.steemitimages.com/DQmZBTvVCR2g5NPbPF8yJAk5FSwL6eAE2iYxdzZZXtNj2fY/Screenshot_2019-04-22-00-41-10-picsay.jpg)

The following is an example of an illustration image of the Triple press  feature.
![Screenshot_2019-04-22-00-41-10-picsay.jpg](https://cdn.steemitimages.com/DQmNgHDcQHoqHtdg1nCokGc5XPUn5XGE34MhHWBcvgimgJD/Screenshot_2019-04-22-00-41-10-picsay.jpg)

![2gsjgna1uruv8X2R8t7XDv5HGXyHWCCu4rKmbB5pmEzjYShW4zR2DwKuB9pWXLFumoAtiEqy53eHfMPuduRSdv1hVFyjXKYEki3E5KGkoavMxuzSuL-picsay.png](https://cdn.steemitimages.com/DQmZV21XuW9VSUiiaftPjzCFVmwXYGFmpCXeYzgPKGUSMmN/2gsjgna1uruv8X2R8t7XDv5HGXyHWCCu4rKmbB5pmEzjYShW4zR2DwKuB9pWXLFumoAtiEqy53eHfMPuduRSdv1hVFyjXKYEki3E5KGkoavMxuzSuL-picsay.png)

# Benefit
With the Headset control feature, users can control music through the headset, by doing one click to pause / play. Double-click to play the next music, and triple it for the previous song. This feature is very useful for application users, and is very suitable for everyday use. Users will feel very happy and more interesting using this application. And that is a big advantage.

I hope, my advice can be an additional idea for developers to make this application more interesting to use.

Thanks.

**Comment by Cantuariensis** [comment]
Hi @ammarraisafti,
Love that, I miss this feature so bad from the Windows Phone/Mobile player!
The implementation you proposed looks clean and functional.
Thanks

**Comment by soncaokim** [comment]
It's already possible to single/doule/tripple press the play/pause headset button to control playback. 

And I dont think is necessary to have a setting to tweak that, the default behaviour is common for many players.
