### ISSUE TITLE
Problem with artist images (Last.FM API change)

### ISSUE THREAD

**Issue by cesfhiil** [AdrienPoupa/VinylMusicPlayer#149]
**Describe the bug**
Artist images (not album images) are not generating right, and instead displays a white star image. Can reset the image, but goes back to the white star image. Also happens on other music apps that generate artist images.

**To Reproduce**
Steps to reproduce the behaviour:
1. Artist images try to auto-generate, but displays white star.
2. Go reset artist image on selected artist.
3. Artist image resets for a while then goes back to displaying white star.

**Expected behaviour**
Displays the generated artist images auto-downloaded from the internet.

**Screenshots**
![Screenshot_20190503-191835_Vinyl Music Player](https://user-images.githubusercontent.com/50235760/57135389-cad91300-6ddb-11e9-9df5-81ec72f3327d.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7
 - Android Version: OneUI on Android Pie
 - ROM: LightROM and BlackDiamondROM (Custom ROMs)
 - Vinyl Music Player Version: 0.21.1

**Additional context**
Did not have this problem on LineageOS 15.1 (just installed the custom rom today). Tried resetting Media Storage, still nothing. Tried disabling the stock music app (Samsung Music) but still doesn't work. Sorry if I got something wrong as I made this account today to start finding bugs (I got spare time, why not).

**Comment by GeoZac** [comment]
@cesfhiil This seems to be an issue at LastFM's end.

**Comment by cellularlupus** [comment]
[Here's](https://getsatisfaction.com/lastfm/topics/api-announcement-dac8oefw5vrxq?topic-reply-list%5Bsettings%5D%5Bfilter_by%5D=all) the announcement from the Last.fm staff about this. There's now no way to download images from Last.fm using the API. It seems they have no intention of changing it.

**Comment by cesfhiil** [comment]
I wonder if we could use [Discogs' API](https://www.discogs.com/developers/) instead?

**Comment by paolovalerdi** [comment]
Let's hope #156 gets merged
