### ISSUE TITLE
Problem with song cover

### ISSUE THREAD

**Issue by Ramton03** [AdrienPoupa/VinylMusicPlayer#150]
**Describe the bug**
After scrolling 2 times the song's cover vanishes

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Primary color'
3. Select 'First four of every color scheme'

**Screenshots**
https://i.imgur.com/Hm6S75d.jpg

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi 5
 - Android Version: 8.1
 - ROM: Xiaomi eu
 - Vinyl Music Player Version:latest version

**Comment by soncaokim** [comment]
I have trouble understanding and following the steps to reproduce the error:
- I dont have the option "First four of every color scheme". You have litterally this option on your phone, is that correct?
- What do you mean by scrolling 2 times? On what screen did you scroll?

**Comment by Ramton03** [comment]
I meant those as well as other 16 primary color schemes
22 May 2019, 02:00 by notifications@github.com:

**Comment by soncaokim** [comment]
I cant reproduce the error
