### ISSUE TITLE
[Feature Request] Playing multiple genres/artists/albums at once

### ISSUE THREAD

**Issue by papjul** [AdrienPoupa/VinylMusicPlayer#157]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
For example, let's say that I want to listen to both "Classical" and "Soundtrack" genres.
I didn't find a way to do this.

An implementation that I can think is the following:
- Go to "Genres" tab
- Long press on "Classical" => Checkboxes appear on the left side of each genre. "Classical" checkbox is automatically ticked since it was pressed. Icons in the topbar change, you now have a "Play button"
- You can select multiple genres, and then hit the "Play" button on the top bar when you're done choosing your genres.

My use case was for genres, but this can be applied to titles, artists and albums as a generic feature.

**Describe alternatives you've considered**
We could play one genre, then add another genre to the queue, but I didn't find a way to do this. There is only a "Shuffle" button on top bar when you go to the genre page, that will overwrite your queue.

**Adding a "Add to queue" button next to the "Shuffle" button on each genre page** could be a quicker alternative to implement, albeit not user-friendly if I want to add many many genres, artists, or albums.

**Additional context**
It would be great paired with #70 (a different but complementary issue).

**Comment by Cantuariensis** [comment]
Good idea, never realized it was not possible. I see 2 things to implement that:

- Being able to select genres the exact same way we can select several songs, albums, artists, and playlists (same code)
- Add a "Play now" button in that selection toolbar (or under the ... dropdown menu) when you select several songs, albums, artists, genres, and playlists. This button would clear the playing queue before adding the selected item.
