### ISSUE TITLE
Gapless Playback causes Playback bug

### ISSUE THREAD

**Issue by captaincocopie** [AdrienPoupa/VinylMusicPlayer#158]
Playback ends at the end of the song. Have to repeatedly press play for each song to resume playback.

-

Device info:
---
<table>
<tr><td>App version</td><td>0.22.0</td></tr>
<tr><td>App version code</td><td>166</td></tr>
<tr><td>Android build version</td><td>V10.0.8.0.PDHMIXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180917.001.V10.0.8.0.PDHMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>tissot_sprout</td></tr>
<tr><td>Device model</td><td>Mi A1</td></tr>
<tr><td>Device product name</td><td>tissot</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by AdrienPoupa** [comment]
Try to clear your cache

**Comment by AdrienPoupa** [comment]
@soncaokim can you check if your changes did that? I could reproduce it until I cleared my cache

**Comment by captaincocopie** [comment]
Clearing cache works. Thanks for taking this matter to attention.

**Comment by AdrienPoupa** [comment]
Thanks for the report. Others reported the issue so I'd think clearing the databases on upgrade will be required. I'll be experimenting to see if that works soon

**Comment by JahnoR** [comment]
I've cleared the cache on my phone but still won't play but one song at a time. Didn't have a problem until update happened. Is there another cache I need to clear?

**Comment by soncaokim** [comment]
> @soncaokim can you check if your changes did that? I could reproduce it until I cleared my cache

weird, I've not experience any like that. I mainly play music from a smart playlist (i.e not recent played).

@AdrienPoupa @JahnoR @captaincocopie How do you trigger the bug?

**Comment by captaincocopie** [comment]
I got the bug after the recent update. Clearing the app cache, then force stopping the app solves the problem for me, though. @JahnoR

**Comment by soncaokim** [comment]
I've just tried to build a play queue with some manually selected songs and a smart playlist. Songs are chained correctly one after another.

If anyone can give more details on how precisely this can be reproduced, it can be helpful.

How the app is procured, via Playstore or FDroid or via manual compilation?

**Comment by AdrienPoupa** [comment]
@soncaokim install 0.21.1, play some songs, upgrade to 0.22.0

**Comment by AdrienPoupa** [comment]
Interestingly I can reproduce it with a fresh install of this APK https://apkpure.com/vinyl-music-player/com.poupa.vinylmusicplayer/download/166-APK?from=versions%2Fversion but not a debug version I compile

**Comment by soncaokim** [comment]
Just my opinion on the automatic clear DB fix: this should be the last recourse since it would imply losing play history.

I guess that you ve not managed to reproduce on a simulator?

**Comment by AdrienPoupa** [comment]
I'm trying on my phone. It's insane: the APK from APKPure and the version of the Google Play Store have the bug, but a signed APK of the same codebase doesn't have it.

Also for the APKPure APK and Google Play I noticed that the black theme is on by default instead of the light one and there are music in the playlist whereas there shouldn't be. I'm starting to think that it may be a bug on Google's side when I uploaded a AAB.

**Comment by arkon** [comment]
> the APK from APKPure and the version of the Google Play Store have the bug

It's probably pulling your saved preferences from Google.

**Comment by AdrienPoupa** [comment]
@arkon thanks for the insight. It always displays the same song on the folder fragment.

If I clear the storage, then it goes back to normal and it works. I'm lost here

**Comment by arkon** [comment]
Clear it from Google Drive: https://www.androidrecovery.com/blog/delete-app-backup-from-google-drive.html

**Comment by AdrienPoupa** [comment]
@arkon I just checked, no trace of Vinyl or any other application there

**Comment by arkon** [comment]
@AdrienPoupa Whoops, you're right. Try going to Drive on your phone, then nav drawer > Backups > your device > Apps

**Comment by AdrienPoupa** [comment]
@arkon You are right, I see it. I disabled automatic restore and the 'bug' is gone. Same thing if I push the prod APK to a virtual device

**Comment by arkon** [comment]
Nice. That's basically all the insight I have (esp since I haven't been keeping up on changes to the codebase), but [here's the documentation on what's backed up](https://developer.android.com/guide/topics/data/autobackup.html#Files).

**Comment by soncaokim** [comment]
Hmm, does that mean that we re back to square zero? User upgrades to .22, Google restores old DB, and it messes up?

I m still lost on why the new binary bugs on old DB, since there were no apparent storage format change.

**Comment by AdrienPoupa** [comment]
Thanks a lot! Unfortunately what I had backed up is gone now that I disabled it and I can't reproduce it anymore haha

**Comment by AdrienPoupa** [comment]
@soncaokim no, if the DB was there it doesn't touch anything. But in my case, when I uninstalled the application and reinstalled it it was restoring all data, and this old data on the newest version is what triggers the bug. Unfortunately I can't find a way to trigger this manually coming from 0.21.1 to 0.22.0

**Comment by soncaokim** [comment]
It seems that the backup can be somewhat old - on my device it shows a copy made several days ago for actively used apps. 6 days for Vinyl for instance. 

Speculation:

If the restored history DB is too old, I guess that we are good (onUpgrade code path which just burst the old DB and recreate anew).

If the restored pref/state DB is too old, not sure we have safety mechanism for that yet.

**Comment by AdrienPoupa** [comment]
Yes my backup is from a month ago. Anyway I managed to get it using Titanium Backup and when I restore it against the 0.22 of the Play Store I can reproduce it. I want to try to see if simply increasing the DB version for the queue is enough or not

**Comment by AdrienPoupa** [comment]
I tried to upgrade the databases but that's not enough, the bug is still there

**Comment by AdrienPoupa** [comment]
I was able to reproduce the problem with the following preference file only, no need to tinker the DB I keep investigating
```
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <string name="replaygain_srource_mode">none</string>
    <int name="SHUFFLE_MODE" value="1" />
    <string name="song_sort_order">title_key</string>
    <boolean name="classic_notification" value="true" />
    <int name="album_grid_size" value="1" />
    <string name="last_added_interval">this_month</string>
    <int name="REPEAT_MODE" value="0" />
    <int name="now_playing_screen_id" value="0" />
    <int name="POSITION" value="3" />
    <long name="next_sleep_timer_elapsed_real_time" value="10003230" />
    <boolean name="should_color_app_shortcuts" value="true" />
    <int name="last_start_page" value="0" />
    <string name="general_theme">black</string>
    <boolean name="ignore_media_store_artwork" value="true" />
    <boolean name="remember_shuffle" value="true" />
    <boolean name="remember_last_tab" value="true" />
    <boolean name="blurred_album_art" value="false" />
    <boolean name="should_make_widget_background_transparent" value="false" />
    <boolean name="album_art_on_lockscreen" value="true" />
    <string name="recently_played_interval">this_month</string>
    <int name="POSITION_IN_TRACK" value="0" />
    <boolean name="make_widget_background_transparent" value="false" />
    <boolean name="synchronized_lyrics_show" value="true" />
    <boolean name="audio_ducking" value="true" />
    <string name="library_categories">[{&quot;category&quot;:&quot;SONGS&quot;,&quot;visible&quot;:true},{&quot;category&quot;:&quot;ALBUMS&quot;,&quot;visible&quot;:true},{&quot;category&quot;:&quot;ARTISTS&quot;,&quot;visible&quot;:true},{&quot;category&quot;:&quot;GENRES&quot;,&quot;visible&quot;:true},{&quot;category&quot;:&quot;PLAYLISTS&quot;,&quot;visible&quot;:true}]</string>
    <boolean name="colored_notification" value="false" />
    <string name="auto_download_images_policy">only_wifi</string>
    <boolean name="intro_shown" value="true" />
    <string name="album_sort_order">album_key</string>
    <int name="last_music_chooser" value="0" />
    <boolean name="gapless_playback" value="true" />
    <int name="last_sleep_timer_value" value="1" />
    <boolean name="variations_seed_native_stored" value="true" />
    <boolean name="initialized_blacklist" value="true" />
    <int name="last_changelog_version" value="166" />
</map>

```

**Comment by AdrienPoupa** [comment]
That took some time, but I found how to reproduce the issue consistently: it is linked to the Gapless playback feature

When enabled in 0.21.1, it works but for some reason 0.22.0 broke it.

**Comment by AdrienPoupa** [comment]
Turns out, that was my fault! Sorry folks :)

**Comment by JahnoR** [comment]
Ok gang. I'm just an old guy that wants to play music on my phone. The music is on my mini sd card. Google Play wouldn't recognize it was there. I went to the phone store and the guy put this on my phone. Worked great. You updated app and now the bug.

**Comment by JahnoR** [comment]
Are you gonna update again with a fix? I don't "code".

**Comment by gkeegan** [comment]
@JahnoR Update your app to version 0.21.1.

**Comment by AdrienPoupa** [comment]
0.22.1 actually. You can get it from Google Play

**Comment by gkeegan** [comment]
@AdrienPoupa Oops. I misread the version in the releases tab.

**Comment by nermolov** [comment]
@AdrienPoupa when will the new version be released on f-droid?

**Comment by AdrienPoupa** [comment]
I tagged the release properly but their process takes a really long time, so I have no idea
