### ISSUE TITLE
[Feature Request] Ability to remember volume setting

### ISSUE THREAD

**Issue by abhishekkumar2718** [AdrienPoupa/VinylMusicPlayer#16]
Hello!

If you are anything like me, your music playlist contains very many different types of songs. Each of which have a different volume with them. I find myself changing volume everytime a song changes.

Can you please implement a feature in which we can manually assign a default volume to a song ? So everytime the song plays, volume would be same.

Thanks.

**Comment by AdrienPoupa** [comment]
I'd say this is a duplicate of #31
