### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by Cricotu30** [AdrienPoupa/VinylMusicPlayer#160]
When we quickly press several tracks in a row it's crash Vinyl Music Player

-

Device info:
---
<table>
<tr><td>App version</td><td>0.22.1</td></tr>
<tr><td>App version code</td><td>167</td></tr>
<tr><td>Android build version</td><td>211C432R1</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>BKL-L09 9.0.0.211(C432E4R1P12)</td></tr>
<tr><td>Device brand</td><td>HONOR</td></tr>
<tr><td>Device manufacturer</td><td>HUAWEI</td></tr>
<tr><td>Device name</td><td>HWBKL</td></tr>
<tr><td>Device model</td><td>BKL-L09</td></tr>
<tr><td>Device product name</td><td>BKL-L09</td></tr>
<tr><td>Device hardware name</td><td>kirin970</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by AdrienPoupa** [comment]
Can't reproduce, sorry. And it's not possible to work on it without logs so feel free to reopen if you have some
