### ISSUE TITLE
Gapless playback breaks ReplayGain

### ISSUE THREAD

**Issue by jamerst** [AdrienPoupa/VinylMusicPlayer#164]
When ReplayGain is enabled at the same time as gapless playback, the correct gain is not applied for the next song when the end of the current song is reached. The gain is not updated until pause is toggled. Moving between songs using forward/back works normally.

**To Reproduce**
1. Enable gapless playback and ReplayGain (either Track or Album mode)
2. Play a song, wait or seek to the end
3. Correct gain is not applied to the next song - there doesn't seem to be any gain applied, but I can't verify that.

**Expected behavior**
Correct gain should be applied.

**Smartphone (please complete the following information):**
 - Device: HTC 10
 - Android Version: 7.1.2
 - ROM: LineageOS 14.1
 - Vinyl Music Player Version: 0.22.1

**Comment by AdrienPoupa** [comment]
@knacky34 any chance you could look into this?

**Comment by knacky34** [comment]
Yep I will check that !

**Comment by SibaNL** [comment]
This issue is still present in version 0.24.0
