### ISSUE TITLE
Transparent widget

### ISSUE THREAD

**Issue by azlux** [AdrienPoupa/VinylMusicPlayer#17]
Hi.

I have a small improvement to propose.
Can we have an option the make the widget background transparent ?

Having a white block can be ugly in the home.

Thank
Az

**Comment by Rygle** [comment]
I would love this! And being able to change the colour and level of transparency.

**Comment by HardCode4All** [comment]
+1 for transparent widget. Selectable color would be mega.

**Comment by AdrienPoupa** [comment]
Sure, I'll see what I can do.

Thanks for the report, I migrated recently and something must have broke.

**Comment by HardCode4All** [comment]
I just used the 4x2 widget instead of the 4x1 and it looks much better:

![screenshot_2018-05-05-07-35-19](https://user-images.githubusercontent.com/38424724/39660882-30f91eee-5048-11e8-9f48-de98c8b7996d.png)

If the 4x1 would look like this color-wise, all would be great.

**Comment by HardCode4All** [comment]
Wow thanks! That was quick. Can't wait to see it in action :)
