### ISSUE TITLE
[Vinyl][v0.22.1]The application crashes if I click on Transparent widget Background

### ISSUE THREAD

**Issue by 44asad** [AdrienPoupa/VinylMusicPlayer#174]
### Actual behavior:
After opening the application, click on setting and then when I click the transparent widget background  the application is crashed.

### Expected Behaviour
I expect that the app should work normally and not to see a crash on the action.

### How to reproduce:
* Download the app and open it.
* Naw click on menu icon
* Then click setting option & 
* Click no transparent widget background.
* see bug
#### Information
* App version:v0.22.1
* OS:Android 6.0.1
* Device:Samsung J5
### Recording Of The Bug:
https://youtu.be/xhCc0GS_o5w

### Logcat:
<pre><code>05-23 08:48:01.642   935   935 E AndroidRuntime: FATAL EXCEPTION: main
05-23 08:48:01.642   935   935 E AndroidRuntime: Process: com.poupa.vinylmusicplayer, PID: 935
05-23 08:48:01.642   935   935 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/content/pm/ShortcutManager;
05-23 08:48:01.642   935   935 E AndroidRuntime:   at com.poupa.vinylmusicplayer.appshortcuts.DynamicShortcutManager.<init>()
05-23 08:48:01.642   935   935 E AndroidRuntime:   at com.poupa.vinylmusicplayer.ui.activities.SettingsActivity$SettingsFragment.e()
05-23 08:48:01.642   935   935 E AndroidRuntime:   at b.b.a.i.a.s.onPreferenceChange(lambda)
05-23 08:48:01.642   935   935 E AndroidRuntime:   at androidx.preference.Preference.callChangeListener()
05-23 08:48:01.642   935   935 E AndroidRuntime:   at androidx.preference.TwoStatePreference.onClick()
05-23 08:48:01.642   935   935 E AndroidRuntime:   at androidx.preference.Preference.performClick()
05-23 08:48:01.642   935   935 E AndroidRuntime:   at androidx.preference.CheckBoxPreference.performClick(:1)
05-23 08:48:01.642   935   935 E AndroidRuntime:   at androidx.preference.Preference$1.onClick()
05-23 08:48:01.642   935   935 E AndroidRuntime:   at android.view.View.performClick(View.java:5698)
05-23 08:48:01.642   935   935 E AndroidRuntime:   at android.view.View$PerformClick.run(View.java:22565)
05-23 08:48:01.642   935   935 E AndroidRuntime:   at android.os.Handler.handleCallback(Handler.java:739)
05-23 08:48:01.642   935   935 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:95)
05-23 08:48:01.642   935   935 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:158)
05-23 08:48:01.642   935   935 E AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:7231)
05-23 08:48:01.642   935   935 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
05-23 08:48:01.642   935   935 E AndroidRuntime:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
05-23 08:48:01.642   935   935 E AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
05-23 08:48:01.642   935   935 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.content.pm.ShortcutManager" on path: DexPathList[[zip file "/data/app/com.poupa.vinylmusicplayer-1/base.apk"],nativeLibraryDirectories=[/data/app/com.poupa.vinylmusicplayer-1/lib/arm, /vendor/lib, /system/lib]]
05-23 08:48:01.642   935   935 E AndroidRuntime:   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-23 08:48:01.642   935   935 E AndroidRuntime:   at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-23 08:48:01.642   935   935 E AndroidRuntime:   at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
05-23 08:48:01.642   935   935 E AndroidRuntime:   ... 17 more
05-23 08:48:01.642   935   935 E AndroidRuntime:   Suppressed: java.lang.ClassNotFoundException: android.content.pm.ShortcutManager
05-23 08:48:01.642   935   935 E AndroidRuntime:     at java.lang.Class.classForName(Native Method)
05-23 08:48:01.642   935   935 E AndroidRuntime:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
05-23 08:48:01.642   935   935 E AndroidRuntime:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
05-23 08:48:01.642   935   935 E AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
05-23 08:48:01.642   935   935 E AndroidRuntime:     ... 18 more</code></pre>

**Comment by 44asad** [comment]
@AdrienPoupa
please review?

**Comment by 44asad** [comment]
@AdrienPoupa

**Comment by gkeegan** [comment]
Could not replicate on Android Pie. Some things were changed in Nougat regarding widgets and icons, so I am not surprised by this bug.

**Comment by 44asad** [comment]
bug fixed

**Comment by gkeegan** [comment]
Could you please close this issue?

**Comment by AdrienPoupa** [comment]
Fixed how?

**Comment by 44asad** [comment]
@AdrienPoupa
review please

**Comment by AdrienPoupa** [comment]
Review what? You say bug fixed and then ask for a review?

**Comment by 44asad** [comment]
yes
