### ISSUE TITLE
"Play next" does the same as "Add to queue"

### ISSUE THREAD

**Issue by hurzl** [AdrienPoupa/VinylMusicPlayer#175]
I would expect the queue to be cleared?

**Comment by gkeegan** [comment]
They don't do the same thing for me. Add to queue adds the song to the end of the queue, while play next puts the song up next. This is expected behavior of any music player.

**Comment by hurzl** [comment]
Ok but the current track is kept and I would expect to start playing what I want to play now

**Comment by gkeegan** [comment]
"Play next" means it will be played next, not now...

**Comment by hurzl** [comment]
So this was a feature request for "play now" ...

**Comment by gkeegan** [comment]
If you just tap the song it will play immediately.

**Comment by hurzl** [comment]
It will clear the playlist and play the whole directory then, it's a bit confusing.
