### ISSUE TITLE
App crashes while deleting songs

### ISSUE THREAD

**Issue by Ramton03** [AdrienPoupa/VinylMusicPlayer#177]
**Describe the bug**
I played a song and the tried to delete 3 songs including the playing one.Then the app crashed

**To Reproduce**
1. Play a song
2. Try to delete multiple songs including the playing one 
3. See error

**Expected behavior**

**Screenshots**
![IMG_20190526_175721](https://user-images.githubusercontent.com/49825977/58381519-775a7f00-7fad-11e9-8c37-34c652726fb7.jpg)

**Smartphone (please complete the following information):**
 - Device: Redmi 5
 - Android Version: Oreo
 - ROM: Miui eu
 - Vinyl Music Player Version: latest

**Additional context**
For crashing you need to play the first of the 3 songs you want to delete.

**Comment by Ramton03** [comment]
https://upload.disroot.org/r/znNmbJMg#HkhSQXg29Z2WgiIWZCJK8Tpz0m/d8NUuYM+CzhNLnSY=

Its the log file.

**Comment by soncaokim** [comment]
@Ramton03 The link you provided doesnt work. Is it possible to reupload the log please?

**Comment by Ramton03** [comment]
6 Jun 2019, 02:37 by notifications@github.com:
