### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by railanbarbosa** [AdrienPoupa/VinylMusicPlayer#179]
Ele não está reconhecendo a metadata em músicas libopus.opus, talvez por isso não esteja baixando as fotos de capa

https://i.imgur.com/K9RDLr8.png
https://i.imgur.com/6jw8op4.png
https://i.imgur.com/Vdbog1Q.png

Já outros players coletam as informações sem problemas

https://i.imgur.com/I405b8U.png

-

Device info:
---
<table>
<tr><td>App version</td><td>0.22.1</td></tr>
<tr><td>App version code</td><td>167</td></tr>
<tr><td>Android build version</td><td>eng.joaoar.20190223.214952</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PQ2A.190205.003</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>montana</td></tr>
<tr><td>Device model</td><td>XT1792</td></tr>
<tr><td>Device product name</td><td>Moto G5s</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by braniii** [comment]
I guess it is related to  #135. Changing Tags/Artwork works only with .mp3
