### ISSUE TITLE
Long-pressing on title starts playback

### ISSUE THREAD

**Issue by ix5** [AdrienPoupa/VinylMusicPlayer#180]
**Describe the bug**
When pressing **directly onto** a song title in a list view, a tap is triggered instead of the long-press action, i.e. the song starts playing instead of the context menu showing.

**To Reproduce**
1. Go into a listing of songs, e.g. open an album
2. Long-press **directly onto** a song title

**Expected behavior**
Context menu should pop up.

**Screenshots**
See video here: [vinyl-screenrecord-bug-listview.mp4](https://sx.ix5.org/files/misc/vinyl-screenrecord-bug-listview.mp4)

**Smartphone (please complete the following information):**
 - Device: Sony Xperia XZ2 Compact
 - Android Version: 9
 - ROM: Stock firmware, June security patch
 - Vinyl Music Player Version: 0.22.1

**Additional context**
I strongly suspect https://github.com/AdrienPoupa/VinylMusicPlayer/pull/172 since neither previous versions nor the upstream Phonograph player seems to have the issue.

**Comment by defvs** [comment]
Reproducable on 0.22.1 on my 9.0 UMIDIGI One Max.

**Comment by defvs** [comment]
Also, #172 is not in 0.22.1 I think. It's not it then.

**Comment by Cantuariensis** [comment]
Thanks for pointing, quite annoying indeed.
Still there on 0.23.1 on Fairphone 3 / Android 9.
