### ISSUE TITLE
First entry shows no title

### ISSUE THREAD

**Issue by HardCode4All** [AdrienPoupa/VinylMusicPlayer#182]
**Describe the bug**
The first entry in folder view is not showing a title:
![01-folder-first-entry-empty](https://user-images.githubusercontent.com/38424724/60165527-c0e1f800-97ff-11e9-8c25-1488ee63a104.jpg) ![01-file-first-entry-empty](https://user-images.githubusercontent.com/38424724/60165526-c0496180-97ff-11e9-9883-5ac6f5e57906.jpg)

As soon as you scroll down and then up again, the title shows correctly:
![02-folder-after-scrolling](https://user-images.githubusercontent.com/38424724/60165589-d5be8b80-97ff-11e9-97f5-80819e685650.jpg) ![02-file-after-scrolling](https://user-images.githubusercontent.com/38424724/60165600-db1bd600-97ff-11e9-80fc-4106517b2fb7.jpg)

This is true for files and folders.

**Smartphone:**
 - Device: Samsung S5 Mini, SM-G800F
 - Android Version: 6.0.1
 - ROM: Where do I get this info?
 - Vinyl Music Player Version: 0.22.1

**Comment by gkeegan** [comment]
Could not replicate on version 22.1 on Android 9. 

(If you don't know where to find out what ROM you are on, then you are most likely on the stock one from Samsung.)

**Comment by AdrienPoupa** [comment]
Same here, can't reproduce. Maybe this is coming from Android6?

**Comment by HardCode4All** [comment]
Hm... I don't know but I just tried "[Music-Player](https://github.com/MaxFour/Music-Player)", another fork of Phonograph, at that does not have the same problem. So it's somewhere in Vinyl, I guess. If you can't pin it down, nevermind. I can stick with Music-Player, although I don't like its folder-icons too much...
