### ISSUE TITLE
A lot of empty playlists showing in my list

### ISSUE THREAD

**Issue by wyjek** [AdrienPoupa/VinylMusicPlayer#184]
**Describe the bug**

When I check the "Playlists" tab, there are a lot of empty playlists with weird names, like "00_0", "01_0", "bang_0", "face_0", and so on, 358 playlists in total. I tried to delete them, but they just come back.

**To Reproduce**
1. Go to 'Playlists' tab
2. That's where these weird playlists are

**Expected behavior**

I expected empty playlists tab.

**Screenshots**

![Screenshot_20190705-075849](https://user-images.githubusercontent.com/29181361/60701535-641bc700-9efc-11e9-8499-ecfd70a36eee.png)
![Screenshot_20190705-075915](https://user-images.githubusercontent.com/29181361/60701550-6bdb6b80-9efc-11e9-8376-bd6a539a8546.png)

**Smartphone (please complete the following information):**
 - Device: Lenovo Moto X Play
 - Android Version: 7.1.2
 - ROM: LineageOS 14.1
 - Vinyl Music Player Version: 0.22.1

**Additional context**

**Comment by AdrienPoupa** [comment]
They must be stored somewhere on your devices, the Android MediaStore picks them up, and so does Vinyl
