### ISSUE TITLE
Incompatible SDK API use which may cause crash to your APP

### ISSUE THREAD

**Issue by jay2013** [AdrienPoupa/VinylMusicPlayer#19]
Hi vinylmusicplayer Developers,
I develop a tool to detect incompatible SDK API use in android application. Today I use my tool to check vinylmusicplayer downloaded from F-Droid. My tool report many bugs. Although I believe most of them are real bugs, I cannot be 100% sure because I am not very familiar with Android developing. So
please help to check it, it must be very helpful to your APP.

The attachment below is the bug report that my tool give. please help to double check!
I also really hope to get your feedback.
thank you!

**[Supplementary explanation]**
There are totally two type of bug in the report. The first one is like this: "API called in method not in [list]", the list here are sdk levels, it means your app run under these SDK version can not call API because no such API in these sdk levels.
Type two is like "API called in method no living level", it means your application can never reach this API
use, so if these API uses are not in external library, you can remove it from your own code.

APIs or methods in our report are given in signature format like "<declaringType: returnType methodName(paramTypeList)>".

And finally, the reachable path is actually one possible call stack. it is always start from dummyMainMethod which is created by our tool. So you should read it from bottom to top.

Yes, many of these bugs seem to be in third-library codes. But it do cause problems in your app. Some third-library API say that they can only be run at specific SDK Level by using "@targetapi(Build.VERSION_CODES.N)", however, Application codes tend to ignore this warning.

Donejie He
hedongjie@ict.ac.cn

[com.poupa.vinylmusicplayer_150.apk.report.txt](https://github.com/AdrienPoupa/VinylMusicPlayer/files/1834308/com.poupa.vinylmusicplayer_150.apk.report.txt)

**Comment by ildar** [comment]
Emm. Verdict?

**Comment by AdrienPoupa** [comment]
I tried to read the logs, didn't see anything sketchy. Moreover, the OP just copy/pastes logs from his tool on dozens of repositories and I'm not willing to debug it.

**Comment by jay2013** [comment]
Hi, 
If you are interested in our report, We are willing to co-operate together to debug these potential bugs.
One of our report says, in Activity "com.poupa.vinylmusicplayer.appshortcuts.AppShortcutLauncherActivity"'s "onCreate(Bundle)" method line 61, it call "<com.poupa.vinylmusicplayer.appshortcuts.DynamicShortcutManager: void reportShortcutUsed(android.content.Context,java.lang.String)>" , and in this method, it call API "<android.content.Context: java.lang.Object getSystemService(java.lang.Class)>" which is not in SDK [16, 17, 18, 19, 21, 22]. Our tool suppose every component can be reached directly, so we report this bug. Can you help us to check whether it is true?
Another similar bug is also list here:
`BUG: <android.content.pm.ShortcutManager: void reportShortcutUsed(java.lang.String)> called in <com.poupa.vinylmusicplayer.appshortcuts.DynamicShortcutManager: void reportShortcutUsed(android.content.Context,java.lang.String)> on line 61 not in [16, 17, 18, 19, 21, 22, 23, 24]`
**reachable path:**
`<com.poupa.vinylmusicplayer.appshortcuts.AppShortcutLauncherActivity: void onCreate(android.os.Bundle)>
		--><com.poupa.vinylmusicplayer.appshortcuts.DynamicShortcutManager: void reportShortcutUsed(android.content.Context,java.lang.String)>
                --><android.content.pm.ShortcutManager: void reportShortcutUsed(java.lang.String)>
`
Another bug is not directly in your code, it's in external library but may lead your app crash too.
it says:
`
BUG: <java.nio.charset.StandardCharsets: java.nio.charset.Charset ISO_8859_1> called in <org.jaudiotagger.audio.flac.metadatablock.MetadataBlockDataPicture: void initFromByteBuffer(java.nio.ByteBuffer)> on line 70 not in SDK [16, 17, 18]`
**Reachable path:**
`<com.poupa.vinylmusicplayer.ui.activities.tageditor.AlbumTagEditorActivity: void onCreate(android.os.Bundle)>
		--><com.poupa.vinylmusicplayer.ui.activities.tageditor.AbsTagEditorActivity: void onCreate(android.os.Bundle)>
		--><com.poupa.vinylmusicplayer.ui.activities.tageditor.AbsTagEditorActivity: void setUpViews()>
		--><com.poupa.vinylmusicplayer.ui.activities.tageditor.AbsTagEditorActivity: void setUpImageView()>
		--><com.poupa.vinylmusicplayer.ui.activities.tageditor.AlbumTagEditorActivity: void loadCurrentImage()>
		--><com.poupa.vinylmusicplayer.ui.activities.tageditor.AbsTagEditorActivity: android.graphics.Bitmap getAlbumArt()>
		--><org.jaudiotagger.audio.generic.AbstractTag: org.jaudiotagger.tag.images.Artwork getFirstArtwork()>
		--><org.jaudiotagger.tag.vorbiscomment.VorbisCommentTag: java.util.List getArtworkList()>
		--><org.jaudiotagger.audio.flac.metadatablock.MetadataBlockDataPicture: void <init>(java.nio.ByteBuffer)>
		--><org.jaudiotagger.audio.flac.metadatablock.MetadataBlockDataPicture: void initFromByteBuffer(java.nio.ByteBuffer)>
               --><java.nio.charset.StandardCharsets: java.nio.charset.Charset ISO_8859_1>`

Any questions, welcome to talk here.

best wishes,

Dongjie He
