### ISSUE TITLE
Make Play/Pause/Next/Previous buttons scalable

### ISSUE THREAD

**Issue by hvdwolf** [AdrienPoupa/VinylMusicPlayer#190]
I'm using VinylMusicPlayer both on my phone as well as on my Android car head unit.
The buttons are fine on a phone, but they are too small on my head unit.
For correct and save(!) use of play/pause and next (mostly), it would be convenient if those buttons were scalable. I forked this repository and did a lame attempt to simply modify the xml files, which did work, but it is not a good solution. Next to that I don't seem to be able to "fill out" the available space for the buttons so that the "repeat" and "shuffle" button are totally left and right above the playlist.
So now I (inexpert amateur) come to the real pros. :)

What I did can be seen [here](https://github.com/hvdwolf/VinylMusicPlayer)
**Original screen:**
![Original screen](https://github.com/hvdwolf/VinylMusicPlayer/raw/master/images/org_main_screen.jpg)

**"My" modified screen**
![Modifiied screen](https://github.com/hvdwolf/VinylMusicPlayer/raw/master/images/new_main_screen.jpg)

**Comment by paolovalerdi** [comment]
Vinyl does support Android Auto, why not using it?

**Comment by hvdwolf** [comment]
I don't want/need Android Auto as I have a full Android car head unit. My head unit IS Android and everything runs directly on this Android head unit: VinylMusicPlayer, Android Navigation (all Android navigation), radio and the whole F-droid or Google Play Store of apks.
And when having a full Android head unit with all those apks available, I'm not going to run Android Auto only for a media player. But it is not only VinylMusicPlayer. Actually it is every media player as they all have been designed for phones, but I prefer VMP highly.
