### ISSUE TITLE
Unicode artist names are seen as <unknown>

### ISSUE THREAD

**Issue by Adrian-Bielefeldt** [AdrienPoupa/VinylMusicPlayer#191]
**Describe the bug**
Artist names with korean characters in them (specifically BTS (방탄소년단)) are rendered as <unknown>. They also show up in the artists tab under unknown artist. They are correct in the tag editor, though.

**To Reproduce**
1. Set the artist name of a song to BTS (방탄소년단).
2. Go to the artists tab.
3. Open the unknown artists.
4. See the song there.
5. Go to the albums tab.
6. Search the album of the song
7. See the artist rendered as <unknown>

**Expected behavior**
The artist shound appear under BTS (방탄소년단) in the artists tab and be rendered as BTS (방탄소년단) in album view.

**Smartphone (please complete the following information):**
 - Device: Huawei Mate 20 Lite
 - Android Version: 9
 - ROM: EMUI 9.1.0
 - Vinyl Music Player Version: 0.22.1

**Additional context**

**Comment by soncaokim** [comment]
Closing this issue as this should be fixed in the version 0.24.

Please dont hesitate to reopen if it's not the case
