### ISSUE TITLE
Search results: allow actions on multiple items

### ISSUE THREAD

**Issue by Vrihub** [AdrienPoupa/VinylMusicPlayer#194]
A useful feature of the old stock android music player was to automatically treat search results as a "temporary playlist": i.e. clicking on the first item would play it, then play the next item etc.

In vinyl, this is not supported; results from a search can only be acted upon individually: you can only play one track at a time by clicking on it (but without the standard "now playing" screen, so no cover display, no controls, why?); or you can enqueue / add to playlist only one item at a time (using the 3 dots menu on the right of each item).

One should be able to apply actions (play, enqueue, add to playlist) to multiple items in the search results list: either all items, or a selection of them.

I.e.: the "search results" view should behave like the SONGS tab, only listing the search results, instead of all tracks.

**Comment by Yiyio** [comment]
Hi, is it possible to reopen this?

**Comment by soncaokim** [comment]
If you can come forward if a pull request proposal, please do.

**Comment by mYnDstrEAm** [comment]
@soncaokim Could you please reopen this? It would be extremely useful and I don't know why it isn't already included by default. Reopening the issue also helps other devs find this issue who then may create a pull-request.

I think many people would like to be able to enter some search term and then play all tracks shown in the results...for example this could be a genre or an artists. This is especially useful if the tracks don't have the respective correct metadata set (like artist or genres) and using the search is often more convenient and quicker than using the Artists or Genres tabs and scrolling for long to find the correct one. Vinyl recently got a feature to show a context menu when you tab on a track - you could add a new context menu item like "Play all tracks of the search results".
