### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by goldencut** [AdrienPoupa/VinylMusicPlayer#2]
Very nice design, plenty of features, just wow. Some suggestions (sorry, such is life):

- [x] equalizer from player menu if not found 
- [x] sorting (by album, alphab. etc) in library-song mode => duplicate of #4 
- [ ] exit player (also exit button on notification)

Thnx,
G

**Comment by goldencut** [comment]
One more thing about the UI - those <unknown> tags - they just introduce clutter. Leaving the spot empty would be enough, to notify those who care about  tags, to add one.

**Comment by goldencut** [comment]
A question - there seems to be a hidden button in top right corner of the notification. Should this exit from the app? It does nothing on my phone.

**Comment by goldencut** [comment]
Well, while already here... Not sure if it's possible but would be cool if when pressed on 'go to home directory' second time it would take you to the file playing currently. Might be complicated implement though..

**Comment by AdrienPoupa** [comment]
hide equalizer from player menu if not found: done

**Comment by AdrienPoupa** [comment]
No hidden button for me.
