### ISSUE TITLE
Set Current Song's Album Cover As Lock Screen Wallpaper Option Not Working 

### ISSUE THREAD

**Issue by olayhemy** [AdrienPoupa/VinylMusicPlayer#20]
#### Expected behavior
If the **Current Song Album Cover As Lock Screen Wallpaper** option is enabled then it must show the song's album cover as wallpaper when on lock screen like the below image.

![Screenshot_20180319-040622.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521437174/tdk6c2lvazeraaci8e1l.png)
#### Actual behavior
When the **Current song album cover as lock screen wallpaper** option is enabled, it doesn't show the album cover on the lock screen, which means the option is not functioning as expected.

#### How to reproduce
* Lunch the app.
* Go to settings and enable the option like the below image. 
![PicsArt_03-19-05.54.59.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521437806/af5ufhp9denguzqtagjy.jpg)

* Now play any song and lock your mobile screen and then press the power button to wakeup the screen and you can notice that there is no album cover  shown on lock screen.

![Screenshot_20180319-071056.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521440080/iezh2bsrk7ib5xcod6fo.png)

* App Version: 0.16.4.4
* Operating system: Android Nougat 7.0

#### Recording Of The Bug
https://youtu.be/v-S37wB9hCs

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@olayhemy/set-current-song-s-album-cover-as-lock-screen-wallpaper-option-not-working">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by GeoZac** [comment]
@olayhemy This feature uses inbuilt system APIs to send image to lockscreen.Some OEMs do break this code,in which case,Phonograph is unable to show images on lockscreen.

**Comment by AdrienPoupa** [comment]
Thank you for the explanation
