### ISSUE TITLE
Songs vanish and artists tag chances to unknown

### ISSUE THREAD

**Issue by crucco37** [AdrienPoupa/VinylMusicPlayer#201]
Vinyl 0.22.1 F-Droid
BQ Aquaris X Pro Android 8
after some time whole albums are vanishing (such as Thievery Corporation - Abductions and Reconstructions) from the list and can't be played anymore. A new scan of the folder does not work and gives the message: 'can't be played because is not in store'.
Opening the song from explorer to play in Vinyl opens the app but doesn't show and play the file. Same files are playable and viewable in VLC and GooglePlay.
Sometimes known artists of a song changes to unknown. After new scan right name reappears.
After tinkering around for a long time with different id3-tags I gave up.
Liked the app because of the artists pictures and the possibility to read the lyrics.
But with these cataloging issues it becomes almost useless. Because there are also other apps for free that do part of the job.

Also the app 'Musik' from Max_Four on F-Droid has the exact same problems.
https://github.com/MaxFour/Music-Player/
Who is copying here from one another?

**Comment by wchen342** [comment]
Not sure whether it is exactly the same problem but I faced sth similar and I think I kind of having a solution. So for me my songs are on SD card and when I restart my phone the songs in my playlists will disappear randomly. The solution is that whenever you restart the phone or eject/remount your SD card, you do not open the player until the notification at the top of your screen says sth like "SD card is ready for use". There is another read permission problem but that one is probably unrelated.

**Comment by crucco37** [comment]
Hello,

nice to hear something. I don’t know why Mr. Poupa himself doesn’t
answer any questions.

I think this is very poor and miserable. He just could say
he’s not interested in support. We’ll help ourselves anyway
without him. My solution for now is to use other music apps
as well. But believe me, the others aren’t any better.

So I came up with a better solution. Now I use a FiiO
player as music player instead of my cellphone.
Software-sided it is not the desired alternative
but sound-quality-sided it’s a big leap forward.

cheers
_t


-----Original Message-----
Von: wchen342 <notifications@github.com>
Antworten: AdrienPoupa/VinylMusicPlayer <reply@reply.github.com>
Datum: 4. Januar 2020 at 23:06:23
An: AdrienPoupa/VinylMusicPlayer <vinylmusicplayer@noreply.github.com>
CC: crucco37 <crucco@riseup.net>, Author <author@noreply.github.com>
Betreff:  Re: [AdrienPoupa/VinylMusicPlayer] Songs vanish and artists tag chances to unknown (#201)

**Comment by AdrienPoupa** [comment]
@crucco37 people like you making toxic comments are the reason why some maintainers (spending their free time on non profit projects) quit the open source world altogether.

If you're so fed up with this issue, do some research by yourself, write a fix and I'll gladly accept it. In the meantime, under no circumstance you can blame me or anyone else for not answering your incomplete bug report.

As for who's copying who, both application are a fork of the same app, Phonograph. Have fun using FiiO.
