### ISSUE TITLE
The playlist's number of songs does not get updated in time

### ISSUE THREAD

**Issue by junior291492659** [AdrienPoupa/VinylMusicPlayer#206]
**Describe the bug**
The playlist created by users or by clicking favorite do no get updated immediately when a song is added to it unless this playlist is created by adding a song in the first time.

**To Reproduce**
1. Go to 'SONG' page
2. Click the dot icon(rigght) of a song(e.g. yourname, as shown in the video)
3. Click  'Add to playlist...'
4. Click 'New playlist...'
5. Input 'Test' (now we can see the 'Test' playlist's number of songs is 1 in 'PLAYLISTS' page, this is correct behavior)
6. repeat steps 2,3(to add this song to the 'Test' playlist again, here we can choose a different song as well, same result)
7. Click 'Test'
8. Go to 'PLAYLISTS' page

**Expected behavior**
The 'Test' playlist's number of songs is 2

**Actual behavior**
The 'Test' playlist's number of songs is still 1. However, if we click 'My top tracks'(any playlist is fine, including 'Test' playlist itself), then click the back icon(upper left), the number gets updated.

In fact, if we firstly create a new playlist in 'PLAYLISTS' page, then add a song to it, the number does not get updated in time.

**Reproducing video**
[https://youtu.be/gzDELrxFhcs](https://youtu.be/gzDELrxFhcs)

**Devices:**
 - Device: a Redmi Note 4X and an Android emulator 6.0 device.
 - Android Version: 6.0
 - Vinyl Music Player Version: latest version 0.22.1, and we also built the newest code in android studio to run, same thing happens.

This can be confusing and a bug as well. Anyway, thanks for your amazing app and it would be really appreciated to get your concern on this.

**Comment by junior291492659** [comment]
Hello, any update on this issue?

**Comment by tingsu** [comment]
I also encounter this small GUI issue. It seems due to the UI update issue. Any plan to fix this in the new released version? Thanks.

**Comment by soncaokim** [comment]
If I'm not wrong, @AdrienPoupa picked some change from upstream that fixes this bug, which is/will be shipped with version 0.24.0
