### ISSUE TITLE
[Feature request] All music folders in a library tab

### ISSUE THREAD

**Issue by rubencg17** [AdrienPoupa/VinylMusicPlayer#21]
Hi! Thanks for develop this app and remove propietary stuff.
The only thing i miss is a folder tab alongside Songs, albums, playlist, etc.
The idea is to show all folders which contain playable files.
In the currently folder view you have to go manually to the folder you want to play.
This tab would show you all folders without having to navigate to them.
Something like [this](https://upm365-my.sharepoint.com/:i:/g/personal/r_cristobal_alumnos_upm_es/ET8JuaUVP7dIu1KpBeu6-SMB6Sk9PQHns-9SyCnsktJI7w?e=Ea1ihJ).
Thanks!!

**Comment by hvdwolf** [comment]
This is already an old one, but upon seeing it last year I did not add my thumbs-up (just did that after all) or so as Adrien added the feature request relatively fast after the "issue" was created. 
However, this is now older than a year and I would also like to see this in VinylMusicPlayer.
Is this being picked up in the near future?
