### ISSUE TITLE
Time slider of notification not correctly updated

### ISSUE THREAD

**Issue by lriesebos** [AdrienPoupa/VinylMusicPlayer#221]
**Describe the bug**
Using Android Q (10), Vinyl shows a "silent notification" when playing music. The notification contains a time slider, which is not always showing the correct time and position on the slider.

**To Reproduce**
1. Start playing a song in Vinyl, the notification will appear and is correct
2. Use the notification time slider to skip a part of the song. The song will resume playing from the desired position, but the notification time slider and play time indicator pop back to the position they had before the slider was touched.
3. When now pausing the song from the notification buttons, the time slider of the notification pops to the correct position (where the song was actually playing).

The bug also appears in other situations. For example when a song finishes and the next song is automatically played. The next song starts playing, but the times and time slider of the notification hang in the ending position of the previous song.

**Expected behavior**
At any time, the current playing time, song duration, and time slider of the notification should show the correct information.

**Smartphone (please complete the following information):**
 - Device: Nokia 7 plus
 - Android Version: 10 (Q)
 - ROM: Manufacturer provided rom
 - Vinyl Music Player Version: 0.23.1

**Comment by Gotolei** [comment]
Also having this, except for me, unlike in this report and #239, at the end of a song the seekbar does correctly reset to zero and begin seeking again. I'll also add that while music is paused, the seekbar stays put as it should (the error seems to happen when the time counter ticks up a second). Upon resumed play of music the bar also resumes from the correct spot.

**Video:** https://youtu.be/q-dw8s72nYo?t=5
Phonograph does not have this problem.

**Smartphone**
 - Device: OnePlus 6
 - Android Version: 10
 - ROM: LineageOS 17.1 (20200403)
 - Vinyl Music Player Version: 0.23.1 (Play Store)

**Comment by tguen** [comment]
This bug still exists on my Pixel 4a with Android 11, app built from newest commit (977698aa0e1963a530f5480bf5eb705134503a6a)

**Comment by ZenerDeveloper** [comment]
This bug is also happening for me on a Galaxy s10+ with oneui3(android 11)
