### ISSUE TITLE
Changing the position of the current track in the queue

### ISSUE THREAD

**Issue by notsaman** [AdrienPoupa/VinylMusicPlayer#223]
So, I actually don't know if it's expected behaviour, but here it goes. I can't change the position of the currently playing song in the queue UNLESS I pause first. So say I want to drag the current song to the end of the queue, I can only do that when I paused first. Very weird. 

-

Device info:
---
<table>
<tr><td>App version</td><td>0.23.1</td></tr>
<tr><td>App version code</td><td>168</td></tr>
<tr><td>Android build version</td><td>G935FXXS7ESL9</td></tr>
<tr><td>Android release version</td><td>8.0.0</td></tr>
<tr><td>Android SDK version</td><td>26</td></tr>
<tr><td>Android build ID</td><td>R16NW.G935FXXS7ESL9</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>hero2lte</td></tr>
<tr><td>Device model</td><td>SM-G935F</td></tr>
<tr><td>Device product name</td><td>hero2ltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos8890</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by bertin0** [comment]
A small workaround I found is to move the adjacent songs twice in quick succession sand that somehow unlocks the current 7 playing sony
