### ISSUE TITLE
Add Song to playlist

### ISSUE THREAD

**Issue by domenic64** [AdrienPoupa/VinylMusicPlayer#226]
Nokia 6.1 with android 10. Spese not add the Song to the playlist
Not remove Song to the playlist
-

Device info:
---
<table>
<tr><td>App version</td><td>0.23.1</td></tr>
<tr><td>App version code</td><td>168</td></tr>
<tr><td>Android build version</td><td>00WW_4_10C</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>00WW_4_10C</td></tr>
<tr><td>Device brand</td><td>Nokia</td></tr>
<tr><td>Device manufacturer</td><td>HMD Global</td></tr>
<tr><td>Device name</td><td>DRG_sprout</td></tr>
<tr><td>Device model</td><td>Nokia 6.1 Plus</td></tr>
<tr><td>Device product name</td><td>Dragon_00WW</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by soncaokim** [comment]
I'm closing this as I beleive this is linked to https://github.com/AdrienPoupa/VinylMusicPlayer/issues/248
