### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by naboql** [AdrienPoupa/VinylMusicPlayer#228]
Hi. I really like your project. Now Vinyl is my daily music player. However, I see there are some items in the app that aren't translated to Spanish, so as a native Spanish speaker I would be glad to help translating some of the text in the app that remains untranslated to Spanish. Greetings.

-

Device info:
---
<table>
<tr><td>App version</td><td>0.23.1</td></tr>
<tr><td>App version code</td><td>168</td></tr>
<tr><td>Android build version</td><td>00WW_3_54J</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>00WW_3_54J</td></tr>
<tr><td>Device brand</td><td>Nokia</td></tr>
<tr><td>Device manufacturer</td><td>HMD Global</td></tr>
<tr><td>Device name</td><td>PL2_sprout</td></tr>
<tr><td>Device model</td><td>Nokia 6.1</td></tr>
<tr><td>Device product name</td><td>Plate2_00WW</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by AdrienPoupa** [comment]
My Spanish is not that great, so feel free to open a PR to add the missing translations
