### ISSUE TITLE
FLAC / No audio on first play

### ISSUE THREAD

**Issue by doctaweeks** [AdrienPoupa/VinylMusicPlayer#230]
**Describe the bug**
When the app is first opened, the first file played will appear to begin in the UI (starts counting, displays pause button, notification, etc) but no audio is produced. Starting the same song over again will produce audio and any subsequent tracks are fine. I have only reproduced this with FLAC.

**Smartphone (please complete the following information):**
 - Device: Moto Z2 Play
 - Android Version: 8.0.0
 - ROM: Stock
 - Vinyl Music Player Version: 0.23.1

**Comment by doctaweeks** [comment]
Retested on 0.24.1 and this is still an issue. Additionally, once "playback" begins, pressing the previous track button will reset the counter to the beginning of the song but it will still not output audio. Still the only thing that appears to fix this is going to back to track selection and selecting the track over again.

**Comment by soncaokim** [comment]
I'm updating the title with Flac since you've mentioned that
