### ISSUE TITLE
Can't play music anymore

### ISSUE THREAD

**Issue by ThomasLeigh** [AdrienPoupa/VinylMusicPlayer#231]
Hello :) For a long time I’ve been using Vinyl Music Player with no issues. All my music files have been placed onto sd-card. Recently, however, I’ve decided to move the music to the internal storage instead of sd-card - as a result of which I can’t play the music anymore (even after cleaning the app’s cache). What happens is that: 1. There is no reaction on “Play next”, “Add to playing queue”, “Add to playlist” or “Scan” commands. 2. Once I’ve set a particular folder (within “Emulated/0/”) from the internal storage as the start directory, I can’t navigate to it anymore using the “Folders” tab - there are neither files or folders displayed under the “Emulated” item (the same in case of “Self” - while files and folders on sd-card are still reachable). 3. If I tap on any particular music file, the following message is displayed: “[a file name] is not listed in the media store”. -- Thank You for Your time, Thomas Leigh

-

Device info:
---
<table>
<tr><td>App version</td><td>0.23.1</td></tr>
<tr><td>App version code</td><td>168</td></tr>
<tr><td>Android build version</td><td>V11.0.4.0.PFGEUXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180904.001</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>lavender</td></tr>
<tr><td>Device model</td><td>Redmi Note 7</td></tr>
<tr><td>Device product name</td><td>lavender_eea</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by Cantuariensis** [comment]
Howdy 😊
Have you tried reinstalling Vinyl? If that didn't solved the issue, here's what I would do, but that may be _really_ time consuming:

1. Uninstall Vinyl (export your playlists before if needed)
2. Move all your music on your computer and delete the empty "Music" folder
3. Recreate the "Music" folder at the root of internal storage, and copy your music again in it.
4. Reboot your phone and then reinstall Vinyl from the Play Store

That should reset app and folder authorizations and the MediaStore database.

**Comment by AdrienPoupa** [comment]
Closing due to lack of information
