### ISSUE TITLE
Some albums are split into two entries in "Albums" view

### ISSUE THREAD

**Issue by ArbysSauce** [AdrienPoupa/VinylMusicPlayer#232]
**Describe the bug**
Two albums are split into two entries in Vinyl's "Albums" view. They are not duplicate entries; each entry has some of the songs from the album while the other contains the rest.
The files are all correctly tagged with the same album and album artist.

**Expected behavior**
The albums affected should take up only one entry. Other music players show them correctly, so it appears the issue is with Vinyl, not the files.

**Screenshots**
https://i.imgur.com/vs9hNms.png
https://i.imgur.com/03iojDL.png
https://i.imgur.com/dvJpbUm.png

**Smartphone (please complete the following information):**
 - Device: Motorola Moto X4
 - Android Version: 9
 - ROM: LOS + microG
 - Vinyl Music Player Version: 0.23.1

These screenshots also show off the already reported issue with unnecessary ellipsis.

**Comment by pokemonpasta** [comment]
Reproducible

**Smartphone**
- Device: Alcatel 3 (2019) 5053Y
- Android Version: 9
- ROM: TCTROM
- Vinyl Music Player Version: 0.23.1

**Comment by soncaokim** [comment]
This should be fixed with version 0.24.

Dont hesitate to reopen if the fix is not okay
