### ISSUE TITLE
Shuffle albums

### ISSUE THREAD

**Issue by mhammond** [AdrienPoupa/VinylMusicPlayer#233]
It would be great to have a "shuffle album" feature - much like shuffling songs, although complete albums are added to the playlist, with the songs in the order they appear on the albums.

Some players support this, but I'm failing to find an active open-source one that does. I'd be interested in contributing to this feature if there's general agreement that the feature is desirable.

**Comment by tjgordon** [comment]
Shuttle and Vanilla are the only open source players with this feature that I've found.
