### ISSUE TITLE
Default album cover is not consistent

### ISSUE THREAD

**Issue by Cantuariensis** [AdrienPoupa/VinylMusicPlayer#235]
Hi guys,
(Off topic : Thanks for this gorgeous app!! Probably the one I'm using the most on my phone! 👌🏻)

**The bug**
The default cover used for tracks without album cover is not consistent in those 3 states : _not played_, _now playing_, _previously played_. And when exiting and opening again the list view (album, artist or playlist) the _previously played_ state is forgotten.

**To reproduce**
1. Open an album of tracks without art cover. Tracks all have the default cover from the Vinyl app (n°1 on my screenshot)
2. Play one track, the cover will change to another cover (the _now playing_ icon, n°2 on the screenshot)
3. Play a second track. The first track previously played will get another cover (n°3)
4. Exit the album view and open it again, the first track we just played is reverted to the n°1 cover.

**Expected behavior**
1. The _previously played_ state should be kept when exiting and reopening the view
2. Not sure it's a good feature to show a different default cover (the n°3) when a track has already been played. I'd rather show the original album art in 50% opacity, with an entry in the Settings to adjust or disable the time difference.
2. The now playing icon/cover (n°2) should not be so close to the default cover, it is confusing and hard to spot the playing track in a long list of tracks. I'd rather use something like https://cdn1.iconfinder.com/data/icons/line-music-ui/256/line_music_pink_icon_.Artboard_22-512.png

**Screenshot**
![ddd](https://user-images.githubusercontent.com/62208363/76702770-c6080f80-66cc-11ea-960f-2d5f50829c13.png)

**Smartphone**
 - Device: Honor 7X / Fairphone 3
 - Android version: 8 / 9
 - ROM: EMUI / stock
 - Vinyl Music Player version: 0.23.1 (latest on the Play Store as of 03/15/2020)

**Additional context**
I'm designer, and web developer on my free time. So if I can help to do a Material Design icon for the now playing and some Illustrator mock-ups, I'd be happy to contribute! 🍻

**Comment by soncaokim** [comment]
I will have a look at this.

On the "The now playing icon/cover (n°2) should not be so close to the default cover, it is confusing and hard to spot the playing track in a long list of tracks.": You can choose to animate the now playing icon (in settings, animate playing song icon), it should be more easy to spot, in addition to the bold font used.

**Comment by soncaokim** [comment]
Talking about icons, @AdrienPoupa you may need to update the screenshot shown in readme. It still rely on old icons.
