### ISSUE TITLE
Queue stuck when playing from Android auto

### ISSUE THREAD

**Issue by shbach** [AdrienPoupa/VinylMusicPlayer#237]
When using Vinyl from android auto, the queue is stuck on the previously existing queue, regardless of what what is selected to play. If I select to play something else, that is completely ignored and the previous queue plays. This is especially problematic if at the last song in the queue as it then becomes stuck on that song. The only way to fix this is to open up Vinyl on the phone and manually clear the queue or play a song from there before returning to android auto. Obviously this is not advisable to to do while driving. 

This only seems to happen if launching android auto after a large amount of time has elapsed since playing something with Vinyl. It doesn't occur if vinyl was recently used. 

This is an incredibly annoying bug and I would appreciate any help with this.

 - Device: OnePlus 5T
 - Android Version: 9
 - Vinyl Music Player Version: 0.23.1

**Comment by soncaokim** [comment]
Just curious: how do you open Vinyl via Android Auto?

**Comment by shbach** [comment]
I use the Android auto app on my phone and use vinyl from the menu in Android auto.

**Comment by soncaokim** [comment]
Weird, I dont see any mean to open Vinyl in Auto.
I'm using the on-device app.

Is there any black or white listing to do?

Thanks

**Comment by shbach** [comment]
I'm confused by your question. Are we talking about the same thing? Vinyl has Android auto support.

![Screenshot_20200926-110404](https://user-images.githubusercontent.com/5298745/94347375-5d3d1080-ffe8-11ea-8ab5-a708ddeabe30.jpg)

**Comment by soncaokim** [comment]
Interesting. On my phone, long pressing the headphone icon in Android Auto doesnt show Vinyl (it shows Google Play Music/Spotify).

Is it because I've always running the non Google Play version?

**Comment by shbach** [comment]
I'm using the Google play version so that's probably it.

**Comment by soncaokim** [comment]
That's the reason. Thanks

**Comment by shbach** [comment]
No problem. Post if you notice the same bug occuring as me.

**Comment by soncaokim** [comment]
Actually this is quite straight forward to reproduce. 
The part 
> only seems to happen if launching android auto after a large amount of time has elapsed since playing something with Vinyl. It doesn't occur if vinyl was recently used.

is important.

**Comment by shbach** [comment]
Yeah that does seem to be the important bit. Not sure what the exact amount of time has to elapse first or the mechanism for this occuring though.
