### ISSUE TITLE
Adding a song to playlist doesn't work

### ISSUE THREAD

**Issue by andejong** [AdrienPoupa/VinylMusicPlayer#242]
After making a new playlist, I can't add any songs. Same when I create playlist with a song. It's just empty.

**Comment by Vrihub** [comment]
I am experiencing the same problem after upgrading my device from android 9 to 10 (I guess the new version has stricter/different writing permissions)

Maybe #243 is related too.

**Comment by cauerego** [comment]
as mentioned there, i got same problem here. fresh install. first time.

**Comment by soncaokim** [comment]
I'm closing this as I beleive this is linked to https://github.com/AdrienPoupa/VinylMusicPlayer/issues/248
