### ISSUE TITLE
New music not added

### ISSUE THREAD

**Issue by Embridioum** [AdrienPoupa/VinylMusicPlayer#243]
Scan doesn't add new music to the library. Folders and permissions are set correctly. I have even tried several MP3's individually with the scan option. 

-

Device info:
---
<table>
<tr><td>App version</td><td>0.23.1</td></tr>
<tr><td>App version code</td><td>168</td></tr>
<tr><td>Android build version</td><td>V11.0.1.0.QFCEUXM</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QKQ1.190828.002 test-keys</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>pyxis</td></tr>
<tr><td>Device model</td><td>Mi 9 Lite</td></tr>
<tr><td>Device product name</td><td>pyxis_eea</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by soncaokim** [comment]
This might be related to https://github.com/AdrienPoupa/VinylMusicPlayer/pull/274 (pending a  new release).
I'm closing this for now, please dont hesitate to reopen if it's not fixed.
