### ISSUE TITLE
Bad text encoding

### ISSUE THREAD

**Issue by darkvadd7** [AdrienPoupa/VinylMusicPlayer#245]
With some albums, the text isn't displayed properly:
![Screenshot_2020-05-14-14-00-37-585_com poupa vinylmusicplayer](https://user-images.githubusercontent.com/48321826/81933354-876bd400-95ed-11ea-95f2-9017fe684ff4.jpg)
But when I edit the informations of the track, it's okay.

**Comment by soncaokim** [comment]
When you open the ID3 tag editor in the application, does it show the correct info?

**Comment by darkvadd7** [comment]
Yes it is, and it also works in Poweramp.

**Comment by soncaokim** [comment]
I'm afraid this should be related to #67, which has no fix for the moment.

I'm closing this, any comment/insight please use the original one.
