### ISSUE TITLE
Equalizer Bluetooth

### ISSUE THREAD

**Issue by plegrand1** [AdrienPoupa/VinylMusicPlayer#246]
Hello,
I use your app on a Xiaomi MI9 smartphone and Airpod Pro headphones.
I note that whatever the settings used on the equalizer, sound is absolutely unchanged.
Is it a bug or a problem of incompatibility with my hardware?
Thank you for your help

Also, itseems that it's the same app than "Music-Player" on F-Droid.
AM'i wrong ?

Pascal

**Comment by AdrienPoupa** [comment]
Hello,

The app does not offer any equalizer, it is opening your phone's.

"Music-Player" on F-Droid and Vinyl are related in the sense that they both are forks of Phonograph
