### ISSUE TITLE
Off timer does not work properly.

### ISSUE THREAD

**Issue by shirou-jeff** [AdrienPoupa/VinylMusicPlayer#25]
#### Expected behavior
The user expects to be able to use the off timer, and program it while you want to turn off the music playback.
#### Actual behavior
The user cannot use the off timer, and program it while you want to turn off the music playback. Because it doesn't work in the application. When programmed and let the music roll, we notice that the stipulated time elapses and the playback does not stop.

#### How to reproduce
- Download the [application](https://play.google.com/store/apps/details?id=com.poupa.vinylmusicplayer). 
- Install. 
- Play a song of your liking and schedule the off timer. 
- As the stipulated time elapses, we notice that the music continues to sound.

* Browser: vinyl music player V 0.16.4.4
* Operating system: Android 5.1.1

#### Recording Of The Bug
https://youtu.be/QPQx2OQzc4U
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@shirou-jeff/off-timer-does-not-work-properly">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by AdrienPoupa** [comment]
Works fine for me, I can't reproduce
