### ISSUE TITLE
Artists Not Completely Alphabetised

### ISSUE THREAD

**Issue by areit99** [AdrienPoupa/VinylMusicPlayer#250]
**Describe the bug**
Under 'Artists' tab, most artists are in the correct order, but some are out of place. In some cases this could be due to surname, but in others it's unclear.

**Screenshots**
![Screenshot_20200618-010704_Vinyl Music Player](https://user-images.githubusercontent.com/44483983/84994983-4db44e80-b100-11ea-8fcf-990a9a08a82a.jpg)

![Screenshot_20200618-010935_Vinyl Music Player](https://user-images.githubusercontent.com/44483983/84995072-6a508680-b100-11ea-9afb-209d0e421d40.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10
 - Android Version: 10
 - ROM: ?
 - Vinyl Music Player Version: 0.23.1

**Comment by soncaokim** [comment]
Should be related to https://github.com/AdrienPoupa/VinylMusicPlayer/issues/67, which has no fix for the moment :-(

I'm closing this, any commeny(insight please use the original one.
