### ISSUE TITLE
Multi-disc album track sorting

### ISSUE THREAD

**Issue by AitorElorza** [AdrienPoupa/VinylMusicPlayer#251]
When the album has more than one discs the program does not separate them. So you end with 1. songCD1, 1. songCD2, 2. songCD1,  2. songCD2 

-

Device info:
---
<table>
<tr><td>App version</td><td>0.23.1</td></tr>
<tr><td>App version code</td><td>168</td></tr>
<tr><td>Android build version</td><td>eng.root.20200518.233251</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>RMX1993EX_11_C.04</td></tr>
<tr><td>Device brand</td><td>realme</td></tr>
<tr><td>Device manufacturer</td><td>realme</td></tr>
<tr><td>Device name</td><td>RMX1993L1</td></tr>
<tr><td>Device model</td><td>RMX1993</td></tr>
<tr><td>Device product name</td><td>RMX1993EEA</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by BDex** [comment]
I observed a similar behaviour, illustrated in the screenshot below. 
The albums directory structure is as follows:
- \<Album Name\> 
    - Disc 1
        - Track 1-01 
        - Track 1-02 
        - ... 
    - Disc 2
        - Track 2-01 
        - Track 2-02 
        - ... 
    - Disc 3 
        - Track 3-01 
        - Track 3-02 
        - ... 
Yet the tracks seem to be order by track number first (3-01 -> 2-01 -> 1-01 -> 3-02 -> 2-02...), as shown on the screenshot below.
In a single album, could tracks be ordered by disc first, when available? Or did I miss something? 
Thanks! 

Sample screenshot: 
![Screenshot_20200709-092702_edited](https://user-images.githubusercontent.com/3939244/87012129-244f8580-c1c9-11ea-9d38-8011d618b016.jpg)

Device info:
---
<table>
<tr><td>App version</td><td>0.23.1</td></tr>
<tr><td>App version code</td><td>168</td></tr>
<tr><td>Android build version</td><td>2005132200</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>GM1913_21_200519</td></tr>
<tr><td>Device brand</td><td>OnePlus</td></tr>
<tr><td>Device manufacturer</td><td>OnePlus</td></tr>
<tr><td>Device name</td><td>OnePlus7Pro</td></tr>
<tr><td>Device model</td><td>GM1913</td></tr>
<tr><td>Device product name</td><td>OnePlus7Pro_EEA</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by soncaokim** [comment]
I'm gonna change the issue title  to reflect this multi-disc situation.

**Comment by Kaerbr** [comment]
I have this issue too. So i tried to investigate. This is what I found out so far:
Android studio virtual device (i think it was a Pixel 3XL oder Pixel 3a XL):
- API lvl 29 --> got the issue
- API lvl 30 --> didnt get the issue

I hope this helps. (:

**Comment by soncaokim** [comment]
The fix for this issue is merged to the main branch - I'm closing the issue for now.
