### ISSUE TITLE
cant add on playlist

### ISSUE THREAD

**Issue by libertyfromthinking** [AdrienPoupa/VinylMusicPlayer#252]
cant use heart button and playlist

-

Device info:
---
<table>
<tr><td>App version</td><td>0.23.1</td></tr>
<tr><td>App version code</td><td>168</td></tr>
<tr><td>Android build version</td><td>A516NKSU1ATE6</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QP1A.190711.020.A516NKSU1ATE6</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a51x</td></tr>
<tr><td>Device model</td><td>SM-A516N</td></tr>
<tr><td>Device product name</td><td>a51xks</td></tr>
<tr><td>Device hardware name</td><td>exynos980</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by soncaokim** [comment]
I'm closing this as I believe this is linked to https://github.com/AdrienPoupa/VinylMusicPlayer/issues/248
