### ISSUE TITLE
Problem with app maskable icon 

### ISSUE THREAD

**Issue by Cantuariensis** [AdrienPoupa/VinylMusicPlayer#265]
**Describe the bug**
The app icon is not masked properly in launcher. Tested on Microsoft Launcher and Quickstep (Fairphone 3 default launcher).

**Expected behavior**
App icon should be closer the one on the store:
![e](https://lh3.googleusercontent.com/XijXz_QsXiKJU0iviv7eldNaO_WFD2AuSMM5r5Vy5nRpBkdI57wc6dXoOcExD2BjiKY=s100)

**Screenshots**
![e](https://user-images.githubusercontent.com/62208363/89988663-2a30fe80-dc80-11ea-8089-b67fdc4e3f45.png)

**Smartphone (please complete the following information):**
 - Device: Fairphone 3
 - Android Version: 9
 - Vinyl Music Player Version: 0.23.1

**Comment by Cantuariensis** [comment]
If someone knows the different sizes that need to be added, I would be happy to edit them 👍🏻

**Comment by AdrienPoupa** [comment]
I just regenerated the icons with the Image Asset Studio as explained here https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

**Comment by soncaokim** [comment]
Is this solved with version 0.24.0?
