### ISSUE TITLE
About dialog is hard to read on version 0.24.0

### ISSUE THREAD

**Issue by soncaokim** [AdrienPoupa/VinylMusicPlayer#266]
**Describe the bug**
About dialog is hard to read (dark text on dark background).

**Screenshots**
![Screenshot_20200813-125245](https://user-images.githubusercontent.com/13333482/90126584-32626a00-dd64-11ea-8122-b1fe3d29d95c.jpg)

**Comment by soncaokim** [comment]
Same remark for the now playing song decoration, as per screenshot
![Screenshot_20200813-130625~2](https://user-images.githubusercontent.com/13333482/90127798-0f38ba00-dd66-11ea-9f24-7e8ff76b6dc4.jpg)

**Comment by AdrienPoupa** [comment]
It is most likely linked to the Material update:

https://github.com/AdrienPoupa/VinylMusicPlayer/pull/254#issuecomment-673255516
https://github.com/AdrienPoupa/VinylMusicPlayer/commit/4b794baa7829290c1fe5a5a8bc83b8013e6c6ed1#diff-e3664de32db822c9fe78ed5dacf4d8dc

**Comment by Tom4tot** [comment]
@soncaokim I'm sorry for the dumb question but how did you get the 0.24 update. Did you build it from sources or did it get pulled? Or am I just blind?

**Comment by soncaokim** [comment]
I've built it from source. 

You can grab a copy for example here from my CI build - given that you accept the risk of downloading and installing an alien app not vetted by Google Play: 
https://211-175573618-gh.circle-artifacts.com/0/outputs/circleci/release/app-circleci-release.apk

**Comment by AdrienPoupa** [comment]
@Tom4tot I would not recommend it for now as it is unstable and may contain bugs

**Comment by Tom4tot** [comment]
Thanks for your answers @AdrienPoupa and @soncaokim.

**Comment by TacoTheDank** [comment]
@AdrienPoupa Would changing CardView to MaterialCardView in the code fix some of this?

**Comment by soncaokim** [comment]
I reopen this issue: looks like this is not working properly on default theme (it will be white on white)

**Comment by AdrienPoupa** [comment]
Using `android:theme="@style/Theme.MaterialComponents.DayNight"` does not seem to help neither.

We need to fix this before we can release 0.24, I'm open to any help

**Comment by soncaokim** [comment]
Should we consider rollbacking the changes?

**Comment by AdrienPoupa** [comment]
Not sure, we need to update the libraries at some point

**Comment by soncaokim** [comment]
By reverting the 9be80fc8 (and consequently ac315e80), we get back to a correctly colored app. Probably now we want to downgrade one by one the upgraded dependencies

**Comment by soncaokim** [comment]
This should help isolating the issue: https://github.com/soncaokim/VinylMusicPlayer/commit/40b5378a5379042eda95d54b7118615de91aae48

**Comment by AdrienPoupa** [comment]
You're right. But we'll need to fix this eventually

**Comment by soncaokim** [comment]
@AdrienPoupa I guess we can close this for now?
