### ISSUE TITLE
Not displayed track numbers "08" and "09"

### ISSUE THREAD

**Issue by stepanmracek** [AdrienPoupa/VinylMusicPlayer#269]
**Describe the bug**
The songs are tagged "08" and "09" but they are shown up at the top of the album, out of order.

**To Reproduce**
1. Edit ID3 tag of any song in the album and set the track number to "08" or "09" 
2. Go to the album
3. See error, track numbers of songs "08" and "09" is shown as "-"

**Expected behavior**
I Would expect that the song numbers will be displayed as "8" and "9"

**Additional context**
I think that it is caused by automatic conversion of strings
"08" and "09" to integers. When string starts with "0" Android/VinylMusicPlayer is trying to parse them as octals. "08" and "09" are invalid octal values. I also tried to set track numbers to "010" and "011" and as I expected - they were displayed in Phonograph as tracks 8 and 9.

**Comment by sersorrel** [comment]
fwiw, this was happening to me also, but seems to be fixed in the latest update

**Comment by AdrienPoupa** [comment]
Great, I will close it, please reopen if needed
