### ISSUE TITLE
F-Droid version last update January 2020

### ISSUE THREAD

**Issue by blackCauldron7** [AdrienPoupa/VinylMusicPlayer#272]
Is the project dead?

**Comment by Cantuariensis** [comment]
It's the same version (0.23.1) on Play Store and F-Droid, and both are still supported I think.
A lot is happening recently. You can check [here](https://github.com/AdrienPoupa/VinylMusicPlayer/pulls?q=is%3Apr) the Pull Requests that will arrive soon in the app :)
