### ISSUE TITLE
Add repeat and shuffle toggles in notification.

### ISSUE THREAD

**Issue by blackCauldron7** [AdrienPoupa/VinylMusicPlayer#273]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to loop one song and I have to open the app and then the now playing screen to do such a frequent task.

**Describe the solution you'd like**
I want the repeat and shuffle toggles in the notification.

**Describe alternatives you've considered**
Mapping fingerprint sensor using tasker to loop song after it ends.

**Additional context**
None

**Comment by jneidel** [comment]
> frequent task

Very subjective. I never do this.

> repeat and shuffle toggles in the notification.

I find the pause button to hard to press as it is. Cluttering up the notification more is just gonna make it worse, as everything has to get smaller to fit in new icons.

**Comment by blackCauldron7** [comment]
Maybe a toggle then in the settings for those who need it.
