### ISSUE TITLE
Duplicate files on disk show up twice in Vinyl.

### ISSUE THREAD

**Issue by travisfw** [AdrienPoupa/VinylMusicPlayer#289]
**Describe the bug**
I have two folders. One is managed by an app that downloads music. One is my music folder that I manage. I copy things from the app folder to my folder often, but then they show up twice in Vinyl. When subsequent rows under an album are exactly the same, it seems like it should be easy for Vinyl to just list a song once.

**To Reproduce**
1. copy tracks into two folders
2. scan media with Vinyl
3. look at the album
4. tracks appear twice

**Expected behavior**
The tracks in an album should be listed once regardless of file system copies. Vinyl is not for file management.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab S6 (SM-T865N)
 - Android Version: 10
 - ROM: no read-only memory installed.
 - RAM: 8G
 - Vinyl Music Player Version: 0.23.1

**Comment by soncaokim** [comment]
Have you tried adding the first folder to the blacklist?

**Comment by travisfw** [comment]
Not everything in that folder is necessarily duplicated, and I don't want to exclude music.
