### ISSUE TITLE
Folders on external SD cannot be blacklisted? 

### ISSUE THREAD

**Issue by kr428** [AdrienPoupa/VinylMusicPlayer#29]
Hi there, 
tried to add folders on my external SD card to the blacklist and failed: In the blacklist configuration / folder chooser I am always within /storage/emulated /0. Being able to cd .. in there would be helpful. ;)

Cheers,
Kristian

**Comment by AdrienPoupa** [comment]
Oh, this is a nice catch! From what I see, and I'm not sure why, if you do "Add", select any folder, THEN do "..", the ".." option will appear for /storage/emulated /0

**Comment by kr428** [comment]
Indeed. I didn't actually notice. So the ".." is just missing the first view after doing "Add". Works for me this way but still might be worth a fix. ;)

**Comment by AdrienPoupa** [comment]
For sure! Thanks for the report :)

**Comment by AdrienPoupa** [comment]
For some reason, "File.pathSeparator" was returning ":" instead of "/".

**Comment by kr428** [comment]
Wow that was fast. Cool, thanks. :)
