### ISSUE TITLE
App Size

### ISSUE THREAD

**Issue by moriel5** [AdrienPoupa/VinylMusicPlayer#3]
I know that this sounds incredulous, however do you think that it would be possible to make Vinyl Music Player weigh less than 3MB, similarly to Odyssey Music Player?

This could also become an opportunity for turning Vinyl into what some may call a full-fledged fork, rather than what the same people would call a simple copy that is only meant for people to get the full version of Phonograph for free.

Disclaimer: I personally see this as a seperate app from Phonograph, not a simple copy, and I wholeheartedly support endeavors to make proper FOSS apps, even if I am obsessed with them being ultra-light, without sacrificing either function nor form (I do lean towards function over form, though).

**Comment by AdrienPoupa** [comment]
Hello,

I will see if it is possible to do so :)

**Comment by moriel5** [comment]
Thanks, that's great to hear.
And sorry about adding more hard work.

**Comment by AdrienPoupa** [comment]
![image](https://user-images.githubusercontent.com/15086425/36334890-6e3e465c-134a-11e8-9926-51247ada67df.png)
I did my best to reduce the image files. However, most of the size comes from the dependencies, which are all needed right now, especially the v4 and v7 compat. I will see if I can get rid of some later.

**Comment by moriel5** [comment]
Thanks, don't worry about it.
What I had asked for isn't a hard requirement, although it is very much preferred.
