### ISSUE TITLE
Minimum number of songs filter

### ISSUE THREAD

**Issue by mziehm** [AdrienPoupa/VinylMusicPlayer#309]
Please include an option in the artists, albums and genres views to show only entries with a user defined minimum number of songs, e.g. show only albums with at least 5 songs. Ideally bundle the excluded songs in a various artists/albums/genre category.

This will allow users to clean up the list, if the library contains few selected songs from many albums or artists, making easier to find the complete albums. 

See also [kabouzeid#496](https://github.com/kabouzeid/Phonograph/issues/496) and possible solution at least for artists [kursadsaka#9](https://github.com/kursadsaka/Phonograph/issues/9)

**Comment by soncaokim** [comment]
Is the root cause the fact that you have compilation album from multiple artists?

**Comment by mziehm** [comment]
Compilation albums are causing the problem on the artist level, but I also have various songs bought or downloaded individually e.g. through amazon download or provided by artists on their homepage or have the full album, but only store selected songs on my mobile. These "indidivudal" songs I then include in playlists (stored or adhoc created).
