### ISSUE TITLE
[Feature Request] ReplayGain support

### ISSUE THREAD

**Issue by AeliusSaionji** [AdrienPoupa/VinylMusicPlayer#31]
Hello!

Would you please implement support for replaygain?

This is the only feature I am missing from VinylMusicPlayer.

Thanks!

**Comment by evan-king** [comment]
@knacky34 implemented ReplayGain in his fork but Phonograph rejected it (refusing not just that contribution, but the feature entirely): https://github.com/kabouzeid/Phonograph/pull/574

Will Vinyl support collaborators and grow on its own or stick purely to vanilla upstream?

**Comment by GeoZac** [comment]
@evan-king The repo seems to be too dead.

**Comment by evan-king** [comment]
Oh good point.  That's a shame, considering this fork is already renamed and published.  Given that the latest Android update fixed Poweramp's notifications, it may be a moot point.  This UI is better, but functionality and maturity vastly outweigh the look and feel of a few screens one rarely ever has to actually use.

**Comment by AeliusSaionji** [comment]
I ended up installing foobar2000 because this is not a convenience feature, this is literally an imperative to my health. The difference in volume for some songs can and does hurt my ears, and it's just not safe to keep adjusting the volume while I'm driving.

Eagerly awaiting this PR, @knacky34

**Comment by knacky34** [comment]
Hi @AeliusSaionji I've released the [1.2.0-beta01](https://github.com/knacky34/Phonograph/releases/tag/v1.2.0-beta01) on my fork.

**Comment by AdrienPoupa** [comment]
Hi @evan-king ! That's awesome, i'm gonna test it and implement it if it works (y)

**Comment by AdrienPoupa** [comment]
@knacky34 actually if you could open a clean PR, i'll review and merge it asap :)

**Comment by knacky34** [comment]
@AdrienPoupa Ok I cleanup the code and create a PR very soon

**Comment by AdrienPoupa** [comment]
Implemented, thanks to @knacky34 for his hard work
