### ISSUE TITLE
Folder View completely empty

### ISSUE THREAD

**Issue by UltraBlackLinux** [AdrienPoupa/VinylMusicPlayer#310]
**Describe the bug**
The folder view displays nothing. 
Other views show the songs

**To Reproduce**
1. *folder view*

**Expected behavior**
### Show at least something

**Screenshots**
Screenshotting nothing is useless

**Smartphone (please complete the following information):**
 - Device: Razer Phone
 - Android Version: Android 10
 - ROM: LineageOS
 - Vinyl Music Player Version: 0.24.1

**Additional context**
Permissions are granted

**Comment by soncaokim** [comment]
Take one song visible in another view, click on three dots menu on right side of the song name, click Details.

Here you can see the path to the file containing the song.

Can you switch to the Folder view and navigate to the path shown, and confirm that you dont see the corresponding file?

**Comment by UltraBlackLinux** [comment]
I can confirm that. Its empty. Even rescanning tells me that there is nothing to scan.

**Comment by soncaokim** [comment]
Looks like this is related to Android 10 folder permissionning.

Can you please try following what I've suggested, and confirm that you cannot  to the folder that contains the songs (those that are visible int he other views)?

**Comment by UltraBlackLinux** [comment]
I. Already. Did. That.

**Comment by toniz4** [comment]
I'm having the same problem, downgrading to 0.23.1 fix this issue.

**Comment by soncaokim** [comment]
I cannot reproduce the issue with Vinyl version1.0, 
on Android 10, either with internal memory or a external sd card.

Note that with external sd card, one has to navigate out of the default folder /storage/emulated/0/... to a folder created by Android 10 for that card (ie /storage/XXXX-YYYY/....

Screenshots of the app and details on where the music files are located may help.

**Comment by toniz4** [comment]
It could be a problem with selinux? lineageos has selinux enforcing by default.

**Comment by soncaokim** [comment]
> It could be a problem with selinux? lineageos has selinux enforcing by default.

I dont think so, otherwise downgrading to previous app version would not fix that.

**Comment by UltraBlackLinux** [comment]
@toniz4 I change my selinux status to permissive everytime I restart my phone - another app needs it.

**Comment by UltraBlackLinux** [comment]
I don't know why, but its fixed. xD
