### ISSUE TITLE
Artist's names missing - all over the app

### ISSUE THREAD

**Issue by bungabunga** [AdrienPoupa/VinylMusicPlayer#311]
**Describe the bug**
I only started using this app recently so I don't know when this issue occured first time. On any list in the app there are no artist names present. Not even in the artist tab - there are song names listed there instead.

Music app from MaxFour and also Phonograph that are obviously based on similar core doesn't have this problem. Artist's names are well seen anywhere around.

**To Reproduce**
1. Open app
2. Try to spot some artist anywhere
3. They're never written anywhere

**Screenshots**
![artistsgone11](https://user-images.githubusercontent.com/2994878/95647527-6c37be80-0ad0-11eb-8c7d-7170d2fcfae4.png)
![artistsgone22](https://user-images.githubusercontent.com/2994878/95647530-6e9a1880-0ad0-11eb-91ad-cf1fed93998b.png)
![artistsgone33](https://user-images.githubusercontent.com/2994878/95647532-71950900-0ad0-11eb-88d0-d23bf18d7d04.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - Android Version: 11
 - ROM: GrapheneOS (a security hardened AOSP)
 - Vinyl Music Player Version: latest F-Droid

**Comment by tomaszg7** [comment]
Just installed the app and noticed the bug. Downgrading to 0.24.0 fixes the problem (although I couldn't downgrade without uninstalling first due to a "unknown error"). 

Seems the culprit is commit cf70332eccabda4cbd7a0c416c821282a309db57. The following line is obviously wrong:

String artist = tags.getFirst(FieldKey.TITLE);

**Comment by chillgamesh** [comment]
having the same issue. It appears the name of the first track in the album is being fetched instead of the artist name, but everything is normal when you actually look at the track info/tag editor.

**Comment by soncaokim** [comment]
Hi, this should be already fixed in master via https://github.com/AdrienPoupa/VinylMusicPlayer/commit/8a27c4b5b7046cd9595d967760651eb6bb10986d

**Comment by keforbes** [comment]
Can you push out a new release with this fix?  The defect is incredibly annoying and there is no workaround.

**Comment by aoloe** [comment]
Please keep this ticket open until the new release is pushed to f-droid.

The bug makes vinyl almost unusable and I won't be the last one coming here to see if "it's only me" and if there are workarounds (downgrading after uninstalling worked for me)

**Comment by AdrienPoupa** [comment]
1.0.0 fixes it.

I have zero control over F-Droid build system, so it will get there when it does.

**Comment by keforbes** [comment]
F-Droid has updated with version 1.0.0 and it works great, thanks!
