### ISSUE TITLE
High battery usage in Android 11

### ISSUE THREAD

**Issue by lufazim** [AdrienPoupa/VinylMusicPlayer#312]
On my new Pixel 4a with Android 11, the app drains the battery really fast (like 1% per every 2-3min of playback).
The problem doesn't occur with other music players (eg. vlc or shuttle+).
Is anyone else experiencing something similar?

**Comment by Alfonsorb** [comment]
I also have this issue. Vinyl has been my most draining app, with android telling me to force stop it almost every hour.

**Comment by lufazim** [comment]
Version 1.0 fixed the battery draining for me.
