### ISSUE TITLE
Being able to move the current song playing in the playing queue

### ISSUE THREAD

**Issue by Tom4tot** [AdrienPoupa/VinylMusicPlayer#318]
Hello,

Thanks for the latest great updates.

I'm almost entirely satisfied with this music player, especially sine you added the possibility to swipe songs to delete them the playing queue (https://github.com/AdrienPoupa/VinylMusicPlayer/releases/tag/0.20.0)

However, unlike Phonograph for example, it's not possible anymore to change the position in the queue of the song playing. I think it'd be nice to get this back. The main purpose is to move the song in the playlist instead of deleting all the songs you don't want to listen to. For people with big library it happens quite often that you want to skip 4-5 songs or even more. It's way quicker to move the current song instead of deleting all the undesired songs.

If it's not too hard to change this, it would be great. Thanks in advance. :)

**Comment by opale95** [comment]
#223
