### ISSUE TITLE
[Feature Request] Sort album first by artist name then by album name

### ISSUE THREAD

**Issue by buche** [AdrienPoupa/VinylMusicPlayer#32]
Hello,

a few days ago I found this player on F-Droid and I like it. Thanks for maintaining! But one issue prevents me from using it as my standard player:

I'm used to have my albums sorted by artist name first because that's the way I'm looking for an album. Often I don't know the name of the album, but the artist name and some visual info from the cover like "this one with the red cover". With albums sorted by album name I'm lost in my list of ~1000 albums.

Using the artist tab is not an option to me, because here covers are only visible per artist. I can't scroll through all covers at once.

I would prefer an user defined option (setting in preferences) for sorting the album list. Possible options: "Album name only (standard)", "Artist name / album name", "Artist name / album year", ...

Thanks for your effort!

**Comment by AdrienPoupa** [comment]
Hi, have you seen the latest version with the sorting feature? It might not be exactly what you're looking for but it should help

**Comment by buche** [comment]
Thanks for the information. I will have a look at it when the new version is available on F-Droid.
