### ISSUE TITLE
Artist category replaced with song name.

### ISSUE THREAD

**Issue by anarchotaoist** [AdrienPoupa/VinylMusicPlayer#322]
**Describe the bug**
Artist category looses both artist name and images and is replaced with the first song name in the first album of that artist.

**To Reproduce**
1. Artist view is as expected.
2. Exit app: close or switch to another app
3. Open app and artist name is replaced
4. Reinstall app and view is as expected
5. Close out app and behaviour repeats.

**Expected behavior**
The Artist view retains artist name and artist image.

**Smartphone (please complete the following information):**
 - Device: Oneplus 5T
 - Android Version: 9
 - ROM: LineageOS for Microg
 - Vinyl Music Player Version: 0.24.1

**Additional context**
Uninstalling and installing version 0.24.0 (downgrading) returns view to expected behaviour suggesting the issue may be with version 0.24.1.

**Comment by AdrienPoupa** [comment]
This is fixed in 1.0.0
