### ISSUE TITLE
[Bug] Track name dispayed instead of Artist

### ISSUE THREAD

**Issue by ner0-m** [AdrienPoupa/VinylMusicPlayer#324]
**Describe the bug**
In the artist tab, the first track of each artist is displayed instead of the artist name (see screenshot 1) However, the grouping is still by the correct artist. Also if I select any track, the name of the track name is displayed as the artist (see screenshot 2)

**Expected behavior**
Artist names are displayed correctly, not the track name.

**Screenshots**

<details>
  <summary>Screenshots 1</summary>
  
![Screenshot_20201018-171921_Vinyl_Music_Player](https://user-images.githubusercontent.com/8257844/96372234-482a4c00-1166-11eb-9103-a236fcdbc3a6.png)
</details>

<details>
  <summary>Screenshots 2</summary>

Here it should display `ATP` as the artist

![Screenshot_20201018-171950_Vinyl_Music_Player](https://user-images.githubusercontent.com/8257844/96372237-495b7900-1166-11eb-8757-8afba2debbff.png)
</details>
  

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy 8+ (SM-G955F)
 - Android Version: 10
 - ROM: LineageOS 17.1 with September updates
 - Vinyl Music Player Version: 0.24.1

**Additional context**
The problem first occurred after the last update I did of Vinyl this morning. I sadly don't remember what version I was no before..

If there is anything more you need, just let me know

EDIT: It works with 0.24.0

Device info:
---
<table>
<tr><td>App version</td><td>0.24.1</td></tr>
<tr><td>App version code</td><td>170</td></tr>
<tr><td>Android build version</td><td>eng.build.20200915.020744</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>lineage_dream2lte-userdebug 10 QQ3A.200805.001 eng.build.20200915.020744 test-keys</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>dream2lte</td></tr>
<tr><td>Device model</td><td>SM-G955F</td></tr>
<tr><td>Device product name</td><td>dream2ltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos8895</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by AdrienPoupa** [comment]
This is fixed in 1.0.0
