### ISSUE TITLE
Changelog for 1.0 was an empty popup

### ISSUE THREAD

**Issue by Porkepix** [AdrienPoupa/VinylMusicPlayer#326]
**Describe the bug**
This is probably just because there was nothing filed as a changelog within, but I report just in case there really was an issue

**To Reproduce**
1. Open the application after updating it to 1.0
2. See the popup

**Expected behavior**
There should either be no Changelog popup, or it should have content

**Screenshots**

![Screenshot_20201019-094701_crop](https://user-images.githubusercontent.com/709500/96469554-a3734180-122d-11eb-8057-0828cea3371a.png)

**Smartphone (please complete the following information):**
 - Device: Sony Xperia Z3 Compact
 - Android Version: 6.0.1
 - ROM: Manufacturer's
 - Vinyl Music Player Version: 1.0

**Comment by AdrienPoupa** [comment]
I noticed that too and tried to fix it with no luck. The changelog file is read successfully, but does not display. I suspect an issue with the material library but could not confirm it

**Comment by soncaokim** [comment]
This is it

https://stackoverflow.com/questions/58061708/webview-targeting-29-not-showing-content

**Comment by soncaokim** [comment]
This is it

https://stackoverflow.com/questions/58061708/webview-targeting-29-not-showing-content
