### ISSUE TITLE
Names creating albums

### ISSUE THREAD

**Issue by Asmosnos** [AdrienPoupa/VinylMusicPlayer#331]
The recent update messed up a lot of my albums featuring multiple artists, splitting the songs from the main album and creating "dummy" albums exclusive to the artist. 

-

Device info:
---
<table>
<tr><td>App version</td><td>1.0.0</td></tr>
<tr><td>App version code</td><td>172</td></tr>
<tr><td>Android build version</td><td>G970USQU4ETH7</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QP1A.190711.020.G970USQU4ETH7</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>beyond0q</td></tr>
<tr><td>Device model</td><td>SM-G970U</td></tr>
<tr><td>Device product name</td><td>beyond0qltesq</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by Knusper** [comment]
I can confirm this bug.  I have a lot of albums with multiple artists (compilations).  The album view now became a mess.  I also tried clearing cache and storage, and doing a new scan, but I arrive at the same messed up album view.   Only solution for me to have the player usable is to downgrade to 0.24.1

**Comment by soncaokim** [comment]
Should be the same as https://github.com/AdrienPoupa/VinylMusicPlayer/issues/323.
