### ISSUE TITLE
Songs arent added to playlists

### ISSUE THREAD

**Issue by InsectOverlord** [AdrienPoupa/VinylMusicPlayer#333]
Songs either Favorited or added manually to a created playlist aren't added.
Tried closing, refreshing, re-favoriting, etc. No luck.

**Comment by soncaokim** [comment]
- Are you on Android 10?
- Are the tracks stored on a SD card?

**Comment by InsectOverlord** [comment]
I'm on Android 10. All files on phones HD. No external storage. (Note 9)

**Comment by Octoton** [comment]
Same problem on android 11

**Comment by Octoton** [comment]
It seems that for me the problem is only that i need to stop the app and re-open it to see the change

**Comment by cauerego** [comment]
isn't this the same as #248 as well?

**Comment by RastalDev** [comment]
For me, same issue, can replicate the bug on Android 10, tracks on SD card. Vinyl version 1.0.0 (F-droid)

**Comment by soncaokim** [comment]
Same as https://github.com/AdrienPoupa/VinylMusicPlayer/issues/248
