### ISSUE TITLE
very slow on a fresh install

### ISSUE THREAD

**Issue by cauerego** [AdrienPoupa/VinylMusicPlayer#334]
following #293 (just tested it again today, still same issue for me).

**Describe the bug**
brand new fresh install.

it takes about 5 seconds to load, almost every time i open the main screen.

**To Reproduce**
1. install it from zero
1. get 100gb of songs
1. open the app
1. go to settings or remove from recent apps
1. get back to the main landing screen

**Expected behavior**
it should be as fast as max four https://github.com/MaxFour/Music-Player/issues/87#issuecomment-698898223

**Screenshots**
i hope there's no need.

**Smartphone (please complete the following information):**
 - Device: nokia 7.2
 - Android Version: 10
 - ROM: stock
 - Vinyl Music Player Version: 0.24.1

**Additional context**
everything else seem to work about the same as maxfour... including the same issues https://github.com/MaxFour/Music-Player/issues/88

**Comment by cauerego** [comment]
still same issue on 1.0.0

except now the app also crashes a lot more!

i also just tested phonograph 1.3.5 and it's as fast as maxfour... (with the same playlist issue already mentioned).

**Comment by tomaszg7** [comment]
I don't have that much music on my phone, but I also notice that it is very slow to start. I see many "App not responding" messages and it won't play anything for quite a time. Afterwards it seems to work fine (no crashes for me). 

I'm using HTC Desire 12+ with Android 8.
