### ISSUE TITLE
Tags are not properly supported in opus files

### ISSUE THREAD

**Issue by ChrisMrX** [AdrienPoupa/VinylMusicPlayer#338]
**Describe the bug**
Tags are not properly supported in opus files. (unread, unwritten)

**Smartphone (please complete the following information):**
 - Device: realme 5 Pro
 - Android Version: 10
 - ROM: Stock
 - Vinyl Music Player Version: 1.0.0

**Comment by tomaszg7** [comment]
Can you even open Opus files? It doesn't work for me at all. Does it depend on Android version? I have only version 8.

**Comment by f1reflyyyylmao** [comment]
As far as I know .opus is only supported when the file extension is .ogg (https://developer.android.com/guide/topics/media/media-formats). Metadata is sometimes broken in my experience, google doesn't seem to be interested in supporting opus as standalone audio format for music libraries.

**Comment by tomaszg7** [comment]
This link is talking about containers, not extensions. Usual Opus files are using Ogg container, so there is no problem here. Changing extensions might only be a trick to workaround broken players.

**Comment by ChrisMrX** [comment]
Android 10 (API 29): Support for the AV1 video codec, the HDR10+ video format and the Opus audio codec.
([https://en.wikipedia.org/wiki/Android_version_history#cite_note-introducingqbeta-256](url))

**Comment by animaldaydream** [comment]
If I'm not mistaken, Opus files are usually stored in Ogg containers (usually with the .opus extension which is supported in Android 10, and with the .ogg extension since Nougat) and so they use Vorbis Comments as tags, not ID3.

I don't think any of the usual audio taggers will let you write ID3 tags to Ogg containers. But they do write the tags.

**Comment by GermanGospel** [comment]
> If I'm not mistaken, Opus files are usually stored in Ogg containers (usually with the .opus extension which is supported in Android 10, and with the .ogg extension since Nougat) and so they use Vorbis Comments as tags, not ID3.

@animaldaydream - If use NewPipe [1] to save the audio of a YouTube video as opus audio file, the extension is ".opus". Vinyl does not show any tag information for these files.

[1] https://github.com/TeamNewPipe/NewPipe

**Comment by ChrisMrX** [comment]
> 
> 
> If I'm not mistaken, Opus files are usually stored in Ogg containers (usually with the .opus extension which is supported in Android 10, and with the .ogg extension since Nougat) and so they use Vorbis Comments as tags, not ID3.
> 
> I don't think any of the usual audio taggers will let you write ID3 tags to Ogg containers. But they do write the tags.

Sorry for the mistake, the metadata container used in Opus file is Vorbis comment. I correct.

**Comment by animaldaydream** [comment]
> If I use NewPipe [1] to save the audio of a YouTube video as opus audio file, the file extension is ".opus". Vinyl does not show any tag information for these files.

Yeah, but even when they're .opus, internally the container is still Ogg. Did you try renaming them to .ogg? I can't test it, I'm on Android 11 and it's a custom rom so I have no issues.
