### ISSUE TITLE
Songs remain in the album detail list after being deleted

### ISSUE THREAD

**Issue by Iislsdum** [AdrienPoupa/VinylMusicPlayer#339]
**Describe the bug**

**To Reproduce**
1. In the library, go to the albums tab and select an album
2. Tap the vertical elipses beside one of the songs to open the menu
3. Select "Delete from device"
4. Tap Delete
5. The song that was just deleted remains in the list.

The same thing happens when selecting multiple songs and using the menu in the upper right to delete them.

**Expected behavior**
The songs that were deleted disappear from the list.

**Smartphone:**
 - Device: OnePlus 6
 - Android Version: 10
 - ROM: Stock (OxygenOS 10.3.6)
 - Vinyl Music Player Version: 1.0.0

**Additional context**
After the song is deleted, the cache is refreshed from the database:
https://github.com/AdrienPoupa/VinylMusicPlayer/blob/f5865a664843963cc506fe264a1d151a9266d491/app/src/main/java/com/poupa/vinylmusicplayer/discog/Discography.java#L244-L247

and the list is reloaded from the cache:
https://github.com/AdrienPoupa/VinylMusicPlayer/blob/f5865a664843963cc506fe264a1d151a9266d491/app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/AlbumDetailActivity.java#L405-L409

These both happen asynchronously, so the UI tends to get its list of songs (including the ones that were just deleted) while Discography is still waiting for results from the database to update the cache with.

**Comment by Iislsdum** [comment]
I can submit a pull request fixing this issue if I can get some input from regular contributors on what the solution should be. I would implement a cache invalidation mechanism for Discography's `MemCache`, but if the regular contributors have other ideas, I can code those up, too. Thoughts?

**Comment by soncaokim** [comment]
Hi, if this is due to the MemCache (your exploration points that way), I would explore this as well.

Thanks

Son

**Comment by soncaokim** [comment]
> I can submit a pull request fixing this issue if I can get some input from regular contributors on what the solution should be. I would implement a cache invalidation mechanism for Discography's `MemCache`, but if the regular contributors have other ideas, I can code those up, too. Thoughts?

Have you made any progress on this? Thanks

**Comment by Iislsdum** [comment]
@soncaokim I haven't started, but I'll see what I can get done by tomorrow night.

**Comment by Iislsdum** [comment]
@soncaokim The cache invalidation route turned out to be more complex than I had envisioned. Instead, I have reused the method already in place to notify the main activity of changes to Discography. Please take a look at #343. If you like what you see, I'll implement the same for the artist, genre, and playlist detail activities.
