### ISSUE TITLE
Amazing FAQ created by me for VinylMusicPlqyer

### ISSUE THREAD

**Issue by yhaulez** [AdrienPoupa/VinylMusicPlayer#34]
Am I music freak and I have been using lots of music players and I came across your project of recent.  It's really lovely when it comes to the queue and playlist. 
And I love the fact that I could actually customize the whole app appearance and I would give a thumbs up for Vinyl Music Player is really user friendly and lovely. 
 But it came to my notice that there wasn't a FAQ on the android application for users to help them discover the essence and need for the application. 
So I went ahead and created a very informative FAQ for the application. 

Including a FAQ on the the application will enlighten users and draw more users, encouraging them to use the application for its diverse purposes.

Here is a link to the FAQ
https://drive.google.com/file/d/174UgCv8qmJFvh-fvqzJ1W3oX8g6Ls4AT/view?usp=drivesdk

Please review and merge it. 
I would welcome corrections and please remember to merge it if you love it. 
Thank you.

**Comment by Rygle** [comment]
You could add the bug and workaround about the two dots that allow you to go up a level when blocking folders.

There is a bug report in for this in the phonograph app that vinyl is forked from.

https://github.com/kabouzeid/Phonograph/issues/475

**Comment by Rygle** [comment]
I mentioned a workaround. It's described in the bug report. That's what I was thinking should go in the FAQ.

**Comment by yhaulez** [comment]
Okay would do that right away

**Comment by yhaulez** [comment]
Here is the updated document with the FAQ and I included the work around you asked me to include. 
https://docs.google.com/document/d/1J35KPYLxfXTH6NMoTRfvnQMZieCHkGaB8GxwMCoNdUM/edit?usp=drivesdk

**Comment by GeoZac** [comment]
@yhaulez Maybe add the reason for the origin of Vinyl Music Player,and add credits to  the original developers

**Comment by yhaulez** [comment]
@geozac is a FAQ (frequently asked questions) not About Us. If i add such it would not look professional. 

@Rygle I believe you solved the issue when you made the workaround and I believe it should still be in the FAQ so as to help those you don't get to see it on the github.

**Comment by AdrienPoupa** [comment]
Hi, thanks for your contribution!

Can you use the [wiki](https://github.com/AdrienPoupa/VinylMusicPlayer/wiki/FAQ) for that instead? Thanks!
