### ISSUE TITLE
Album sorting options in artist activity

### ISSUE THREAD

**Issue by tguen** [AdrienPoupa/VinylMusicPlayer#341]
When selecting an artist, it opens an activity that shows all albums by that artist. Before v1.0, albums were sorted in reverse-chronological order. In v1.0, they are sorted in chronological order. I preferred the way it was, and I'd like an option to change the album sorting similar to how I can in the main activity.

**Comment by soncaokim** [comment]
> I preferred the way it was, 

The PR #344 proposes a fix for the regression (sorry for that)

> and I'd like an option to change the album sorting similar to how I can in the main activity.

This is conceivable but not done, at least for now
