### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [AdrienPoupa/VinylMusicPlayer#346]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by AdrienPoupa** [comment]
Feel free to open a PR for that ;)

**Comment by mondlicht-und-sterne** [comment]
The topic of PR and merge is too difficult
for me. You can, if you use Fastlane, just
add screenshots to make your app view more
beautiful. If not, then it stays dry like
that. So it was just a hint that more can
be displayed - if desired.
