### ISSUE TITLE
The application crashes when I like a song using Android Auto

### ISSUE THREAD

**Issue by bcroq** [AdrienPoupa/VinylMusicPlayer#348]
**Describe the bug**

The application crashes when I like a song using Android Auto

**To Reproduce**
1. Use Android Auto
2. Play a song
3. Like this song by clicking on the heart on the Android Auto screen

**Expected behavior**

No crash ;-)

**Smartphone (please complete the following information):**
 - Device: Nokia 6.1
 - Android Version: 10 (00WW_4_16D)
 - Vinyl Music Player Version: 1.0.0 (172)

**Additional context**

It doesn't crash when I like a song in Vinyl on the phone.

**Comment by soncaokim** [comment]
This should be a problem any more with recent 1.1.x changes. When they are released, I'll close this bug report.

**Comment by GermanGospel** [comment]
@bcroq - I installed Vinyl 1.1.1 via F-Droid and activated the developer options in the Android Auto app to allow "Unknown Sources". The bug you described is fixed! :-)

**Comment by GermanGospel** [comment]
This bug is fixed in version 1.1.2 (available via Google Play Store): https://github.com/AdrienPoupa/VinylMusicPlayer/issues/376#issuecomment-796471789

**Comment by GermanGospel** [comment]
@bcroq - This bug is fixed in version 1.1.2 (available via Google Play Store): #375
