### ISSUE TITLE
Integrating .m4a codec

### ISSUE THREAD

**Issue by PetersProblem** [AdrienPoupa/VinylMusicPlayer#353]
It would be great, if a .m4a codec could be integrated, so that these files could be played.

**Comment by ChrisMrX** [comment]
MPEG-4 is a container (https://en.wikipedia.org/wiki/MPEG-4_Part_14). Audio-only MP4 files generally have a .m4a extension. The audio codec usually embedded is AAC (https://en.wikipedia.org/wiki/Advanced_Audio_Coding).
Vinyl Music Player (1.0.0) work correctly with AAC codec in my Android 10 phone !
