### ISSUE TITLE
Ignore "The" in sorting artists

### ISSUE THREAD

**Issue by aselker** [AdrienPoupa/VinylMusicPlayer#366]
In the "Artists" tab, artists are sorted alphabetically.  A leading "The" is included, so The Who will come just before Thom Yorke. 

Since so many bands have "The" in their names, many music players ignore it; The Who would go in the W's, not the T's.  It seems that Vinyl does this for songs, putting The Sounds of Silence in the S section.  It would be nice to do this for artist names, too.

If some folks don't want this, maybe it ought to be an option in Settings?

(It's possible that this has been talked about; it's really hard to Google, so I hope this isn't unnecessary!)

**Comment by soncaokim** [comment]
The best way is to rely on song/album/artist sorting tags (TSO* tags), to retain the compatibility with other music players.

**Comment by animaldaydream** [comment]
I agree that this is an useful feature, but it should be optional.

There's no reliable way to sort out which words should be ignored on all languages! The only proper way out is figuring it out in a case-by-case basis. MusicBrainz does some of this work for us on the relevant "sort" tags but it only sorts the artist names.

So there's no good compromise. Giving us the option to either sort by special sorting tags, automatically sort certain predefined words, or just do regular alphabetical sorting would be the way to go.
