### ISSUE TITLE
Android Auto/Play Store submission issue

### ISSUE THREAD

**Issue by soncaokim** [AdrienPoupa/VinylMusicPlayer#376]
> Submission of version 1.1.0 to the Play Store got rejected due to Android Auto issues.
> That's what it says:
>> Voice commands
>> Your app does not support all of the required voice commands. You can read more about how to support Voice Actions in the Android Developers Help Center.
>> For example, your app recognizes the voice command, but does not start the requested track in the Android Auto environment

**Comment by soncaokim** [comment]
By faking an intent, I've triggered the corresponding rewritten code in SearchQueryHelper. I've not noticed anything abnormal.
Do you have more details on the PlayStore expectations?

**Comment by soncaokim** [comment]
I've managed to make on-device Auto to recognise the development version of Vinyl.
Here comes the first fixes proposed for Auto -> https://github.com/AdrienPoupa/VinylMusicPlayer/pull/377

I've found nothing relevant to search for now.

**Comment by GermanGospel** [comment]
> I've managed to make on-device Auto to recognise the development version of Vinyl.
Which Vinyl app version? app_version_name=1.1.1 from F-Droid is not showing up in the Android Auto app. I switched back to version 1.0.0 from Play Store and now Vinyl is listed again as a media player in the AA app.

**Comment by GermanGospel** [comment]
> I've managed to make on-device Auto to recognise the development version of Vinyl.

@soncaokim Which Vinyl app version? app_version_name=1.1.1 from F-Droid is not showing up in the Android Auto app. I switched back to version 1.0.0 from Play Store and now Vinyl is listed again as a media player in the AA app.

**Comment by soncaokim** [comment]
My guess: Auto is not recognising apps that are not signed by PlayStore. You can circumvent this (enable developer mode in Auto) but this is obviously not recommended.

If I'm not wrong, Adrien is trying to push the latest changes to PlayStore. So the safer bet would be to wait for this to get through.

**Comment by AdrienPoupa** [comment]
Based on the rejection message, I assume we needed to implement `onPlayFromSearch` which I roughly did here: https://github.com/AdrienPoupa/VinylMusicPlayer/commit/73f95d5496197d165de2ce26b557802d1c4e3bf6

based on this https://developer.android.com/guide/topics/media-apps/interacting-with-assistant#java

I submitted 1.1.2, we will see if this is enough

**Comment by AdrienPoupa** [comment]
It passed! 🎉

**Comment by GermanGospel** [comment]
@AdrienPoupa - I see 1.1.2 in PlayStore but the changelog only lists changes up to 1.1.0! ;-) Maybe automate the generation of the changelog text for the PlayStore?

**Comment by AdrienPoupa** [comment]
Yes, that would be really nice indeed!
