### ISSUE TITLE
Album Art is cut off

### ISSUE THREAD

**Issue by utack** [AdrienPoupa/VinylMusicPlayer#38]
Hi,
unfortunately in the newest version 0.17.0 (from F-Droid) the Album art it provides to the system is cut off
![1](https://user-images.githubusercontent.com/8551234/39672330-b2d8c532-5128-11e8-9ac2-605acff0151a.png)

This does not happen when I tick the "blur album art" option:
![2](https://user-images.githubusercontent.com/8551234/39672333-b684ffde-5128-11e8-8aac-c270914dbe30.png)

I also tried it with Phonograph 1.0.0 from Play Store, and there it does not happen.
Hopefully between comparison to 0.16.5.2 and Phonograph you can quickly narrow down where it started.

Thank you for looking into it!

**Comment by AdrienPoupa** [comment]
Hi,

Thanks for the report! That must be coming from the Glide 4 upgrade, I'll have a look

**Comment by utack** [comment]
This a gerneric Music Widget:  
https://play.google.com/store/apps/details?id=com.jackthakar.musicwidget&hl=en_US  
In an ancient version (that is why it looks different)

**Comment by utack** [comment]
Thank you for fixing it so quickly 👍
