### ISSUE TITLE
Can't sort files on latest fdriod build.

### ISSUE THREAD

**Issue by Ramton03** [AdrienPoupa/VinylMusicPlayer#380]
**Describe the bug**
On version 1.0.0 it was working fine but now i can't sort.I downgraded and it's working again.

**Screenshots**
<a href="https://ibb.co/NNPsnVN"><img src="https://i.ibb.co/YdM3TRd/IMG-20210228-225205.jpg" alt="IMG-20210228-225205" border="0"></a>
<a href="https://ibb.co/LRwPSYn"><img src="https://i.ibb.co/SyTxN5R/IMG-20210228-225152.jpg" alt="IMG-20210228-225152" border="0"></a>
<a href="https://ibb.co/n7jRF9P"><img src="https://i.ibb.co/5rL2PmK/IMG-20210228-225130.jpg" alt="IMG-20210228-225130" border="0"></a>

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi 5
 - Android Version: 10.0
 - ROM: Resurrection Remix
 - Vinyl Music Player Version:1.1.1

**Comment by soncaokim** [comment]
Oops
