### ISSUE TITLE
Playlist sorting not working anymore

### ISSUE THREAD

**Issue by EBiForE** [AdrienPoupa/VinylMusicPlayer#385]
Device info:
---
<table>
<tr><td>App version</td><td>1.1.1</td></tr>
<tr><td>App version code</td><td>174</td></tr>
<tr><td>Android build version</td><td>V12.0.2.0.QFKMIXM</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QKQ1.190825.002 test-keys</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>raphael</td></tr>
<tr><td>Device model</td><td>Mi 9T Pro</td></tr>
<tr><td>Device product name</td><td>raphael</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by soncaokim** [comment]
Hi,

Can you please describe further what is the regression and the expected behaviour?
If possible, what is the last version when the app reacted as expected?

Thanks

Son

**Comment by soncaokim** [comment]
Closing this for now - dont hesitate to reopen with more information
