### ISSUE TITLE
Menu button is "invisible"

### ISSUE THREAD

**Issue by HardCode4All** [AdrienPoupa/VinylMusicPlayer#39]
Sometimes, the Menu-button (the 3 dots next to the Favorite-button) is displayed in black in the Black (AMOLED) theme. This makes it very hard to see.

![screenshot_2018-05-07-00-12-07](https://user-images.githubusercontent.com/38424724/39690706-55207396-51db-11e8-80ab-581e56bf41c9.png)

Doesn't happen always though...

Update (9 days later): but most of the times :(

**Comment by HardCode4All** [comment]
Is this app still being developed? It is so silent here... :(

**Comment by GeoZac** [comment]
@HardCode4All Seems so

**Comment by AdrienPoupa** [comment]
I've never been able to reproduce it

**Comment by HardCode4All** [comment]
I found out how to reproduce this on my Samsung S5 Mini with Android 6: The dots are white as long as I am in Library-View. As soon as I switch to Folder-view and then swipe up to see the currently plaing sond, the dots are always black (in v0.20.0 as the 0.20.2 is still not available in F-Droid :( )

**Comment by AdrienPoupa** [comment]
OK, weird. I can't reproduce it with Android 9

**Comment by HardCode4All** [comment]
Dang! An I cannot install a newer Android on that old phone. Sad :(
