### ISSUE TITLE
ID3v11: Metadata not read resulting in huge list of Unknown Artists

### ISSUE THREAD

**Issue by Kreuger** [AdrienPoupa/VinylMusicPlayer#398]
Hey just found Vinyl recently after using Phonograph for a bit. However the app doesnt seem to read the metadata from a lot of my mp3s resulting in them being put under the Unknown Artist category. Is there a way to firce the app to read the info from ID3 tags or the file name? I dont wanna have to manually edit over 300 songs.

**Comment by soncaokim** [comment]
I take that there a tracks that are correctly classified? Do you spot any common pattern among the missing ones?

If you open the tag editor for a track that are incorrectly classified, does the in-app tag editor show expected info?

**Comment by Kreuger** [comment]
Yes actually there is a pattern. All of the songs have a track number in the file name. There is no info at all when opening the tag editor.

**Comment by soncaokim** [comment]
The file name itself should not matter. If there is nothing shown on the tag editor, I guess the file format is not recognised/supported. 

Are the files being of the same encoding, and if yes, what would that be please?

Are they correctly supported on Phonograph?

**Comment by soncaokim** [comment]
For debugging purpose, do you mind posting a copy of a MP3 so that I can have a look? If possible, please share what is the expected artist info.

**Comment by Kreuger** [comment]
I dont know how it will go with copyrighted material.

https://u.pcloud.link/publink/show?code=XZxRfWXZs2nptc0XtKVYYvcrcgn58bn4PPzV

Artist: Our Lady Peace
Song: All For You
Album: Gravity
Track #1

**Comment by soncaokim** [comment]
Looks like the MP3 is tagged with ID3v11 tags.
I've updated the issue title.

For immediate result, I'd suggest you to upgrade the ID3 tagging

**Comment by Kreuger** [comment]
It would be easier just to switch back to phonograph.

**Comment by soncaokim** [comment]
Your call obviously.

Fyi I'm prepping a fix nevertheless to provide a compat for ID3v1, to at least evade the regression.

**Comment by Kreuger** [comment]
I appreciate the effort.

**Comment by AdrienPoupa** [comment]
Thanks for the help/feedback guys!
