### ISSUE TITLE
Artwork changes reversed

### ISSUE THREAD

**Issue by Bambina93** [AdrienPoupa/VinylMusicPlayer#399]
Hello! I've recently been downloaded the app and fell in love with it. Sadly, I've noticed that whenever I change the Artist Images, after a while it changes back to how it was before.

I can't keep changing the images again and again, it's really frustrating. I wish I could show you a screen recording of this bug, but it doesn't happen on a regular basis. Sometimes the images I chose are still there, sometimes they are not.

 - Device: Motorola One Fusion
 - Android Version: 10
 - ROM: Stock
 - Vinyl Music Player Version: 1.1.2

**Comment by PrivacyFriendlyMuffins** [comment]
The same thing just happened within the last hour for me.

**Device**: Motorola One 5G Ace
**Android Version**: 11
**ROM**: Stock
**App Version**: 1.11.0
