### ISSUE TITLE
Some album art is only shown in the tag editor, not the player

### ISSUE THREAD

**Issue by jordannewport** [AdrienPoupa/VinylMusicPlayer#405]
**Describe the bug**
I have many albums to which I have manually added album art (the specific command I have used on my Linux command line is `metaflac --import-picture-from <image file> <flac file>`). For most of these (17/20), it works fine, and I can see the album art everywhere I see a song from the album, or the full album. However, I have a few albums (3/20) where the album art is only visible in the album tag editor. It's not visible when I look at the album, or play songs from it, only when I open the album tag editor. I don't know why it's these albums in particular; I can't really find any distinguishing features between albums that work and albums that don't. I think it's particular to the songs, rather than the images; I tried one album with a different image and it still was not visible.

**To Reproduce**
1. Add metadata to FLAC files (`mpv` on my command line displays the album art correctly).
2. Load the FLAC files onto your phone
3. Open Vinyl and look at album; the album art is not visible
4. Navigate to the album's tag editor (select album, open menu, tap "Tag editor"); art is now visible

I can't attach the file that causes the bug, since Github apparently doesn't like FLACs. I have uploaded a song that causes the bug, along with the image that I attached to it, to https://jnewport.dev/included-files/bug-report/13%20-%20Little%20Bag%20of%20Gloom.flac and https://jnewport.dev/included-files/bug-report/mm-4wd.jpg respectively. I unfortunately don't have a separate version of the file without the art attached. Fingers crossed this doesn't somehow end up DMCA'd.

**Expected behavior**
Album art should be visible on all screens for all albums.

**Smartphone (please complete the following information):**
 - Device: Motorola moto Z4
 - Android Version: 10
 - ROM: Stock
 - Vinyl Music Player Version: 1.1.2 (F-Droid)

**Comment by soncaokim** [comment]
this is weird, I can reproduce the issue on real device, but not on the debug emulator.

**Comment by soncaokim** [comment]
I assume that you have, in the Settings, "Ignore MediaStore cover" disabled?
If this is the case, can you enable that and report back?

I'm suspecting an issue with the way MediaStore extract/report the album art. Having the mentioned option enabled makes the app ignoring MediaStore (with the penalty of extracting the album art each time, cf the description associated with the option in the Settings screen).

**Comment by jordannewport** [comment]
Yes, it works when I turn on that option (although it does load notably slower, as you mentioned).

**Comment by soncaokim** [comment]
I'm closing this bug for now.
