### ISSUE TITLE
Add opus support

### ISSUE THREAD

**Issue by LoveChocoCat** [AdrienPoupa/VinylMusicPlayer#412]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the app can't see and play opus file.

**Describe the solution you'd like**
I want this app to be able to read and play opus file. Please take some codec from other sources and put it in the app.

**Describe alternatives you've considered**
If integrating a codec into the app is difficult, just make add on like what MiX explorer do.

**Additional context**
![Screenshot_2021-04-11-16-33-53-196_com poupa vinylmusicplayer](https://user-images.githubusercontent.com/37618453/114299095-c21f0a80-9ae3-11eb-81c3-695c59a5e91e.jpg)
This is a screenshot where i put some opus files. The app can't detect and play them.

**Comment by tguen** [comment]
Works for me. What version of Android do you have? According to [Wikipedia](https://en.wikipedia.org/wiki/Opus_%28audio_format%29#Operating_system_support), full support for opus was only added in Android 10.

**Comment by GHolk** [comment]
I change the suffix from opus to ogg, then vinyl and most music player can play them.

**Comment by GermanGospel** [comment]
@GHolk Maybe the app can be modified to interprete *.opus files as *.ogg files? Your manual workaround is working. An automated workaround should also work! ;-)

**Comment by f1reflyyyylmao** [comment]
Adding to this: Opus encoded audio files work fine, but the android media scanner supports only basic fields. Here is a full ffprobe dump of a music file I tagged with data from musicbrainz:

```
ffprobe version n4.4 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[ogg @ 0x55aefd0a9440] 4520 bytes of comment header remain
Input #0, ogg, from '/data/Musik/Converted/Beyond the Black/Horizons/01 Horizons.ogg':
  Duration: 00:05:00.79, start: 0.000000, bitrate: 100 kb/s
  Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      ISRC            : DEUM71906551
      BARCODE         : 602508339929
      AUTHOR          : David Levy, Jennifer Haben, Hartmut Krech, Mark Nissen
      ACOUSTID_FINGERPRINT: AQADtIkUKWIiC0-UOcXNokFtHMePZxX-OXiO5gzRHzd-PAd-9Mfxw29x6AouIcyLZ0_wPMEPX3h_fLiO6fiR_pDSHPF53AdeYzf6F44e_JgSF_khXbywM0Ef5Qid4QneWQiTU-iLG7qoo9_R1LjQ3OjCHL-HUndgMUePF0-L78EV5uh17MIbfMqhi4ef6SiuHcdRUOcha8vRf-hDUJeOgKKKkprxDznDo_lR3ngUQqO0o8lTgmuGS5mF_5jFo3e
      ACOUSTID_ID     : 7f7ab818-9264-4468-8807-210d983233c2
      ALBUM           : Hørizøns
      ALBUM ARTIST    : Beyond the Black
      album_artist    : Beyond the Black
      ALBUMARTIST_CREDIT: Beyond the Black
      ALBUMARTISTSORT : Beyond the Black
      RELEASESTATUS   : Official
      MUSICBRAINZ_ALBUMSTATUS: Official
      RELEASETYPE     : album
      MUSICBRAINZ_ALBUMTYPE: album
      ARTIST          : Beyond the Black
      ARTIST_CREDIT   : Beyond the Black
      ARTISTSORT      : Beyond the Black
      BPM             : 156
      CATALOGNUMBER   : [none]
      COMPILATION     : 0
      COMPOSER        : Jennifer Haben, Chris Hermsdörfer, Hartmut Krech, David Levy, Mark Nissen
      COMPOSERSORT    : Haben, Jennifer, Hermsdörfer, Chris, Krech, Hartmut, Levy, David, Nissen, Mark
      RELEASECOUNTRY  : US
      DATE            : 2020-06-17
      YEAR            : 2020
      disc            : 1
      DISCTOTAL       : 1
      DISCC           : 1
      TOTALDISCS      : 1
      GENRE           : Symphonic Metal, Power Metal, Metal
      INITIALKEY      : Fm
      LABEL           : Napalm Records
      PUBLISHER       : Napalm Records
      LANGUAGE        : eng
      LYRICIST        : Jennifer Haben, Hartmut Krech, David Levy, Mark Nissen
      LYRICS          : [Intro]
                      : Horizons, horizons, horizons
                      :
                      : [Verse 1]
                      : Come with me
                      : For we're the ones to see the light
                      : Come with me
                      : Beyond horizons through the night
                      : Anything that lies within
                      : Deepest roots can be no sin
                      : The night unfolds the beauty and the beast
                      : Come with me
                      :
                      : [Pre-Chorus]
                      : I can see it in your eyes
                      : They are burning for this life
                      : We can go to see it all
                      : We are invincible
                      :
                      : [Chorus]
                      : Horizons, horizons, horizons
                      : Oh, won't you come with me?
                      : We can share a common vision
                      : Come with me
                      : We can aim for new horizons
                      :
                      : [Verse 2]
                      : Come with me
                      : We're fighting for a better place
                      : Come with me
                      : Can't leave the earth without a trace
                      : Anything that dares to fly
                      : Invisibly for human eyes
                      : Hides within the dark to show its face
                      : Come with me
                      :
                      : [Pre-Chorus]
                      : I can see it in your eyes
                      : They are burning for this life
                      : We can go to see it all
                      : We are invincible
                      :
                      : [Chorus]
                      : Horizons, horizons, horizons
                      : Oh, won't you come with me?
                      : We can share a common vision
                      : Come with me
                      : We can aim for new horizons
                      :
                      : [Pre-Chorus]
                      : I can see it in your eyes
                      : They are burning for this life
                      : We can go to see it all
                      : We are invincible
                      :
                      : [Chorus]
                      : Horizons, horizons, horizons
                      : Oh, won't you come with me?
                      : We can share a common vision
                      : Come with me
                      : We can aim for new horizons
                      :
                      : [Outro]
                      : Oh, horizons
                      : We can aim for new horizons
      MUSICBRAINZ_ALBUMARTISTID: 9f18016f-f0af-4a56-9e58-035c1916a8f3
      MUSICBRAINZ_ALBUMID: fc513fc6-66bf-4d31-93d3-1656e7b0f348
      MUSICBRAINZ_ARTISTID: 9f18016f-f0af-4a56-9e58-035c1916a8f3
      MUSICBRAINZ_RELEASEGROUPID: 3282ef07-94d5-4626-ac4e-e77cb09a6f7d
      MUSICBRAINZ_RELEASETRACKID: 24e14fb6-2003-405b-8eab-532ae5a78d60
      MUSICBRAINZ_TRACKID: 4176a296-f50f-4e4c-b24c-75fbf0db3bf8
      MUSICBRAINZ_WORKID: 29665b6a-bed0-4e71-95a7-68c962f7acde
      MEDIA           : Digital Media
      ORIGINALDATE    : 2020-06-17
      SCRIPT          : Latn
      TITLE           : Horizons
      track           : 1
      TRACKTOTAL      : 13
      TRACKC          : 13
      TOTALTRACKS     : 13
  Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1000x1000 [SAR 72:72 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Cover (front)
```

Meanwhile, here's what I get from Vinyl:
![Screenshot_20210628-132407_Vinyl_Music_Player](https://user-images.githubusercontent.com/17353799/123629487-9ecb4800-d814-11eb-8d59-6cc3de265289.png)
![Screenshot_20210628-132441_Vinyl_Music_Player](https://user-images.githubusercontent.com/17353799/123629501-a2f76580-d814-11eb-9786-b2edaec85a6a.png)

The Track is missing all format information, the disc number formatting is broken and at least the lyrics are missing although present in the file itself.

I understand that this is an issue with the android media scanner and google refusing to acknowledge opus' existence as an audio format for non-streamed music, but I think at least the disc number handling would deserve some digging, as theres clearly _some_ data there, it's just displayed in a weird way.

**Comment by Sogolumbo** [comment]
As far as I know the track number 1001 means first disk, first song. I think I've seen some similar encoding in some tool tip in Kid3, but I'm not sure about it.

**Comment by f1reflyyyylmao** [comment]
While thats true, you can clearly see that in the tag data the fields aren't formatted like that:
```
disc            : 1
DISCTOTAL       : 1
DISCC           : 1
TOTALDISCS      : 1
```

```
track           : 1
TRACKTOTAL      : 13
TRACKC          : 13
TOTALTRACKS     : 13
```

As you see, when displaying equally tagged mp3 files the presentation is quite different:
![exhibit a](https://user-images.githubusercontent.com/17353799/127046901-192a4e63-e223-4c8e-962d-25cafb39082d.png)

**Comment by soncaokim** [comment]
For the metadata that media store/android os manages to extract from the file, but displayed incorrectly by the app - such as disc number - I can have a look at the app code (or better, if someone is willing to jump in, I can point out where the bug probably is).

However, this is only a minor fix comparing to what's obviously expected - to be able to extract other metadata and to be able to edit the metadata. For this the app relies on an external library - jaudiotagger.

The issue is only solved when this library provides support  for the file format (ogg, opus, flac, etc). Please contribute to this upstream library, that would be beneficial for a greater audience.

**Comment by f1reflyyyylmao** [comment]
Not going to happen i'd say: https://bitbucket.org/ijabz/jaudiotagger/issues/65/add-support-for-ogg-opus-format

**Comment by soncaokim** [comment]
> For the metadata that media store/android os manages to extract from the file, but displayed incorrectly by the app - such as disc number - I can have a look at the app code

I've just attempted a fix for the disc number fallback (see PR above), but however dont have any Opus file at hand to confirm. If possible, can you share a sample file (with the disc number displayed incorrectly) so that I can check?

**Comment by f1reflyyyylmao** [comment]
I'm a bit unsure what I'm allowed to share with you without Sony sueing me until I'm homeless, but I can give you the line I use to convert my audio to opus: 
```
ffmpeg -i $source_file -vn -acodec libopus -ab 96k $dest_file
```
Provided the original track has a disk and track number it should give you the test file you need.

**Comment by soncaokim** [comment]
Please dont share anything unallowed.
Thanks for the command.

**Comment by ShareASmile** [comment]
.

**Comment by HaneulCheong** [comment]
@soncaokim

> . . . For this the app relies on an external library - jaudiotagger.
> 
> The issue is only solved when this library provides support for the file format (ogg, opus, flac, etc) . . . 

Are you sure Vorbis comment is not supported by jaudiotagger? The [tag mapping](http://www.jthink.net/jaudiotagger/tagmapping.html) from the library's [web site](http://www.jthink.net/jaudiotagger/) shows the library does have a mapping for Vorbis's GENRE tag and yet Vinyl still shows all opus and ogg tracks' genres as "Unknown Genre" as of 1.3.0. In fact it seems jaudiotagger's Vorbis support level is completely the same as ID3.
