### ISSUE TITLE
Genres: Show Albums within selected Genre

### ISSUE THREAD

**Issue by patrasco** [AdrienPoupa/VinylMusicPlayer#414]
V1.1.2
Tab 'Genres', select a genre. Currently there is only a song view for a given genre, listed by track title (ascending).

Consider a large music collection containing several genres. Under tab 'Genres', select a genre like 'Classical Baroque'. In that case a list of songs by track title doesn't make much sense. More useful would be show all the Albums within that genre, and then select an Album to play.

There may be a simple way to combine both Album view and Song view for a Genre. First show the artwork of all the Albums within the genre, followed (if you scroll further down) by a list all the songs within the genre.

**Comment by soncaokim** [comment]
The pull request https://github.com/AdrienPoupa/VinylMusicPlayer/pull/467 contain improvement similar to requested here: the list of song is still shown for each genre, but the songs are sorted by album
