### ISSUE TITLE
Wrap filename

### ISSUE THREAD

**Issue by Xyde** [AdrienPoupa/VinylMusicPlayer#416]
**Is your feature request related to a problem? Please describe.**

I have a lot of untagged songs with the same title but different remix and covers. But because the filename doesn't wrap properly, I have no idea which version is playing at the moment so it's very annoying.

**Describe the solution you'd like**
Add text wrapping.

**Describe alternatives you've considered**
Make text size smaller.
**Additional context**

**Comment by soncaokim** [comment]
I assume that you are using the "Folder" view to browse through the music library. Right now if the (folder/file) name is too long to display, the name is "ellipsized" - truncated, with ... added at the end of the displayed name.
You can swipe the name to get to the end of it.

The same is possible with the song on now-playing screen.

Would that be helpful?

**Comment by AdrienPoupa** [comment]
Yes, you can swipe the title directly :)
