### ISSUE TITLE
Deal with Use of All files access (MANAGE_EXTERNAL_STORAGE) permission

### ISSUE THREAD

**Issue by AdrienPoupa** [AdrienPoupa/VinylMusicPlayer#427]
When submitting the latest release I saw this warning: https://support.google.com/googleplay/android-developer/answer/10467955

![image](https://user-images.githubusercontent.com/15086425/116009327-e8b26a80-a5e6-11eb-874a-7b07ac415fd6.png)

**Comment by soncaokim** [comment]
If I recall correctly, this permission is added to be able to manipulate playlist/faves. 

We might need that to apply metadata scanning as well (Google's one is a mess, you have multiple bug reports to support this).

And probably to use the folder based browsing.

Given that we offer direct file/folder browsing, do we qualify as an exception? :-p

**Comment by AdrienPoupa** [comment]
Yes, I think it would be the easiest way to deal with this, however Google's support is a mess as well :p

**Comment by soncaokim** [comment]
Btw @Octoton @tramhao this is a call to finish the ongoing pull request before we get to the hiatus due to G's policy enforcement.

There is some conflict with your PRs that caused by my recent change, should be minor.

**Comment by soncaokim** [comment]
@AdrienPoupa Reading through the link you provided in the first post, I'm curious why we are concerned by this restriction:

- This is only impacting apps targetting Android 11 and uses the new Android's permission MANAGE_EXTERNAL_STORAGE
- My post mentions existing features (metadata scan etc) but they are not using the new permission
- Our build.gradle is targetting API 29, i.e. before Android 11 if I'm not wrong.

So my understanding is that we are not concerned by this and should not be worried by now.

Is this still a blocking point? Do you have any progress on this?

**Comment by soncaokim** [comment]
Concerning this offending line https://github.com/AdrienPoupa/VinylMusicPlayer/blob/33a7d3e29051abaf57048eaf3c273ea8dbb0e6c5/app/src/main/AndroidManifest.xml#L26

I think we can cook up a complete replacement for the playlist mgmt, so this permission can be dropped and resolve probably the playlist vs tracks on external storage issue at the same time.

This will take time however. What are our short term options?

**Comment by AdrienPoupa** [comment]
I was able to submit 3.3.0 without submitting a form.

A warning was added [here](https://support.google.com/googleplay/android-developer/answer/10467955), stating that this will only affect apps targeting API 30 while we are still targeting 29.

**Comment by soncaokim** [comment]
Ok, let me have look on the internal playlist mgmt, instead of relying on Android support.

Obvious limit will be desync and non native playlist sharing with other players.

**Comment by ShareASmile** [comment]
.

**Comment by ShareASmile** [comment]
.
