### ISSUE TITLE
Now playing controls dont reflect playing state after extended sleep

### ISSUE THREAD

**Issue by soncaokim** [AdrienPoupa/VinylMusicPlayer#428]
**Describe the bug**
Now playing controls dont reflect playing state after extended sleep (ex: resume in the morning)

**To Reproduce**
Steps to reproduce:
1. Play a queue
2. Pause
3. Leave the phone sleeping, for long time.
4. Resume playback
5. Sometime - I've not managed to reproduce consistently - the playback controls (bottom bar) dont reflect the current playback (current song incorrect, play/pause button incorrect.
6. Force restart or repeatedly go back inside the app till the UI quits (playback still on), then relaunch -> playback controls are correct.

**Additional context**
This happens since several versions back, i.e not related uniquely to v1.2.0

**Comment by soncaokim** [comment]
If anyone has further info that might help tracking down this issue, it is much appreciated.

**Comment by soncaokim** [comment]
I'm still trying to reproduce and tracking down the issue. 

Looks like the internal messages (between the MusicService part of the app and the other parts) are not getting delivered after some extended sleep.

**Comment by ShareASmile** [comment]
bump

**Comment by ShareASmile** [comment]
.
