### ISSUE TITLE
[Feature Request] ALAC support

### ISSUE THREAD

**Issue by nean-and-i** [AdrienPoupa/VinylMusicPlayer#43]
First of all the VinylMusicPlayer is great!
Unfortunately it does not support ALAC, so I have to use a different player to playback the songs which I converted to Apple Lossless format in iTunes.
Is it possible to integrate ALAC codec/decoder?

thanks,
nean

**Comment by ildar** [comment]
Is it not patent-infected?

**Comment by nean-and-i** [comment]
let me allow to state it that way:
"some other players have no issue playing back ALAC" eg.: VLC, foobar2000, etc,...

**Comment by catb0t** [comment]
@ildar no, Apple released the source code under Apache 2.0 and there is no patent, so the Java port is legal too
