### ISSUE TITLE
Add confirmation dialog for rescanning library

### ISSUE THREAD

**Issue by tguen** [AdrienPoupa/VinylMusicPlayer#431]
The navigation drawer has a "rescan library" option. When clicked, it will immediately rescan all of my music, which takes a few minutes for me. Depending on the size of the library & the hardware it may take even longer. Until this process is completed, I am unable to find any music that has not yet been rescanned. It should not be so easy to start this process by accident. A simple confirmation dialog explaining that it may take a while & allowing the user to cancel the process would be appreciated.

**Comment by soncaokim** [comment]
Makes sense to me.
