### ISSUE TITLE
"Shuffle All" button does not start new playback

### ISSUE THREAD

**Issue by Uvik** [AdrienPoupa/VinylMusicPlayer#438]
**Describe the bug**
"Shuffle All" button in Songs tab does not start playback (still works from the app's contextual menu on the homescreen)

**To Reproduce**
1. Start playing a song from any tab. Keep it playing or pause it, both lead to the same situation.
2. Go to the "Songs" tab
3. Tap "Shuffle All"

**Expected behavior**
I expecting the button to start a new shuffled playback of all my songs, which I believe was the case until the latest update. 

**Screenshots**
![Screenshot_20210506-104322__01](https://user-images.githubusercontent.com/11810912/117270817-e3141a80-ae59-11eb-8007-e1747d974b2e.jpg)
![Screenshot_20210506-105431__01](https://user-images.githubusercontent.com/11810912/117270825-e3acb100-ae59-11eb-91b5-69314c990633.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 Pro (GMT1913)
 - Android Version: 11
 - ROM: Oxygen OS 11.0.0.2.GM21BA
 - Vinyl Music Player Version: 1.2.0 (Google Play Store)

**Comment by soncaokim** [comment]
Hi, thanks for reporting this. I'll take a look
