### ISSUE TITLE
Play song without enqueueing the rest of the album/playlist

### ISSUE THREAD

**Issue by 0x6273** [AdrienPoupa/VinylMusicPlayer#448]
**Is your feature request related to a problem? Please describe.**
I often want to play just a single song from an album or playlist. This means having to tap the 3 dot menu, tapping "Play Next," and then tapping the play button.

**Describe the solution you'd like**
I would like this to happen when I tap the song. Please add an option to change the behavior of tapping a song.

**Describe alternatives you've considered**
An alternative would be to have swiping the song to the left/right preform this action.

**Additional context**
Another music app, Vanilla Music, has this option. There it is called "Default playlist action." It has a variety of default actions to choose from: "Play," "Enqueue," "Last used action," "Play all," "Enqueue all," "Enqueue if playing; Play if paused," "Play next," "Do nothing."

**Comment by ShareASmile** [comment]
.

**Comment by ShareASmile** [comment]
.
