### ISSUE TITLE
Can't Import Playlist File (.m3u)

### ISSUE THREAD

**Issue by SarahTehCat** [AdrienPoupa/VinylMusicPlayer#45]
Vinyl Music Player lets you export a given playlist to a .m3u file by tapping the playlist's options icon (the 3 vertical dots) and selecting "Save as File".

However, the app doesn't seemingly give an option to import said file. Either that or I can't figure it out. 

I've tried searching the FAQs, looking through the settings multiple times, and using both an external file manager and the app's internal file manager to open the file in Vinyl.

I've also tried using the internal file manager to select the m3u file and then select "Scan" and I get an error message that says 

`Scanned 0 of 1 files. Could not scan 1 files`.

**Comment by Dorsug** [comment]
Having the same problem here. How did you get past it, if you did ?
