### ISSUE TITLE
Folder view not working with SD card

### ISSUE THREAD

**Issue by CarneSeca** [AdrienPoupa/VinylMusicPlayer#453]
**Describe the bug**
I've just downloaded Vinyl (1.2.0, F-Droid) and after granting storage permission, it finds all the music on my SD card just fine - all songs and .m3u playlists are easily accessible in library view. However, when switching to folder view, the folder defaults to Root>Storage>Emulated>0>Music (which is an empty music folder in the internal storage, I've tried deleting it but Vinyl seems to default to it anyways.) I can't find a way to get to the SD card - I can tap on '0' which gets me to the root folder of my internal storage, but tapping 'root', 'storage', or 'emulated' just gets me the "Empty" message.

**To Reproduce**
1. Open Vinyl
2. Switch to Folder
3. See internal storage only, no way to switch to SD card.

**Expected behavior**
Some way to change the view to the Music folder on the SD card.

**Smartphone (please complete the following information):**
 - Device: Moto X4
 - Android Version: 11
 - ROM: LineageOS 18.1
 - Vinyl Music Player Version: 1.2.0 (F-Droid)

**Comment by Yusei-StarDust** [comment]
I have same problem in my phone.

- Device: Samsung note 10 Lite
- Android Version: 11
- ROM: RP1A.200720.012.N770FZHS7EUF2
- Vinyl Music Player Version: 1.3.0 (F-Droid)

**Comment by msiep** [comment]
I have the same problem on my new phone:
- Device: Samsung Galaxy A12
- Android Version: 11
- Vinyl Music Player Version: 1.3.0 (F-Droid)

**Comment by mikhoul** [comment]
Same here, its caused by Android 11 that require a new way to access SD card: (Scoped Storage) : https://developer.android.com/about/versions/11/privacy/storage

@AdrienPoupa 

Regards :octocat:

**Comment by e-motiv** [comment]
> Same here, its caused by Android 11 that require a new way to access SD card: (Scoped Storage) : https://developer.android.com/about/versions/11/privacy/storage
> 
> @AdrienPoupa
> 
> Regards :octocat:

I have the same problem (with a lot of music players so far tested).
But according to that page it should still have read access to external storage. Maybe developers haven't set the right flag or variable or are requesting write access or something else is going on, because all the songs on external storage are still found!
I'm gonna reopen this issue to see how developer(s) react.
