### ISSUE TITLE
Add Repeat Button on Notification Tab

### ISSUE THREAD

**Issue by ghost** [AdrienPoupa/VinylMusicPlayer#454]
**Is your feature request related to a problem? Please describe.**
In my previous music player, I can toggle the Repeat button whenever I'd like to repeat a song or its whole group. But when I jumped to Vinyl to replace my core apps with open-source alternatives, I find the Repeat button missing. I miss that convenience that I had before, and I'd like to see it added here.

**Describe the solution you'd like**
Add a Repeat option on the Notification tab. See "Additional Context" for screenshot references

**Describe alternatives you've considered**
I don't think there are any.

**Additional context**
No Repeat Option on Vinyl
![Screenshot_20210527-123525.jpg](https://user-images.githubusercontent.com/79004952/119804876-6e2c8180-bee9-11eb-99ef-954ca5322215.jpg)

Repeat Option Available on Omnia Music Player
![Screenshot_20210527-123902.jpg](https://user-images.githubusercontent.com/79004952/119805024-8ef4d700-bee9-11eb-9bb2-7b109c7e5490.jpg)

**Comment by ShareASmile** [comment]
.

**Comment by ShareASmile** [comment]
.

**Comment by ShareASmile** [comment]
.
