### ISSUE TITLE
last.fm scrobble support

### ISSUE THREAD

**Issue by theotheroracle** [AdrienPoupa/VinylMusicPlayer#455]
could last.fm scrobbling be implemented ?

**Comment by soncaokim** [comment]
There is some mention of last.fm support built in already in the code. If you can point out what is expected and what is working/not working, this will be helpful.

**Comment by theotheroracle** [comment]
i don't see any option to sign in to last.fm the settings menu . but yes, the player this is based on seemed to have supported scrobbling in the past but may have been removed at some point, based on what i could find . ( the api changed and support likely broke )

basically, you need to sign in to last.fm ( preferably with [oauth](https://www.last.fm/api/authentication) ), and then vinyl should send to last.fm what song is currently playing via [now playing requests](https://www.last.fm/api/scrobbling#now-playing-requests), and then scrobble them upon completion via [scrobble requests](https://www.last.fm/api/scrobbling#scrobble-requests) .

**Comment by emmatebibyte** [comment]
libre.fm support is something I'd be interested in
