### ISSUE TITLE
Define app as Google Assistant's default music service

### ISSUE THREAD

**Issue by pixel2user** [AdrienPoupa/VinylMusicPlayer#459]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
If Vinyl is added as 'Google Assistant's default music service', it would be possible to use Google Assistant to select an MP3 stored on the internal memory of my smartphone by saying "OK, Google. Play 'Jesus Loves Me' by DMX in Vinyl."

**Describe alternatives you've considered**
Use other speech recognition providers to select the correct song.

**Additional context**
Maybe this is not possible, as long as Google doesn't allow to add new apps as 'Google Assistant's default music service': 
https://stackoverflow.com/questions/47962336/define-my-app-as-google-assistants-default-music-service

**Comment by AdrienPoupa** [comment]
This would be nice but it seems to be a Google limitation unfortunately.
