### ISSUE TITLE
Add spanish translation

### ISSUE THREAD

**Issue by samthelion** [AdrienPoupa/VinylMusicPlayer#460]
I would like to collaborate adding Spanish translation, if u show me how...

**Comment by soncaokim** [comment]
Hi, are you familiar with Android devel and having a devel environment set up? If yes, this involves running Vinyl on an emulator, makes the needed text change, test it and submit a pull request.

If all this blah blah is not making any sense to you, or you dont want to invest in such heavy setup, I'm afraid we dont have the proper setup to ease the translation submission. 

Other apps have this kind of support, shame on us.

In any case, thanks for the offer.

**Comment by samthelion** [comment]
I'm not familiar, but I can learn! I'll get back to this when I have the time. Hang on....

**Comment by AdrienPoupa** [comment]
Feel free to open a PR when needed

**Comment by soncaokim** [comment]
If you are following this repo, there are some recent translation efforts that might give you some handle to where to start.

Adrien has also enabled the support to build pull request, so if you open one we can see if your build passes or not. 

Not a perfect and painless path, but at least some tedious setup steps are automated.
