### ISSUE TITLE
Android Auto Compatability

### ISSUE THREAD

**Issue by theksepyro** [AdrienPoupa/VinylMusicPlayer#462]
**Is your feature request related to a problem? Please describe.**
I wouldn't say it's related to a problem. More of a nice to have than to fix an issue.

**Describe the solution you'd like**
Enable Vinyl music Player to be able to interface with Android Auto to play music safely while driving. I imagine this would require some development for the appropriate UI and review by Google.

**Describe alternatives you've considered**
To my understanding there are some proprietary apps that can do this, and there is a workaround via AnyAutoAudio, but it would be nice to have a good native open source solution.

**Additional context**
NA

Thanks for the consideration.

**Comment by soncaokim** [comment]
I'm using Vinyl with Auto. You might need to choose it as the default music player first via the Auto interface.

**Comment by theksepyro** [comment]
If that is the case I am embarrassed and apologize for taking your time. I had only tried it for a few minutes while driving a relatives car and didn't apparently do my full due diligence.

**Comment by theksepyro** [comment]
To follow up on what solved this issue for me in case anyone else comes along that can't get it to work, you might have to take additional steps if you install it from f-droid (or anywhere other than the play store). I had to enable developer mode on the Android auto app on my phone and then allow apps from "unknown sources" in the developer settings before it would show up on the car screen.
