### ISSUE TITLE
Option to close app

### ISSUE THREAD

**Issue by Jolopu** [AdrienPoupa/VinylMusicPlayer#464]
This is the best player around. Excellent user interface. I use Vinyl Player on my Google Pixel 2XL with CalyxOS (Android 11). Everything works great except I could not find a way to close the app. When swiping it up it continues playing in the pull down menu. In the pull down menu app widget of Vinyl Player there is no "x" to close the player. And by pressing the back button in the player main window, it also continues playing. The only way I manage to close the player is to go into the app properties and force quit the app.  Not a nice way.

So my feature request would be:
- Include an option to close the player when the back button is pressed in the player main window. (This is standard in many other players.)
- Include a "X" into the pull down menu widget of the player to close it. (Also seen in many other players.)
- Include a close option into the main menu of the player. (Still much space there.)

This said, it's the most intuitive and beautiful player I've seen on Android. Just trying to help making it perfect. ;-)

Thanks!

-Jolopu

**Comment by Jolopu** [comment]
Thanks for fixing! ;-)

**Comment by adrielsand** [comment]
@Jolopu If this issue is fixed, why don't you close it? Thanks!
