### ISSUE TITLE
USB Audio support

### ISSUE THREAD

**Issue by Jolopu** [AdrienPoupa/VinylMusicPlayer#465]
It would be great if Vinyl would support USB Audio. I use the Audioquest Dragonfly Red decoder for hires audio on my Pixel 2 XL with CalyxOS (Android 11). I tried to use it with Vinyl but the sound has artefacts. I think this is due to the standard Android USB driver. Other apps like Neutron Player or USB Audio Pro have their own driver for USB audio which sounds muuuuuch better. Maybe there is a way to include USB Audio support in Vinyl. Would be awesome!

Thanks!

-Jolopu

**Comment by dodoradio** [comment]
So usb audio is an utter pain on android. Android natively supports USB Audio Class 1 (UAC1) which is quite old. The greater fraction of USB DACs etc. nowadays only support UAC2, so when you connect them, you get awful noise. Adding support for UAC2 would require a whole usb interface to be written.
