### ISSUE TITLE
Dark mode for widgets

### ISSUE THREAD

**Issue by ALongToe** [AdrienPoupa/VinylMusicPlayer#468]
Even to this day, the 4x1 widgets are white. Is there a possibility to add dark mode to them? Thank you.

**Comment by ShareASmile** [comment]
.

**Comment by ShareASmile** [comment]
.

**Comment by soncaokim** [comment]
Closing this, thanks to https://github.com/AdrienPoupa/VinylMusicPlayer/pull/522
Please dont hesitate to reopen this if it's not satisfactory
