### ISSUE TITLE
Gap displayed between songs in Now Playing list (visual issue only)

### ISSUE THREAD

**Issue by sknorr-prv** [AdrienPoupa/VinylMusicPlayer#479]
**Describe the bug**
Vinyl sometimes leaves a visual gap where the next song should be displayed.
Functionality is fine though -- the invisible song is played next anyway.
This is not a consistent issue, so I can't really give instructions how to reproduce it.

**To Reproduce**
1. Make a Now-Playing list, and open it
2. Hope the issue reproduces :/

**Expected behavior**
No visual gaps.
The next song should be displayed as normal.

**Screenshots**

![vinyl-gap](https://user-images.githubusercontent.com/47387444/124044575-07c9e000-da0e-11eb-9f92-dd20fd9b52aa.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - Android Version: 11
 - ROM: stock
 - Vinyl Music Player Version: 1.2.0

**Comment by soncaokim** [comment]
This is weird. How often this happens to you (many times a day, once a day, every few days)

Even though there is no specific change that targets this issue, I'd suggest you to upgrade to the latest version 1.3.x

**Comment by sknorr-prv** [comment]
I can't really say -- It's happened a few times within that same listening session before I stopped/restarted Vinyl. As I mentioned, it's not really something that I know how to reproduce or quantify how often it happens (I guess I may not be listening to enough music right now).
