### ISSUE TITLE
Adding/removing songs to/from playlists - "Add to Playlist..." dialog

### ISSUE THREAD

**Issue by Sogolumbo** [AdrienPoupa/VinylMusicPlayer#484]
**Is your feature request related to a problem? Please describe.**
It is not easy to find out if a song/set of songs is already in a playlist. I think this should be shown in the "add to playlist..." dialog. ~This would make it easy to avoid unwanted duplicates in playlists.~
Also there is no easy way to remove a specific song from a playlist without scrolling through the entire playlist. Because the playlists aren't sorted this is nearly impossible to do in big playlists with over 1000 songs.

**Describe the solution you'd like**
I would propose a solution that is similar to the way playlists are handeled on youtube:
![image](https://user-images.githubusercontent.com/33571916/35697190-be53d5c0-0789-11e8-9722-f66f354f7669.png)
There checkboxes are used to indicate if a song is already in a playlist or not and you can easily add and remove songs.
There are two problems with this:
1. When selecting a set of songs (e.g. one album) where only some of the songs are in the playlist a simple two state checkbox will not be able to communicate the situation. I think this can be solved by using a three state checkbox where the third state is used to indicate a more complex situation.
2. It is possible that people want to add a song to one playlist multiple times (e.g. for doing workout sessions, trolling, ...). This should still be possible in future. This could be done by leaving the current dialog in there in addition to the new one. To make it a little bit more intuitive maybe this function could be enabled and removed in the settings (e.g. "allow duplicate songs in playlists").

**Additional context**
I have made some effort trying to implement this myself in [my Phonograph fork](https://github.com/Sogolumbo/Phonograph) ([Pull Request](https://github.com/kabouzeid/Phonograph/pull/432) in the original Phonograph repo with screenshots).
I seem to be unable to implement this properly because I miss the necessary knowledge/skills for the Android UI. More specifically I couldn't find a three state checkbox in the framework and I do not know how to implement one. (I built a hacky solution which worked for me by adding unicode checkmark symbols in brackets to indicate the third state. But clearly that doesn't do justice to the visual appearance of Vinyl/Phonograph.)

Please add Ideas and thoughts you have. 
If I know that someone with the necessary skills is be willing to support me I would try and make a fork where I implement everything I can and then the other person could help me to finish it and make sure the coding standards are met.

**Edit**:
Duplicates are already avoided: If a song is added to a playlist the second time there's a dialog which asks how to handle this.

**Comment by soncaokim** [comment]
There is a recent change in this direction https://github.com/AdrienPoupa/VinylMusicPlayer/pull/382

Can you please refine your idea and submit mockup UI (sketches are fine) first. If this gets enough traction I can help reviewing the underlying code if needed.

**Comment by Sogolumbo** [comment]
Hey, sorry for the delay:
This is my mockup:
![Playlist-menu](https://user-images.githubusercontent.com/33571916/127203977-cdef77a7-fe30-446b-b5fe-518a0272ad99.png)

When clicking on "New playlist..." the state of the selection should be memorized. Then the dialog for new playlists will be opened. After that this dialog will come back with the memorized selections and the new playlist selected.

For the design of the third state of the checkbox I would used the same design as in [1].
The third state would only be possible to select if it was the initial state (which corresponds to only some of the selected songs being in the playlist).
Then a selected checkbox would add all (missing) songs to that playlist and a deselected checkbox would remove all selected songs from that playlist.

[1] IndeterminateCheckbox (the repo seems to be an example implementation) https://github.com/imhardiklakhani/IndeterminateCheckbox

**Comment by soncaokim** [comment]
Hi, I guess I understand your idea. 

However I dont find it very necessary. I would, in my opinion, avoid manual/static playlists with that many elements (you cannot just scroll through the list to find a song).

Or we need a full feature set for playlist mass-manipulation: sorting, grouping, searching... in addition to duplicate detection.

**Comment by Sogolumbo** [comment]
> However I dont find it very necessary. I would, in my opinion, avoid manual/static playlists with that many elements

Everyone's musical taste is different so it makes very much sense to create and maintain your own playlists manually.
What other kind of playlists are there? (And are any of them supported by vinyl?)
Also for me this feature is very much necessary as I have playlists with 2500 songs and a total of roughly 6000 songs on my phone. But even with a playlist of 30 songs it gets really annoying to manually have to search a song just to delete it.

> [Or] we need a full feature set for playlist mass-manipulation: sorting, grouping, searching... in addition to duplicate detection.

Yes! I agree we need more playlist features. I personally think this current feature might be the most important one for playlist manipulation.

### Off topic for this specific feature:
I thought that it would be awesome to have something I'd call a search query. There you can combine as many 'conditions' as you like into one query and will get a resulting playlist. You can play those songs, make a playlist from them or maybe even save the query for future use. Possible conditions would be a specific title/artist/album/genre or if some string is part of those names.

### About this feature:
Do you have any criticism on the design and logic behind it?
