### ISSUE TITLE
jcenter Maven repository is deprecated

### ISSUE THREAD

**Issue by alanorth** [AdrienPoupa/VinylMusicPlayer#489]
**Describe the bug**
Attempting to build 1.3.0, Gradle warns that jcenter is going away soon. We need to migrate to another repository.

**To Reproduce**
Start gradlew:

```console
$ ./gradlew      
WARNING:: Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.
This repository is deprecated and it will be shut down in the future.
See http://developer.android.com/r/tools/jcenter-end-of-service for more information.
Currently detected usages in: root project 'VinylMusicPlayer', project ':app'
```

It seems we will also need to update a few dependencies, as they are not found on Maven central. For example:

- [com.afollestad:material-cab:0.1.12](https://search.maven.org/artifact/com.afollestad/material-cab)

**Comment by AdrienPoupa** [comment]
Good point. I started to replace it but saw that some deps were missing indeed.
