### ISSUE TITLE
Some ogg files are not listed on Vinyl Music Player Collection

### ISSUE THREAD

**Issue by trmendes** [AdrienPoupa/VinylMusicPlayer#50]
Some ogg files are not listed on Vinyl Music Player

Those files lives at the same directory SD-CARD/Music

How can I provide you more useful info about it?

Vinyl Player: 0.17.0 F-DROID
Android: LineageOS 15 (Android version 8.1.0)

**Comment by ildar** [comment]
Can you see them in other players? How?

**Comment by trmendes** [comment]
@ildar I only have Vinyl Music Player on my mobile.

I can play the files on other players when I take the sdcard from my mobile and plug into my laptop to play.

**Comment by ildar** [comment]
No. The idea is to see if Android Media Service sees the files

**Comment by trmendes** [comment]
How can I check the status of the Android Media Service to see if I have the files indexed by it?
Another question would be: How do I reset the Android Media Service to make it index all the ogg files again?

**Comment by trmendes** [comment]
@ildar Made a reset here at the Media Cache...The songs are now there but the issue #40 and #49 still happening...any idea?
