### ISSUE TITLE
App Crashing

### ISSUE THREAD

**Issue by IIIJIII** [AdrienPoupa/VinylMusicPlayer#500]
The app crashes fairly regularly.

Most of the time when the app crashes it is when I am selecting an  artist or album.
However recently the app has been crashing from the start up of the app.

This will happen for a little while then the app will work again.

Pixel 5
Android 11
GrapheneOS
Version 1.3.0

**Comment by IIIJIII** [comment]
I downgraded to 1.1.2 yesterday after seeing a similar report of a bug and the suggestion that downgrading to 1.1.2 fixes it. So far the app is working normally with no crashes so far

**Comment by IIIJIII** [comment]
This version has now started to crash.

**Comment by IIIJIII** [comment]
All of the songs I have downloaded are m4a files, I don't know whether this will affect it.

**Comment by IJohnDoeI** [comment]
I am having this issue also, downgrading to 1.1.2 has fixed the crashing though.

**Comment by IJohnDoeI** [comment]
Mine has started to crash again, it seems to crash when I'm looking through artists of songs.
