### ISSUE TITLE
Real Shuffle Mode

### ISSUE THREAD

**Issue by Rorschach1010** [AdrienPoupa/VinylMusicPlayer#501]
Any chance to get a real shuffle mode? Shuffle as in random tracks being shuffled indefinitely. The current shuffle mode just creates a randomized playlist with every track included once and the player stops when all tracks were played.
I am well aware that I could just click on random play at the top of the tracklist again but when I'm driving in my car I just want the player to shuffle all of my tracks until I arrive at my destination without the need to ever touch my phone (for safety reasons).

**Comment by AdrienPoupa** [comment]
@Octoton would your PR fix this?

**Comment by Octoton** [comment]
@AdrienPoupa not the current one (split queue from ...) but the one after will introduce infinite random album shuffling.
With it, we would be able to create an infinite song shuffling

**Comment by soncaokim** [comment]
I dont think it will (the idea was to shuffle by album), but the PR opens the doors for this request

**Comment by soncaokim** [comment]
> I dont think it will (the idea was to shuffle by album), but the PR opens the doors for this request

Okay he is faster than me 😀

**Comment by Rorschach1010** [comment]
That's great, looking forward to it :D

**Comment by Octoton** [comment]
As the time being you could just click on random play and in playing queue click on the looping queue icon (not a real song shuffle but if you have enough song it's pretty close)

**Comment by ShareASmile** [comment]
.

**Comment by ShareASmile** [comment]
.

**Comment by ShareASmile** [comment]
.
