### ISSUE TITLE
Sort artists by Album Artist

### ISSUE THREAD

**Issue by hellocatfood** [AdrienPoupa/VinylMusicPlayer#503]
**Is your feature request related to a problem? Please describe.**
When browsing the artist list it shows the artists including those that they have collaborated with. This can be useful but in situations where an artist collaborates with many people the artist list becomes very very long. See this example below for Aesop Rock.

![Screenshot_20210801-205802](https://user-images.githubusercontent.com/151947/127784262-3ef45dfd-fe99-4c53-b9d0-b108e76090a6.png)

**Describe the solution you'd like**
In the artist list view can an option be added to group/view by Album Artist? This would only show the Main artist(s). To elaborate on what Album Artist is I loaded a song into Picard.

![Screenshot from 2021-08-01 20-59-05](https://user-images.githubusercontent.com/151947/127784273-b1fc3a79-5e63-440c-b0b0-2379dcc1fa0a.png)

The Artist and Artists fields show all featured artists but the Album Artist shows only Aesop Rock. This would mostly help reduce the noise/length of the list.

**Comment by soncaokim** [comment]
You can retag your tracks, and instead of having "X feat. Y" as artist, declare them as separate ones (in multiple lines in the app)

**Comment by ShareASmile** [comment]
.

**Comment by aqxa1** [comment]
Sorting by album artist makes a lot more sense to me as well, even if it's just an option.

**Comment by ShareASmile** [comment]
.

**Comment by mikelpr** [comment]
Important and needs attention as this is frequent with many artists

**Comment by duude21** [comment]
I do not have my coding PC set up right now, but it seems like a minor change to me, no? If it is trouble for other people, it could be an option in settings.
Maybe I will try to code this next month when I have more time :)
