### ISSUE TITLE
Seek through songs using hardware buttons

### ISSUE THREAD

**Issue by hellocatfood** [AdrienPoupa/VinylMusicPlayer#504]
**Is your feature request related to a problem? Please describe.**
I own a [Sony NW-A105](https://www.sony.co.uk/electronics/support/digital-music-players-nw-nwz-a-series/nw-a105) which has dedicated buttons for playback and volume control. 

![maxresdefault](https://user-images.githubusercontent.com/151947/127784843-5a4a429f-68b8-408b-b596-8a2e1b088785.jpg)

Using the [default player](https://play.google.com/store/apps/details?id=com.sonyericsson.music&hl=en_GB&gl=US) when the forward and back buttons are held it seeks through the song.

When using Vinyl pressing and holding the same buttons skips through songs.

**Describe the solution you'd like**
 Can it be changed or an option be added to allow those buttons to seek through songs when pressed and held?

**Describe alternatives you've considered**
One way around this is to open the app and seek using the gui, but for easier operation without having to open the ui using just the hardware buttons would be better.

**Comment by ShareASmile** [comment]
.
