### ISSUE TITLE
Copycat on Google 

### ISSUE THREAD

**Issue by Poussinou** [AdrienPoupa/VinylMusicPlayer#511]
Hi @AdrienPoupa 

I found this app : https://play.google.com/store/apps/details?id=com.fivestarappsworld.musicplayer on the Google Play Store. I'm not sure if it's a copy of Vinyl or Phonograph, but this guy just took the source code, added some ads in it and put it on the Store, without warning this is free software...

As you are (maybe) the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove this copy from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v3 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app.

**Comment by Poussinou** [comment]
https://play.google.com/store/apps/details?id=com.kabouzeid.mymusic

**Comment by chopin2712** [comment]
lmao "gramophone"

**Comment by pixel2user** [comment]
The one from the opening post is gone. I commented on the other 3 to get the information out that the original has no ads and is FOSS!

**Comment by Poussinou** [comment]
* https://play.google.com/store/apps/details?id=com.dreamrevive.music from [this developer](https://play.google.com/store/apps/developer?id=Dream+Revive)
