### ISSUE TITLE
Now playing notification is showing previous song instead of current song

### ISSUE THREAD

**Issue by DeMikeyyy** [AdrienPoupa/VinylMusicPlayer#514]
Any fix for that? Android 11, Pixel Experience ROM, Mi 9T Pro

**Comment by bertin0** [comment]
I have also observed this issue from time to time, tapping pause and then play updates the notification to show the right song.

**Comment by TheTerminatorOfProgramming** [comment]
i have also experienced this issue.

**Comment by ShareASmile** [comment]
.
