### ISSUE TITLE
Feature request: add better equalizer 

### ISSUE THREAD

**Issue by takase1121** [AdrienPoupa/VinylMusicPlayer#53]
The equalizer in the player is very basic, please add a better equalizer with more control over the music and also other adjustments like playing speed and balance.

**Comment by AdrienPoupa** [comment]
Hello,

There is no built in equalizer afaik, it is the one from your phone.

**Comment by takase1121** [comment]
I see. Will you considerto add an equalizer in the future?

**Comment by AdrienPoupa** [comment]
I do not really see the need, some apps are doing that just fine
