### ISSUE TITLE
Scanning the library doesn't work under Android 12

### ISSUE THREAD

**Issue by sojusnik** [AdrienPoupa/VinylMusicPlayer#534]
**Describe the bug**
After upgrading to Android 12 I can't scan the library any more. I've removed all blacklisted folders and deactivated the whitelist function. Before that I've resetted the app (cleared settings and cache). But it didn't help. Even If I manually scan certain folders, they don't appear in the library.

Is this a known bug on Android 12?

Using the latest version of Vinyl from the Play Store.

**Comment by ShareASmile** [comment]
.

**Comment by deragon** [comment]
I have the same problem.  I want to be able to scan and include files under /storage/emulated/0/Podcasts, but I cannot manage it to work.

**Comment by sojusnik** [comment]
Same here, only that my folder lies in /storage/emulated/0/Audiobooks
