### ISSUE TITLE
new track doesn't update album timestamp

### ISSUE THREAD

**Issue by ildar** [AdrienPoupa/VinylMusicPlayer#537]
I have an artist XYZ and album XYZ containing singles.
I'm adding a new single to that album and expect that album to pop up in "Albums" tab which is sorted by "Date added". It doesn't.

**Comment by hxd2772** [comment]
have you tried tapping the top left menu button then tapping rescan media. (note that when you enter the app it should detect new files and say it has scanned in new files)

**Comment by ildar** [comment]
Of course that's AFTER rescan.

**Comment by ildar** [comment]
keep open

**Comment by ildar** [comment]
Please reopen
