### ISSUE TITLE
App Crashes when editing album cover on ogg file.

### ISSUE THREAD

**Issue by MintMain21** [AdrienPoupa/VinylMusicPlayer#539]
**Describe the bug**
Albums comprised of ogg files cannot have their album art changed. Any attempt will resort in either a white screen fading back to normalcy, or the app outright crashing.

**To Reproduce**
1. Go to album with ogg files.
2. Click on Tag Editor
3. Attempt to change the album art, including from local storage.
4. App will crash and/or fail to update tags.

**Expected behavior**
Art should update without any bugs, just as it does when changing art on albums comprised of m4a files.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: LG Stylo 5
 - Android Version: 10
 - ROM: ?
 - Vinyl Music Player Version: 1.3.0

**Additional context**
Issue seems to be exclusive to ogg files. Issue is non-existant with any other file format I've tried.

Also: This bug is replicateable in the Phonograph Music Player from which Vinyl was forked, so it's most likely a bug inherrited from there.

**Comment by hxd2772** [comment]
I have album tagged my ogg files using vinyl music player and it works flawlessly, perhaps a hardware issue?

**Comment by MintMain21** [comment]
I'm talking specifically about the album art tag. I've edited other tags no problem.

**Comment by hxd2772** [comment]
Just tried adding an album cover to an ogg file in vinyl, it crashes for me. So it is a software bug

**Comment by MintMain21** [comment]
Nope
