### ISSUE TITLE
Make artists modification possible

### ISSUE THREAD

**Issue by dobriseb** [AdrienPoupa/VinylMusicPlayer#54]
Hi,

I've got some artists names that were not correctly write in the mp3 and so VinylMusicPlayer doesn't find this artists and doens't propose any picture.

I change the mp3 information but VinylMusicPlayer still get the old and wrong name.

I didn't found any way for changing this.

Thanks a lot for this application.

**Comment by soncaokim** [comment]
Ia this bug still present with version 0.24?

Thanks

**Comment by soncaokim** [comment]
I'm closing this bug, it's not reproducibe (at least with version 0.24.1). Please dont hesitate to reopen with more info if it's not the case.
