### ISSUE TITLE
Question: Does it support High Resolution Flac Audio?

### ISSUE THREAD

**Issue by lamyergeier** [AdrienPoupa/VinylMusicPlayer#541]
I can play **24 bit stereo 96 kHz flac** using vinyl player. Does it really support the High Resolution Flac Audio or does it downgrades the quality?

**Comment by ShareASmile** [comment]
.

**Comment by animaldaydream** [comment]
That's a very good question.

I play Opus however Opus files are always encoded as 48khz audio, so I wouldn't like for them to be downsampled back to 44.1khz if it can be helped.

I also wanna play up to DXD if I feel like it. That's more of a fantasy though. I highly doubt Android can play 352.8khz audio.

I'd switch to Linux given the chance.
