### ISSUE TITLE
Android Auto possible regression

### ISSUE THREAD

**Issue by soncaokim** [AdrienPoupa/VinylMusicPlayer#544]
I ve just installed the master version (vinyl_master_6b35abe6_211205-2248-circleci-release.apk) and looks like the support for Android Auto is not ok.

My on device Auto shows this
![Screenshot_20211215-180625_Android_Auto](https://user-images.githubusercontent.com/13333482/146269786-78a32c1e-99b8-457a-9d7f-8ae14a6817cc.png)

Havent had a chance to look closer though.

Rolledback to the previous build (from my cont-integ branch, before the rebase operation I did today) is ok.

**Comment by soncaokim** [comment]
It seems that the ability to delete songs is gone with the API 31 upgrade as well.

I've partially rolled back the API 31 upgrade via 0e6309c96334efe8abc9f32c580f79e9f17b8c1f and the AA integration/delete song is OK.

**Comment by AdrienPoupa** [comment]
Do you think this is linked to the new permission scope?

**Comment by soncaokim** [comment]
I havent followed the changes in API 30 and 31, so no idea

**Comment by soncaokim** [comment]
For information, even with a downgrade to API 29, I've just had the same screen as shown in the initial post --> the Android Auto problem is not linked to the API 31 upgrade.

**Comment by soncaokim** [comment]
This should be fixed by the above-mentioned PR (https://github.com/AdrienPoupa/VinylMusicPlayer/pull/551)

> It seems that the ability to delete songs is gone with the API 31 upgrade as well.

This is a separate issue, havent retested since I've downgraded to API 29
