### ISSUE TITLE
Unicode song names are not shown correctly

### ISSUE THREAD

**Issue by takase1121** [AdrienPoupa/VinylMusicPlayer#55]
When I was using this music player to play some Japanese songs, I found out that some song names and albums are not displayed correctly. Here's an example:

![screenshot_2018-05-30-21-05-55-225_com poupa vinylmusicplayer](https://user-images.githubusercontent.com/20792268/40722223-4d8b95a4-644e-11e8-9398-ba93cff2eefa.jpg)

But the song names and albums are displayed correctly when opened in tag editor.

![screenshot_2018-05-30-21-06-08-817_com poupa vinylmusicplayer](https://user-images.githubusercontent.com/20792268/40722259-6a1176ee-644e-11e8-8f96-6366595d0ecc.jpg)

Please fix this problem. Thanks!

**Comment by AdrienPoupa** [comment]
Hi,

Could you provide a file that has this issue? You can send it at adrien at poupa dot fr.

**Comment by dglava** [comment]
I'm experiencing the same problem. I sent you a test file, the same from the screenshot below.

https://i.postimg.cc/SsF4g059/Screenshot-20190414-064133.png
