### ISSUE TITLE
Options to sort albums in annual order, per artist

### ISSUE THREAD

**Issue by StarPepe** [AdrienPoupa/VinylMusicPlayer#554]
**My issue:**
When viewing albums in the “Albums” category, the albums of artists are not sorted in the order of their year of release. Instead, they are sorted in alphabetical order only.

**An example:**
For example, Pink Floyd’s “A Momentary Lapse of Reason”, released in 1987, sits to the left of their album “Animals”, released in 1977, and directly below sits "Meddle", released in 1971. I do own many of their previous albums, all of which are tagged properly.

![Screenshot_20211230-182409 - Copy Resized](https://user-images.githubusercontent.com/96881600/147775304-f2d979c4-3064-47a8-a35c-3006ff2caeda.png)

**My solution:**
Because of this, I’d like to ask that the three buttons in the top-right corner have a new sort order added. It should be capable of sorting albums in annual order with an “Ascending” or “Descending” option, per artist, of course.

**Comment by soncaokim** [comment]
Closing this since it will be possible with the next release (to tweak sorting options)
