### ISSUE TITLE
Playlist ignores songs with paths that have spaces

### ISSUE THREAD

**Issue by 3marcusw** [AdrienPoupa/VinylMusicPlayer#556]
**Describe the bug**
When using m3u playlists, songs with spaces in their path are ignored

**To Reproduce**
1. Have m3u playlist with songs with spaces in path
2. Open PLAYLISTS tab
3. Open playlist
4. Notice lack of songs

**Expected behavior**
Songs should appear even if they have spaces in their path name

**Additional context**

**Comment by soncaokim** [comment]
If I'm not wrong the M3U reading support right now depends on the Android OS implementation. 

At it's not brilliant: On my end, the behaviour is quite erratic (playlists not updated in tens of minutes).
