### ISSUE TITLE
Separate the notification bar from the album artwork

### ISSUE THREAD

**Issue by StarPepe** [AdrienPoupa/VinylMusicPlayer#563]
**Is your feature request related to a problem? Please describe.**
Certain pieces of album artwork blend in with the notifications bar, especially those that are entirely white. 
This makes it impossible to see the time, notifications and battery percentage without obscuring the album artwork, of which I'd like to be undisturbed. Here's an example:

![Screenshot_20220106-215852](https://user-images.githubusercontent.com/96881600/148452519-782a94ed-199e-45e9-ba1a-8cc008269368.png)

A less severe example, but annoying nonetheless:

![Screenshot_20220106-215538](https://user-images.githubusercontent.com/96881600/148453342-09f1f41f-a4df-41ce-8855-bcbecd460246.png)

**Describe the solution you'd like**
I would like to see the notifications bar separated from the album artwork as shown in my example below. I've simply dragged the album artwork downwards a bit:

![Screenshot_20220106-215924](https://user-images.githubusercontent.com/96881600/148452998-c4dfafcd-8c20-41c5-bece-03b7bfae9943.png)

![Screenshot_20220108-093039](https://user-images.githubusercontent.com/96881600/148637652-a9b2fe9b-96cc-42a5-ade6-0d6fcb65b697.png)

I understand that this is probably very low priority, but the UI of this app is already excellent, and this change would, in my opinion, only improve upon it.

**Comment by MintMain21** [comment]
A really simple fix that looks quite lovely. :+1:

**Comment by StarPepe** [comment]
> A really simple fix that looks quite lovely. 👍

Thank you! 
I am no dev, but it seems like it would be a simple change to make.

**Comment by MintMain21** [comment]
No u
