### ISSUE TITLE
Play Next from this song on

### ISSUE THREAD

**Issue by aoloe** [AdrienPoupa/VinylMusicPlayer#566]
**Is your feature request related to a problem? Please describe.**

I often want to set the next album to be played without disrupting the sound.
I want the current song to finish and then play the selected song and continue from there (album or playlist)

**Describe the solution you'd like**

I'd like to be able to choose if "Play next" only plays the select song and then the previous queue continues or if a new queue is build starting from the selected song.

**Describe alternatives you've considered**

This could be implemented as a setting ("Play next only plays a single song" would be the current behavior; then "Play next" would behave differently depending on the state of this setting) or by a new action in the menu for the songs (just after "Play next").

**Additional context**

I can try to produce a patch, if there is an agreement on this feature being useful and on the way it should be implemented.

**Comment by soncaokim** [comment]
I'm experimenting a fix for this, upon tapping on a song, the user is asked to choose between
- Replace old queue
- Append to existing queue
- Insert after currently playing song

For additional info: https://github.com/AdrienPoupa/VinylMusicPlayer/pull/584

**Comment by aoloe** [comment]
thanks @soncaokim  for caring.

i'm not sure that your patch is a solution for the feature i was asking for.

what i want is that i can say to vinyl, that when it's done with playing the current song, it should play the tapped song and continue playing from there.
