### ISSUE TITLE
[Feature Request] Multi album progress 

### ISSUE THREAD

**Issue by droidberg** [AdrienPoupa/VinylMusicPlayer#57]
is there any chance that you could please add the ability to save the progress of more than one album at a time? i switch from various albums through the day and i have to start from scratch when i switch back and forth. it would be great to return to various albums and start back from where i left off.

**Comment by ildar** [comment]
That reminds me of Bookmark feature of Odyssey player

**Comment by droidberg** [comment]
@ildar ive never used odyssey player but what im suggesting isnt a bookmark feature but rather that the app keep the progress of all albums and tracks until the user wishes. this would be amazing because it would make vinyl a pretty great audio player and not just music player.
