### ISSUE TITLE
Bluetooth car audio autoplay

### ISSUE THREAD

**Issue by Offerel** [AdrienPoupa/VinylMusicPlayer#574]
Can we please have a option that Vinyl is starting playing music, when the phone connect to the car Bluetooth audio?

I thought this is the case as I have installed the app some weeks ago. But after changing the phone and reinstall the app there, this is not more the case.

Maybe I didn't find the correct option to enable this behavior, if so, please let me know how I can enable this function.

**Comment by soncaokim** [comment]
The app does not support this. It's often an option/feature outside of the app - in the OS or in the Android Auto app for instance.

**Comment by Offerel** [comment]
Currently I'm using MacroDroid to start Vinyl, if my car audio mac address is connected. It works, but I have previously installed MediaMonkey Pro, before Vinyl and had massive issues with that function. That's why I asked.

Since MacroDroid works as a workaround, we can close this issue.
