### ISSUE TITLE
Vinyl not responding to intents

### ISSUE THREAD

**Issue by fuzxi** [AdrienPoupa/VinylMusicPlayer#577]
**Describe the bug**
I'm trying to play some music by sending an intent from Tasker. When I send either of the below intents, Vinyl will open, but nothing else happens.

**To Reproduce**
_Intent to play all media from search:_
Action: android.media.action.MEDIA_PLAY_FROM_SEARCH
Category: Default
Extra: MediaStore.EXTRA_MEDIA_FOCUS:vnd.android.cursor.item/*
Extra: query:Okabe
Package: com.poupa.vinylmusicplayer
Target: Activity

_Intent to play a specific track:_
Action: android.intent.action.VIEW
Category: Default
Mime type: audio/*
Data: file://Music/Lullabies/207-keiichi_okabe-repose.flac
Package: com.poupa.vinylmusicplayer
Target: Activity

**Expected behavior**
First intent: Vinyl should start playing all tracks that contain "Okabe" in their name, artist, and/or album metadata.
Second intent: Vinyl should start playing the specified track.

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - Android Version: 12 (also experienced on 11)
 - ROM: CalyxOS 3.2.0
 - Vinyl Music Player Version: 1.3.0

**Additional context**
Vinyl does not have any denied permissions, and can play the songs in question if I select them in Vinyl.

If I send the same intents and specify Vanilla Music Player (https://github.com/vanilla-music/vanilla) as the package instead of Vinyl, it works as expected. The first intent plays all 20 tracks which match the query string, and the second opens a pop-up to play the specified file. So I'm reasonably sure that my intents aren't the issue, but maybe Vinyl just requires different syntax?

**Comment by soncaokim** [comment]
If you are able to debug and submit code patch, I can explain to you my understanding of the issue and the suggestion on where the issue would be.

**Comment by soncaokim** [comment]
I suppose the intent should be handled here: https://github.com/AdrienPoupa/VinylMusicPlayer/blob/6f96a68e69ce4cfadaa32eff7a7901e0d219d4e2/app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/MainActivity.java#L268

**Comment by fuzxi** [comment]
Thanks, I'll look into it.

**Comment by elesto** [comment]
Just tested on my Xperia 5 II android 11. It works just fine for me

**Comment by fuzxi** [comment]
Can you share the intent you used?

**Comment by elesto** [comment]
I tested this one:

Action: android.media.action.MEDIA_PLAY_FROM_SEARCH
Category: Default
Extra: MediaStore.EXTRA_MEDIA_FOCUS:vnd.android.cursor.item/*
Extra: query:Okabe
Package: com.poupa.vinylmusicplayer
Target: Activity

**Comment by elesto** [comment]
Sorry to post here but there is no way to contact @fuzxi and I want to ask them if they know an intent to open vinyl and play a specific playlist on shuffle.

**Comment by fuzxi** [comment]
> Sorry to post here but there is no way to contact @fuzxi and I want to ask them if they know an intent to open vinyl and play a specific playlist on shuffle.

I have not yet been able to get Vinyl to react to any intents, so I can't help you with that currently.

**Comment by elesto** [comment]
I have only been able to get the query intent to work. The others just open the app so there is a problem
