### ISSUE TITLE
Playlist clears after trying to delete more than one track

### ISSUE THREAD

**Issue by arigawalin** [AdrienPoupa/VinylMusicPlayer#580]
**Describe the bug**
When deleting multiple selected tracks, it clears the whole playlist.

**To Reproduce**
1. create a Playlist with any number of tracks
2. go to playlist
3. select more than one track
4. select Option to remove tracks from playlist and accept when prompted
5. Playlist appears/is empty

**Expected behavior**
Only the selected tracks are removed from the playlist.

**Smartphone:**
 - Device: Samsung A5 (2017) (SM-A520F)
 - Android Version: 11
 - ROM: LineageOS 18.1
 - Vinyl Music Player Version: 1.3.0

**Comment by soncaokim** [comment]
I'll have a look
