### ISSUE TITLE
Songs no longer sort alphabetical

### ISSUE THREAD

**Issue by DraconicNEO** [AdrienPoupa/VinylMusicPlayer#582]
**Describe the bug**
In the latest update songs are no longer sorted in alphabetical order and are just randomly arranged in the albums when they don't have track numbers. Originally it would sort these songs alphabetically but it's not doing that anymore.

**To Reproduce**
1. Install version 1.3.0
2. Scan for Songs in the beginning
3. Check an album that doesn't have track numbers

**Expected behavior**
The Songs Should be ordered in Alphabetical order when no track numbers are present just like how it was before 1.3.0.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 4
 - Android Version: 7.0
 - ROM: Miui 8.5.4.0
 - Vinyl Music Player Version: 1.3.0

**Additional context**
Songs will organize by track number but if Track number isn't present it will be a jumbled mess.

**Comment by soncaokim** [comment]
I will have a look
