### ISSUE TITLE
Add support to play playlist-files (.m3u or .m3u8 )

### ISSUE THREAD

**Issue by k3b** [AdrienPoupa/VinylMusicPlayer#590]
**Is your feature request related to a problem? Please describe.**
i like to prepare playlist-m3u-files for different moods on my laptop, 
transfer the m3u-s to the android and then play the playlist-m3u-s on android.

Note: laptop and android have the same relative directories and mp3 filenames

See also https://www.reddit.com/r/fossdroid/comments/u07ods/any_music_player_that_can_read_m3u_playlist_files/

**Describe the solution you'd like**
after opening a  .m3u or .m3u8 file from filemanager or bookmark with relative file names the player app tries to find the corresponding music file.

------

.m3u or .m3u8 file is a text file 

Lines are either comments (prefixed with "#") or relative or absolute file paths.

example

<pre>
#EXTM3U
# This is a comment

# file path is relative to m3u file.
wellness/water.mp3
# example if this file is /storage/1234-5678/MUSIC/my-playlist.m3u
# then /storage/1234-5678/MUSIC/wellness/water.mp3 is the path of the referenced mp3 file
</pre>

----

Implementation detail:  the app must implement

action: VIEW 
mime: audio/x-mpegurl
data: uri of the m3u /m3u8 playlist file

**Comment by Offerel** [comment]
This was closed automatically. Is there some chance to reopen the request?
