### ISSUE TITLE
App closes quietly when in the background during playback in the middle of songs

### ISSUE THREAD

**Issue by ElSamhaa** [AdrienPoupa/VinylMusicPlayer#596]
**Smartphone (please complete the following information):**
 - Device: Redmi Note 10 Pro
 - Android Version: 12
 - ROM: miui.eu MIUI 13.04
 - Vinyl Music Player Version: 1.3.0

**Comment by jcperil** [comment]
Is there a different outcome with earphones and without it?

**Comment by ElSamhaa** [comment]
@jcperil I don't remember tbh.

**Comment by alphanerdgen** [comment]
@ElSamhaa If you are battery-optimizing the app then that could be the reason. Disable it and then see if it resolves the issue.

**Comment by ElSamhaa** [comment]
Nope, not it.

I already have the battery optimization disabled completely for this app.
