### ISSUE TITLE
No Equalizer found displayed in Vinyl app settings 

### ISSUE THREAD

**Issue by bonniemunene** [AdrienPoupa/VinylMusicPlayer#603]
** Settings windows in Vinyl app displays no equalizer found . Click on the equalizer  does nothing. My phone has an EQ system app- DTS sound
![Screenshot_20220615-012503](https://user-images.githubusercontent.com/73817057/173919887-a62d121e-e930-40e9-8a65-7c63ae6548d1.png)
![Screenshot_20220615-012345](https://user-images.githubusercontent.com/73817057/173919964-80812177-fc46-4757-ba47-8fbfc0c2514d.png)
 that does a perfect job. I don't why vinyl music says not EQ found.**

1. Go to settings
2. Scroll down to Equalizer and click on it
3. Does nothing and shows no EQ found

**Expected behavior**
Opening a EQ window, changes sound depending on the settings i choose
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Infinix Smart 5
 - Android Version: 10 Go edition
 - ROM: XOS 6.2 
 - Vinyl Music Player Version: 1.3.0

**Additional context**
Exiting the app opening the EQ app  DTS sound 
Seems to change the sound coming from Vinyl app

**Comment by kairusds** [comment]
This is also the case on my Redmi Note 12 Turbo, MIUI 14 and Android 13.

**Comment by kairusds** [comment]
Seems that this is an issue Android 11+ for every device: https://stackoverflow.com/questions/73381390/how-to-detect-if-an-android-phone-has-a-built-in-equalizer (check the comments)
