### ISSUE TITLE
Some Artist Images Not Displaying

### ISSUE THREAD

**Issue by RichCat6** [AdrienPoupa/VinylMusicPlayer#611]
**Describe the bug**
Some artist images refuse to display. I don't know if it's my phone, which in and of itself acts pretty weird, but this seems to me like a software issue.

**To Reproduce**
1. Scroll down on the artists menu.

**Expected behavior**
To display artist pictures properly and efficiently.

**Screenshots**
![Screenshot_20220804-104356_Vinyl Music Player](https://user-images.githubusercontent.com/99022764/182876178-b5d77a8e-30a9-4439-a084-bbf82096bb9c.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung A11
 - Android Version: Version 10
 - ROM: It's just default Android, no funny stuff.
 - Vinyl Music Player Version: 1.3.0

**Additional context**

**Comment by soncaokim** [comment]
Hello, right now the artist images are fetched from Deezer (correspoding code in `**/ArtistImage*.java` if you want to investigate further). My guess is that Deezer is not returning any matching image for the artists in your library.

**Comment by RichCat6** [comment]
> Hello, right now the artist images are fetched from Deezer (correspoding code in `**/ArtistImage*.java` if you want to investigate further). My guess is that Deezer is not returning any matching image for the artists in your library.

I know this is not the problem. If I reinstall the app, it will have the same issue with different artist images which would usually load without any problem.

**Comment by soncaokim** [comment]
There is an option that prevent searching from web service (deezer) if you are not on wifi - this can be disabled in settings.

Otherwise, if you go to the artist page, and tap on the option "reset artist image" in the three dots menu on top right, will the image gets fetched and saved consistently?

**Comment by RichCat6** [comment]
> There is an option that prevent searching from web service (deezer) if you are not on wifi - this can be disabled in settings.
> 
> Otherwise, if you go to the artist page, and tap on the option "reset artist image" in the three dots menu on top right, will the image gets fetched and saved consistently?

No. It won't.
