### ISSUE TITLE
New notification design bug

### ISSUE THREAD

**Issue by x2k13** [AdrienPoupa/VinylMusicPlayer#62]
Hello, I'm using a Moto X Play running Nougat 7.1.1. I like the built in Moto Info function (lock screen overlay providing some useful info about time, battery info, app notifications etc.) Using Vinyl with the old style notifications enables player controls in Moto Info as expected, but switching to the new, colored notification style breaks that. The player controls don't do anything anymore. Not a big issue but maybe worth looking at.

**Comment by AdrienPoupa** [comment]
Can't reproduce without your specific device, sorry
