### ISSUE TITLE
Counter overflow when listening to playlists

### ISSUE THREAD

**Issue by Justin00015** [AdrienPoupa/VinylMusicPlayer#66]
![Picture of it happening](https://user-images.githubusercontent.com/26168814/42136679-0ee5cf1a-7d2e-11e8-8df7-e58a3169539a.jpg)
I'm on version 0.17.0.

**Comment by AdrienPoupa** [comment]
It's actually a feature showing that your current track is 5 tracks away from the beginning of your playlist.
