### ISSUE TITLE
Problems with Artist and Album Artist

### ISSUE THREAD

**Issue by jacob-emery** [AdrienPoupa/VinylMusicPlayer#67]
Lets say that the CD's album artist is "Quartet", and there are 8 songs in the album. The first 2 are played by "Artist A", another 2 are played by "Artist B", another 2 are played by "Artist C", and the remaining 2 are played by "Artist D",

ALBUM INTERFACE
In the album interface, Vinyl will show only the name of "Artist A" (or maybe another one) instead of showing "Quartet".
The fix here would be to show the album artist instead of one of the artist, while in the album interface.

ARTIST INTERFACE
What's even worse, in the artist interface only "Artist A" will be shown, and the other Artist won't (the strange thing is that if you search them, e.g. "Artist B", you will find them).
The fix here would be to show also "Artist B", "Artist C" and "Artist D" in the artists interface (and if the mentioned names are visible, "Quartet" shouldn't be visible).
The app would be wonderful if, in the app settings, it would be possible to choose to display only the album artists instead of all the artists (this possibility obviously only in the Artist interface and not in the Album interface, there should be displayed only album artists). So to insert a toggle which enables either:
- artist album (if a CD has a unique album artist, only the artist album is visible in the album interface and artists (e.g. "Artist A" or "Artist B") for that album are not visible. If a CD only contains information about artist and the section album artist is empty i.e. "", then (since album artist is empty) the one of the artists will be shown for that CD. If in the CD the artist album is "", but all song's artist names are the same, this won't be a problem, because the correct name will be assigned).
- all artists (and when this is enabled, album artists are not displayed in the artist interface, but only artists).

Please let me know what you think about this! Thank you for reading.

**Comment by GeoZac** [comment]
The same issue is present in upstream project,so a fix may take time.

**Comment by vovchykbratyk** [comment]
I second this request.  There was a long standing bug in mediaStore that corrupted the ALBUM_ARTIST field and caused it to return the ARTIST value.  I am curious as to whether this was fixed in Pie.  If so, fetching this value and offering the user an option to show Track Artists or Album Artists (like DoubleTwist does using their own scanner/db) would be pretty easy.

**Comment by trymeouteh** [comment]
I have this issue too. It should grab the Album Artist tag and use that to define the artist of the whole album. Each song should use the Artist tag.

**Comment by AdrienPoupa** [comment]
Related to https://github.com/kabouzeid/Phonograph/pull/216

**Comment by smichel17** [comment]
:(
