### ISSUE TITLE
Opus codec support

### ISSUE THREAD

**Issue by wyjek** [AdrienPoupa/VinylMusicPlayer#68]
Hi, could you please add support for .opus files? I have a lot of them and I have to use another music player to play them. The codec is open-source and great for music playback at a small file size.

**Comment by derefff** [comment]
I want this feature too.

**Comment by Keith94** [comment]
Related: https://github.com/kabouzeid/Phonograph/issues/500

**Comment by Ypnose** [comment]
Actually, Opus files are perfectly detected and played when you use the right extension, which is <code>.ogg</code>. All my songs are opus.

**Comment by GeoZac** [comment]
AOSP has not taken any action even though the issue the issue has been on their bug tracker for too long.Custom ROMs have taken a favourable step by adding support.

**Comment by Ypnose** [comment]
Opus extension is now handled as ogg on LineageOS ROM, for example. But encoding files as opus in an ogg container is working flawlessly.

**Comment by GeoZac** [comment]
@Ypnose Lineage team merged support for *.opusso renaming is not required in Lineage based ROMs,I'm not sure if AOSP based custom ROMs have adopted this change

**Comment by Ypnose** [comment]
Of course, that's what I'm saying. I'm the guy who reported it on the LOS IRC. <code>*.opus</code> was then added.
But, if you are not on LOS or a ROM supporting <code>*.opus</code>, encoding your opus in a ogg container might be a solution, in the meantime.

**Comment by Zeik0s** [comment]
On my Mi A1 (Vanilla 8.1) an Opus File renamed to `.ogg` can't be played. Reading these Comments and related Issues of Phonograph i thought this should work?

**Comment by GeoZac** [comment]
@stephendt Opus support was added to the pie branch of LineageOS on Jan 05,so try a build later than Jan 05

**Comment by leewdch** [comment]
> encoding your opus in a ogg container might be a solution, in the meantime.

The tag editor is unable to edit, save and fetch metadata if you use an .ogg container with an .opus file. I tried a different tag editor and it couldn't recognize the file header. I'm currently on [LiOS 16 on my redmi note 4x](https://forum.xda-developers.com/redmi-note-4/xiaomi-redmi-note-4-snapdragon-roms-kernels-recoveries--other-development/rom-lineageos-16-0-t3830602)
