### ISSUE TITLE
Empty playlist after remove SD card

### ISSUE THREAD

**Issue by ok38** [AdrienPoupa/VinylMusicPlayer#69]
Hi,

I have all my music on external SD card, when i remove [when phone working] and put after, all playlists are blank. This not changes even i save the playlist. Is there a way to import .m3u playlist or another playlist format ?

Thanks.

**Comment by GeoZac** [comment]
That is supposed to happen as the SD card is remounted it will be given a new Label( Like XXXX-YYYY) ,if you can manually replace the lable to the new one,you should be able to use the old playlists

**Comment by ok38** [comment]
I tried to know if the mounting point change :

`/mnt/media_rw/14BD-090F`
`/mnt/runtime/default/14BD-090F`
`/mnt/runtime/read/14BD-090F`
`/mnt/runtime/write/14BD-090F`
`/storage/14BD-090F`

There is no change before and after. I have to rescan library/folder each time to have music but the playlist is still empty.

**Comment by GeoZac** [comment]
Are you sure the playlists have same mount points, you can open the playlist in any text editor

**Comment by ok38** [comment]
The saved playlist file has this;

'/storage/14BD-090F/.../*.flac or .mp3'

And where the temporary playlist is stocked ? Maybe I can found something there.

**Comment by rstruminski** [comment]
I have a similar issue that may be related to this: After removing and re-inserting my SD card, I can't even play a single file. I rescanned all my music several times. When trying to scan from the menu, nothing happens. When scanning a folder in folder view, using the scan button on the top right, it will say, for example, "340 files scanned". But when I click any file, it says "file is not in the media library".

The library always stays empty, except for some stuff on my internal memory (which isn't music, but only a few voice messages etc.).

**Comment by megamorphf** [comment]
I have a similar issue when playlists appear and dissapear at random (I'm using Syncthing) to sync them.  What I've noticed is that you need some sort of trigger to force the playlists to be rediscovered.  For me adding a song to Favourites helped one time.  But not others.

I think it would be smart to add an event for refreshing playlists every time playlists button is pressed in the app.  Or even better an ability to import playlists to the app.

**Comment by Nathoufresh** [comment]
Same problem when rebooting my Poco F1 on Los16, I didn't experience it whith my Galaxy J5 2016 Stock marshmallow. Musics were on external SD in both cases.

**Comment by AdrienPoupa** [comment]
Related to Android Mediastore, not Vinyl directly, ie: the issue you describe should be reproducible with any other player using Android Mediastore's playlists
