### ISSUE TITLE
[CRASH] playing ogg on Android 4.2 JB

### ISSUE THREAD

**Issue by ildar** [AdrienPoupa/VinylMusicPlayer#7]
Android 4.2 JB/CM10.1. Freshly started player crashed on the 1st audio file. Just tapped the file to play it. [adb.logcat.log](https://github.com/kabouzeid/Phonograph/files/1655180/adb.logcat.log)
This was reported at Phonoraph's issue tracker: https://github.com/kabouzeid/Phonograph/issues/418 , but actual crash happens on Vinyl.

**Comment by AdrienPoupa** [comment]
Hi,
There is another issue about supporting opus files. Would you say it's related?

**Comment by AdrienPoupa** [comment]
OK, can you upload the file causing it to crash somewhere so I can try to reproduce? Also I think you reported the bug on Phonograph's bug tracker, does it still crash there? Thank you!
