### ISSUE TITLE
No write access to SD card on Android Oreo

### ISSUE THREAD

**Issue by TheoRet** [AdrienPoupa/VinylMusicPlayer#82]
Hello! Thanks for this nice music player.
I downloaded it via fdroid on Lineage OS 15.1.

I was trying to use the tag editor for my mp3 files which are on a 64gb SD card. Unfortunately my tag changes are not saved. 

I tried again on a single mp3 file on my internal storage and it worked. So it seems to be a permission problem. Has this already been reported? 

I think this problem is not specific to VinylMusicPlayer. Rocket Player's tag editor e.g. doesn't work either on my Android version (although it does work on my other phone with Lollipop) . The only app I found so far to properly ask for write access to SD card  is AnExplorer Pro. 

Is it possible to improve this? This feature is really important to me because I use tags to manage Playlists. Apart from that I am very satisfied with the design and functionality.

Thanks, Theo

Device info:
---
<table>
<tr><td>App version</td><td>0.18.0</td></tr>
<tr><td>App version code</td><td>157</td></tr>
<tr><td>Android build version</td><td>f966a6d859</td></tr>
<tr><td>Android release version</td><td>8.1.0</td></tr>
<tr><td>Android SDK version</td><td>27</td></tr>
<tr><td>Android build ID</td><td>lineage_mido-userdebug 8.1.0 OPM6.171019.030.H1 f966a6d859 dev-keys</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>mido</td></tr>
<tr><td>Device model</td><td>Redmi Note 4</td></tr>
<tr><td>Device product name</td><td>lineage_mido</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by tbdal** [comment]
Hey, 

i get the same behaviour on los14.1 on sumire
It would be great if you could check if you could solve this.
In addition I can see in the log whenever I click save:

System.err at com.poupa.vinylmusicplayer.ui.activities.tageditor.AbsTagEditorActivity$WriteTagsAsyncTask.doInBackground(Unknown Source)

**Comment by TheoRet** [comment]
Ok, so it is not a specific Oreo problem after all.

I found another app that can edit tags of mp3 files on my external SD card - Vanilla Music Player via the Tag editor Plugin. It specifically asks for permission to write on this SD card on the first try. However Vanilla MP is lacking some important features that Vinyl MP has..

**Comment by AdrienPoupa** [comment]
Should be fixed with https://github.com/AdrienPoupa/VinylMusicPlayer/commit/1d079817df3eb324676ad3c1a57db2bb1941fa03

Please reopen if issues are present, since I don't have a device with an SDCard I can't really debug.
