### ISSUE TITLE
Sleep timer

### ISSUE THREAD

**Issue by M1Aston** [AdrienPoupa/VinylMusicPlayer#83]
The sleep timer option is too limited. Other players have options like

    stop playing after x number of files.
    stop after x hours\minutes but always finish the playing file.
    close the program after stopping playback by the sleep timer.

Please improve the sleep timer.

**Comment by trymeouteh** [comment]
Please add a setting to decrease the volume or have a db limit. With other sleep timers this is handy incase the next song played doesn't wake you up.
