### ISSUE TITLE
fast forward and back button

### ISSUE THREAD

**Issue by M1Aston** [AdrienPoupa/VinylMusicPlayer#84]
Sadly missing from the program: fast forward and rewind the playing track. Why is it not there? ;-)

I aslo think clicking the Back button (a number of times) should always close the program completely.  As it is now, it stays active as is shown in the Status Bar\Notification Area. Please add a completely close the program option.

**Comment by M1Aston** [comment]
A feature I "stole" from another player. :-)
Swipe down, go 10 seconds forward.
Swipe up, go 10 seconds back.
Would be nice to have this feature.

**Comment by Vrihub** [comment]
+1 definitely a basic feature missing!
I guess that swipe up/down and left/right are already assigned and would be troublesome to re-assign. Maybe the most intuitive way to implement is by long-pressing the Prev/Next buttons, as it was in the classic android stock music player.

**Comment by deragon** [comment]
Double tap on the right or left side of the image would rewind or fast forward 10s would be an option.  Also, on a 1 hour podcast, the progress bar (whatever it is called) can be moved by hand, but the precision is non existent.  Something needs to be done to increase precision.  Say I go to around about 1/3 of the podcast, then another window on top would show up, some kind of zoom on the progress bar, showing the cursor within a 10 mins window where the user could then more precisely select where to play from.

**Comment by M1Aston** [comment]
Shake the phone = 10 sec forward. 
Brilliant feature (again, stolen from another player :-))

**Comment by deragon** [comment]
@M1Aston, shaking only is not good.  Sometimes your phone rest on a table and you do not want to have to pick it up.  In addition to shacking (which should be an option; we could debate if it should be on or off by default), we should have visual buttons on Vinyl such as the one found at this link for [forwarding 10s](https://iconscout.com/icon/forward-10-second) (yes, I am aware that the icon is not _libre_; we would need to find one that has a proper licence).

**Comment by M1Aston** [comment]
Shaking/ff as an option would be fine.
I find it a fantastic feature. It's. for example, for skipping ads and other "stuff" you don't like in podcasts.
Yeah, sometimes the phone is on the table, but also sometimes it is in my coat pocket (while cycling or walking). Again, being able to skip parts (ff 10 seconds per shake, if that's proper english) without taking the phone from your pocket is absolutely great.

**Comment by deragon** [comment]
@M1Aston, do not get me wrong;  I am sold on your idea.  We just agree that it is not enough and some visual means should be made available.  A+
