### ISSUE TITLE
Excessive memory usage

### ISSUE THREAD

**Issue by BOB74j** [AdrienPoupa/VinylMusicPlayer#85]
com.poupa.vinylmusicplayer process memory usage is often in excess of 100 MB, even when music is not playing. Issue can be reproduced by playing a track, pausing, and dismissing notification. Memory usage remains high until music player service is force stopped. App version 0.18.0, Android 7.0.

-

Device info:
---
<table>
<tr><td>App version</td><td>0.18.0</td></tr>
<tr><td>App version code</td><td>157</td></tr>
<tr><td>Android build version</td><td>9</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NPNS25.137-93-4</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>potter</td></tr>
<tr><td>Device model</td><td>Moto G (5) Plus</td></tr>
<tr><td>Device product name</td><td>potter</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by mikhoul** [comment]
I was looking to see if I was alone with huge amount of memory being used, here it is always between 250-300 MB even when not in use.

![image](https://user-images.githubusercontent.com/5678673/59559396-6f9e6100-8fd4-11e9-9cbc-b7325852c519.png)
