### ISSUE TITLE
[Feature] Rating ID Tag and Tab

### ISSUE THREAD

**Issue by svoop** [AdrienPoupa/VinylMusicPlayer#89]
For people like me who have rated songs in other applications, this would be a killer feature:

Make the "rating" ID tag editable in the tag editor and add a tab which sorts all songs by "rating". In order to accomodate many rating scales, numbers from 0.0 (=truely awful) to 5.0 (=absolutely stunning) would do since they can map the traditional "5-star-scale" as well as finer scales with up to 50 steps.

In order to get the ratings fro an external application, all you have to do is persist the ratings in the ID tags. For example:  Swinsian on Mac stores those ratings in a SQLite3 db, all it takes is a little script to write/read these to/from ID tags. I'd contribute such a script as an example, unfortunately, I have no Andoid kudos and can't contribute this feature itself.

What do you think?

**Comment by ManchurianSector** [comment]
Also, if it is possible, it would be really cool to support the fmps_rating tag, which is already being used in some music apps such as gmusicbrowser.

**Comment by svoop** [comment]
Too bad to go stale, it would really kick ass and be one of a kind.
