### ISSUE TITLE
Album Cover

### ISSUE THREAD

**Issue by coding-JEF** [AdrienPoupa/VinylMusicPlayer#90]
When I set a new album cover, it displays not the one I have set, but one random from my media pictures.

-

Device info:
---
<table>
<tr><td>App version</td><td>0.18.0</td></tr>
<tr><td>App version code</td><td>157</td></tr>
<tr><td>Android build version</td><td>G850FXXU2CQK1</td></tr>
<tr><td>Android release version</td><td>5.0.2</td></tr>
<tr><td>Android SDK version</td><td>21</td></tr>
<tr><td>Android build ID</td><td>LRX22G.G850FXXU2CQK1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>slte</td></tr>
<tr><td>Device model</td><td>SM-G850F</td></tr>
<tr><td>Device product name</td><td>sltexx</td></tr>
<tr><td>Device hardware name</td><td>universal5430</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by AdrienPoupa** [comment]
Please try the "Ignore Media Store covers" setting
