### ISSUE TITLE
Widget gets transparent when the device is rotated

### ISSUE THREAD

**Issue by GermanGospel** [AdrienPoupa/VinylMusicPlayer#92]
I don't see the new "transparent widget" in the list of widgets, but since 0.18.0 there is a bug that sets the normal 3 widgets to transparent, when I rotate the device. If I touch the widget and start a song and go back, the widget is back to normal, till the next rotation.

Tested on stock Android 8.0 on Sony XZ1.

**Comment by ErebosGR** [comment]
It didn't get fixed for me. In fact, since 0.20.0 the widget stays transparent even after I enter and exit the app. I can't get it to go back to normal unless I remove it from the homescreen and place it again.

Xiaomi Redmi Note 4X. Android 7.0 MIUI 10

**Comment by AdrienPoupa** [comment]
For me, toggling the option in the settings changes it right away. I'm on LineageOS16

**Comment by GermanGospel** [comment]
@AdrienPoupa - Thanks for hinting at the settings toggle. The widget was transparent for me, even so the toogle was set to 'off'. After toggling to 'on' and back to 'off' the widget is no longer transparent.

**Comment by GermanGospel** [comment]
Too bad: The widget changed to transparent again, without me toggling the option.

**Comment by AdrienPoupa** [comment]
I can reproduce it and I'll investigate it

**Comment by AdrienPoupa** [comment]
Fixed, thanks for the reports. The widgets were due for a big refactoring anyway
