### ISSUE TITLE
Bug: Scan media stops, nothing is refreshed

### ISSUE THREAD

**Issue by tomsquest** [AdrienPoupa/VinylMusicPlayer#94]
Hi,

I have a bug/crash happening when I `scan media`. 
The `scan media` notification appears, then disappeared and nothing is refreshed.
For example, the blacklist is not taken into account, so I assume that nothing gets refreshed.

Here is the info from the version installed:

```
App version: 0.18.0
App version code: 157
Android build version: eng.davide.20170920.161708
Android release version: 7.1.2
Android SDK version: 25
Android build ID: NJH47F
Device brand: ZUK
Device manufacturer: ZUK
Device name: z2_row
Device model: Z2 Pro
Device product name: z2_row
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

```

I don't know how to get the logs.

**Comment by evilphish** [comment]
Same problem here on a new Oneplus 6T. Installed app, clicked scan, nothing happens. Also when using the folder mode and browsing to an mp3 file does not play the file. Instead an error is shown that the track is not listed in the media store. VLC finds the tracks, scans them and works without issue.

```
App version: 0.19.2
App version code: 160
Adroid build version: 1812260627
Android release version: 9
Android SDK version: 28
Android build ID: ONEPLUS A6013_45_181226
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus6T
Device model: ONEPLUS A6013
Device product name: OnePlus6T
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs: (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
```

**Comment by juneverse** [comment]
Same Problem on a Nokia 5.1 with Android 9

<table>
<tr><td>App version</td><td>0.22.1</td></tr>
<tr><td>App version code</td><td>167</td></tr>
<tr><td>Android build version</td><td>00WW_3_19C</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>00WW_3_19C</td></tr>
<tr><td>Device brand</td><td>Nokia</td></tr>
<tr><td>Device manufacturer</td><td>HMD Global</td></tr>
<tr><td>Device name</td><td>CO2N_sprout</td></tr>
<tr><td>Device model</td><td>Nokia 5.1</td></tr>
<tr><td>Device product name</td><td>Core2_00WW</td></tr>
<tr><td>Device hardware name</td><td>mt6755</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

I think it first happened after the upgrade to Android 9 (not sure though)
