### ISSUE TITLE
Doesn't play/find ogg files

### ISSUE THREAD

**Issue by hvdwolf** [AdrienPoupa/VinylMusicPlayer#96]
Vinyl Player 0.18.0 on Motorola G5+ on Android 8.1

I mostly use playlists
Half of my playlists is in ogg format (open source, just like vinyl music player)
- In album view, the albums do not show up.
- In Playlists view, the playlists are empty
- In map view I can access the map, but when I tap the ogg file, vinyl music player mentions "XYZ.ogg is not available."

Other apps like Google Play Music and Pulsar do play ogg, so it is not a missing codec on my phone.
Anything I should adjust on my phone? Or is this a bug?

**Comment by hvdwolf** [comment]
I mentioned that half of my library is in ogg.
I stumbled through quite some playlists further and one playlist containing oggs did play. That playlist contains oggs that have embedded "album art" images. Vinyl Music Player does play those oggs.
All those albums/playlists do contain album art in the folder, but that doesn't make them playable. This afternoon I used easytag to embed quite some album art directly into the oggs (next to the album art already in the playlists/album folders).
Now, with embedded images/album art INSIDE the ogg, they are played by VinylMusicPlayer.

**Comment by Roever1** [comment]
I have a similar problem on shift 6m with Android 8.0.
Oggs take ages to load and play, the player freezes for more than 10 seconds after I start the file. while playing its not a problem to stop and restart. Some logs are only playable if started from a third party file holster.

**Comment by leewdch** [comment]
I had troubles using ogg vorbis files as well so I tried encoding using opus and .ogg as container. It worked wonderfully. The only con is you won't be able to use the tag editor due to the incorrect header. Personally, I'll use mp3 for now waiting for a true ogg vorbis support

**Comment by eworm-de** [comment]
I have been wondering why my ogg files are not showing... This one is a good explanation.

I will try to embed the artwork, I have it around anyway.

Still... Any chance for a proper fix?

**Comment by eworm-de** [comment]
I noticed I can see some of my ogg files, but not the recent additions. Turns out the player is happy with any kind of (external) artwork, but it needs to find it. Named it `folder.jpg`, now all files are recognized (as far as I can tell).
